### ISSUE TITLE
Extension conflicts with Cloudflare site protection

### ISSUE THREAD

**Issue by JeffRockatansky** [ruffle-rs/ruffle#10037]
### Describe the bug

When Ruffle extension is enabled in a browser, it breaks "Verify that you are human" bot blocker on some sites (e.g. `chat.openai.com`).

The verification process is stuck in an infinite loop of `"Click 'Verify'" -> "Wait for page to reload" -> "Click it again"`

### Expected behavior

1. Enable Ruffle
2. Go to Cloudflare-protected site
3. Verification passes, site works

### Affected platform

Browser's extension

### Operating system

Ubuntu 20.04

### Browser

Google Chrome 108.0

### Additional information

Checked in every possible case (e.g. with or without other extensions, with or without strict privacy browser prefrences, with or without chrome flags), everything leads to Ruffle extension breaking Cloudflare protected sites.

**Comment by p0008874** [comment]
This also happened to me.

**Comment by n0samu** [comment]
Thank you for reporting this! It is probably caused by the polyfill code that Ruffle injects into each page. We would usually do something along the lines of #7146 to solve an issue like this, but it sounds like this might be affecting a large number of sites. So we'll need to study this further to come up with a good solution.

**Comment by n0samu** [comment]
Okay I tried accessing the suggested site (chat.openai.com) and didn't get any human verification prompts. When exactly does it happen? (I don't have an account with the site and I didn't attempt to make one)

**Comment by n0samu** [comment]
@p0008874 pointed me to https://captcha.website/ as a site to test this out. It worked fine for me with the Ruffle extension enabled, too. Not sure what's going on

**Comment by JeffRockatansky** [comment]
@JeffRockatansky Try clearing cookies and cache.

**Comment by EMREOYUN** [comment]
Same error here

**Comment by absurdismworld** [comment]
Having the same issue.

**Comment by sersorrel** [comment]
Ruffle also breaks signup on https://orionfeedback.org/.

**Comment by worenga** [comment]
Hi, I am from Cloudflare and I am the technical lead working on the challenges team.
We got a customer support inquiry about your Plugin and it seems you guys are overriding navigator.plugins to make it look weird.

**Comment by n0samu** [comment]
Thank you for reaching out, @worenga! As a Flash Player emulator, Ruffle's job is to get old Adobe Flash websites working again while requiring minimal effort on the part of the user or webmaster. Unfortunately, many websites used Flash detection scripts that check `navigator.plugins` for the presence of the Adobe Flash plugin and display a "Get Adobe Flash Player" message instead of the Flash content if Flash Player is not detected. To get Flash content to display in those situations, we need to add Flash Player back to `navigator.plugins`, but it is not normally modifiable from JavaScript. So we overwrite `navigator.plugins` with our own custom RufflePluginArray object that allows us to do this; see https://github.com/ruffle-rs/ruffle/blob/master/web/packages/core/src/plugin-polyfill.ts.

This approach has caused a few problems in the past, the most similar being #8842. We try to make RufflePluginArray behave as similarly as possible to the original `navigator.plugins` but there will always be detectable differences (including some purposeful ones, like using `ruffle.js` for the `Plugin.filename`). According to @Lord-McSweeney, Cloudflare is checking whether `navigator.plugins.item(2**32) === navigator.plugins.item(0)`, which is quite an esoteric behavior that none of us knew about before now. He just now implemented this behavior in RufflePluginArray, which will fix the issue with Cloudflare challenges according to his testing.

I understand that the purpose of Cloudflare challenges is to distinguish bots from normal users, so I imagine that finding and checking for these kinds of esoteric behavioral differences is basically your job. At the same time, we can't really stop overwriting `navigator.plugins` without breaking the Flash content that our users rely on, so I'm afraid that these types of problems will keep cropping up as you continue evolving your detection heuristics. Do you think @Lord-McSweeney's fix will be sufficient to prevent future problems, or is there more that you can suggest?

**Comment by JeffRockatansky** [comment]
Nice! Time to test.

**Comment by n0samu** [comment]
Hopefully the issue is resolved! Please leave a comment here if not.

**Comment by EMREOYUN** [comment]
Can confirm the issue has been resolved. Cloudflare check does not conflict on my tests.

**Comment by absurdismworld** [comment]
I'm not sure if the fix has been pushed to the chrome web store yet, but from my tests the issue persists on Chrome. Tested on clean Firefox and Chrome builds with just the Ruffle extension on "captcha.website".


https://user-images.githubusercontent.com/19274382/230232181-d451cdb6-c028-4879-b147-79b7edcfa3d9.mp4

**Comment by n0samu** [comment]
The fix has not made it to Firefox yet. Can you please click your Chrome extension icon and tell me what nightly version you have?

**Comment by n0samu** [comment]
Oh sorry, it looks like the fix did not quite make it into the latest nightly release. Please try again once nightly build 2023-04-06 is released and active in your browser.

**Comment by absurdismworld** [comment]
> Oh sorry, it looks like the fix did not quite make it into the latest nightly release. Please try again once nightly build 2023-04-06 is released and active in your browser.

Sure thing, I'll test it out again with the new version once it's released. No idea what's going on with Firefox though, I tested it a few times just to make sure and even with nightly build 2023-03-25 it worked first try every time. I guess it might just be an issue with Chrome.

**Comment by n0samu** [comment]
I suspect that Cloudflare is only returning the problematic JavaScript to Chrome/Chromium users. Seems like we're not going to get any answers on that though.

**Comment by n0samu** [comment]
Looks like the new nightly is up on the Chrome Web Store!

**Comment by absurdismworld** [comment]
> Looks like the new nightly is up on the Chrome Web Store!

Done some testing with the newest nightly build and I can confirm that the issue seems to be fixed :)
