### ISSUE TITLE
Internationalization/localization

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#1006]
We have a decent amount of text in our settings dialog and page, which will need to be localized eventually. Someone suggested a platform for this on the discord, but I don't really have any experience with localization/internationalization, except for editing the `messages.json` files manually (and a little on the translator side but not enough to know what platform it was they were using or whether it was any good. I would like to know what everyone's thoughts are on this matter and whether we have anyone willing to help translate into other languages (l know a little Spanish, but I don't know what languages, if any, the other members speak since we always communicate in English).

**Comment by veikk0** [comment]
I suggest [translatewiki.net](https://translatewiki.net/), a translation community for free and open-source projects. I've used it for a while as a volunteer translator and I find the interface simple and easy-to-use. It uses the [Translate](https://www.mediawiki.org/wiki/Extension:Translate) MediaWiki extension, which has a lot of features that make translators' work easier.

The extension is also in use on various Wikimedia wikis, like MediaWiki.org, Meta-Wiki, and Wikimedia Commons, so the tech & UI itself isn't used only by this single website.

[Here's their intro page for developers](https://translatewiki.net/wiki/Translating:New_project). In terms of requirements, they require commit access so that @translatewiki can regularly integrate translation updates into the project. They also prefer that projects have i18n support. They have [a tips page](https://translatewiki.net/wiki/Translating:Localisation_for_developers) for developers and software project managers.

Disclaimer: I only have recent experience with this single translation platform, so take my suggestion just as that, a suggestion.

**Comment by Justin-CB** [comment]
> I think with Crowdin set up (#10766, https://crowdin.com/project/ruffle) this can now be considered solved.

You're right, thanks.
