### ISSUE TITLE
The Keeper of the 4 Elements - Stops after first wave

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10313]
### Describe the bug

https://www.newgrounds.com/portal/view/625408?emulate=flash - Thought it would work but then the second wave never appeared. Thougt I already posted this bug here, seems now.

### Expected behavior

2nd wave to come through.

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by emgfc** [comment]
That's an interesting one.

They use pretty rare and underdocumented `Graphics` method called `drawRoundRectComplex()` which takes 8 parameters to draw a rounded rectangle. There's a stub for it in current avm2 implementation, but it seems like this stub is wrong as it takes only 6 parameters.

There's a child MovieClip initialization right after a call to this method, and because of an exception caused by a wrong stub call this child MC is never initialized. When an enemy wave ends, this MovieClip should be deleted with `removeChild()` method, and so here's an another exception thrown and that's what actually breaks a new wave logic.

**Comment by emgfc** [comment]
https://github.com/ruffle-rs/ruffle/pull/10368 will fix it.
