### ISSUE TITLE
Perfomance bug: read-usage buffer was read back without waiting on a fence. this caused a graphics pipeline stall

### ISSUE THREAD

**Issue by kyunkakata** [ruffle-rs/ruffle#10324]
### Describe the bug

I tried to debug some SWF files with Ruffle self-host in the latest version (nightly-23.3.22). This warning, 'Performance bug: read-usage buffer was read back without waiting on a fence. This caused a graphics pipeline stall,' is shown. But I don't find any clues about what causes this problem.
SWF: 
[strikeforceheroes.swf.zip](https://github.com/ruffle-rs/ruffle/files/11046031/strikeforceheroes.swf.zip)

### Expected behavior

The problem should be resolved to improve performance overall.

### Affected platform

Desktop app

### Operating system

macOS Ventura 13.1

### Browser

Google Chrome 98

**Comment by n0samu** [comment]
@Dinnerbone recently explained on Discord why this error occurs:
> It's when things do bitmapdata.draw() and then something else with the pixels on the cpu, and it's somewhat of a design flaw with webgl as far as I know. I don't think we can fix it
But I'm not sure what wgpu could do here. As far as I understand, the browser isn't going to progress the fence until we submit a frame and literally wait a bit. We need to stall it to get the texture right away for bitmapdata stuff
The stall is intentional, unless I'm misunderstanding. There's no nicer way to do it, we can't async other stuff whilst we wait
