### ISSUE TITLE
PuzzPinball: Next Level never appears

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#10325]
### Describe the bug

[ruffle.rs-1679539603680.log](https://github.com/ruffle-rs/ruffle/files/11046448/ruffle.rs-1679539603680.log)

https://www.newgrounds.com/portal/view/406091?emulate=flash
Game seems to work alright-ish for the first level, however once you beat the first level and try to move onto the next level, you are greeted by this empty void of a level.

![Puzzball Ruffle](https://user-images.githubusercontent.com/78768499/227086782-dd2f0ec1-5b78-4b9c-bb57-6f0696d67625.png)

To get past the first level, I set it up like this.
![Puzzball level 1](https://user-images.githubusercontent.com/78768499/227087058-0d1be64a-1343-4426-b293-ff9a824664bc.png)

### Expected behavior

![Puzzball Flash](https://user-images.githubusercontent.com/78768499/227086797-059c1ddd-6d23-4375-8d20-38a0735ef518.png)

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge 110

**Comment by n0samu** [comment]
There are several "Cannot enumerate" warnings that may be related.

**Comment by kuka-alekseevna** [comment]
@n0samu nope, this isn't a problem.

The problem is somewhere in `Scene.removeAll()` method. It just deletes `this` for some reason, so when `Game` tries to call `this.mcScene.init()`, this.msScene is actually undefined.

Will try to debug it tomorrow. My bet is something bad happens when you try to `delete this[undefined]`

<img width="612" alt="image" src="https://user-images.githubusercontent.com/102722085/227626800-4f2c5dbd-5b83-4de0-b30a-596fe5dbf2c0.png">

**Comment by n0samu** [comment]
Thank you for looking into this! 👍

**Comment by emgfc** [comment]
@kuka-alekseevna was actually me, didn't notice it when I took my fiancee's laptop.

So, the funny stuff happens when `__proto__` prop gets deleted from `this` in `Scene.removeAll()`. I thing that scene object just gets deleted with the first GC after that.

**Comment by emgfc** [comment]
https://github.com/ruffle-rs/ruffle/pull/10356 should fix this.

**Comment by waspennator** [comment]
Can confirm level 2 seems to show up properly now.
