### ISSUE TITLE
Steampunk Tower - Can't drag&drop Towers 

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#10532]
### Describe the bug

https://www.newgrounds.com/portal/view/627971?emulate=flash - Hey I can't place the towers ingame via drag&drop.

### Expected behavior

To drag and drop.

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by n0samu** [comment]
I tried placing the machinegun on the first level (by dragging it) and it worked for me. Can you provide more detail on what's not working?

Note: After placing the tower and starting the level, the game broke due to this error:
`ERROR core/src/avm2/events.rs:419 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0xe5b0780 }) to handler FunctionObject(FunctionObject { ptr: 0x124cceb0 }) : TypeError: Error #1010: A term is undefined and has no properties. (accessing field: clone)`
So the level was not actually playable regardless.

**Comment by desertking** [comment]
It actually woks now to place the towers with the update from yesterday I guess. I played it yesterday and it didn't work, now with the new version it works until your error.

**Comment by Sonikkustar** [comment]
The issue appears to be fixed. The only issue I see is some screen stuttering/screen tearing in the updates screen, but that's probably unrelated.

![image](https://github.com/ruffle-rs/ruffle/assets/22226938/7e0feaaa-7dd3-4e6e-96fe-d10a8790d650)

Site now uses **nightly-2023-12-23**.
