### ISSUE TITLE
ridesims.com Taron Simulator Frame Skipping? 

### ISSUE THREAD

**Issue by JamesAllgood** [ruffle-rs/ruffle#1060]
When playing a simulator on ridesims.com The Taron Simulator doesn't seem to like a variable being counted or it skips a frame? 

**Ways to reproduce this bug:**
https://ridesims.com/ride-simulators/Taron
Open up the Taron Sim, power on, maintenance mode, turn on the blocks, send the train, add another train (it doesn't mater what one), press up, press space to put it into the station and then your notice a change in the frames as if something has happened. (the bar go down and the simulator becomes useless) 

The code that's run when this happens is the following: 

onFrame (1828) {
    _root.ESTOPTrain1=0;
    if (_root.ESTOP==0 && _root.BlockA==0 && _root.HoldBlockF==0 && _root.SystemMode!=0  && _root.UnloadDispatch==1) {
        play();
        _root.BlockA=1;
    } else {
        stop();
        BLOCKCHECK.gotoAndPlay("BlockA");
    }

**Comment by Herschel** [comment]
Full instructions for how to operate the sim and see the bug:
* Click Active Power
 * Hold R until System Resets
 * Click System Mode to set Maintenance Mode
 * Click Blocks and click A B C D E F
 * Press Down on the keyboard. The Load Station "Restraints" light turns yellow. Wait a moment.
 * When the Dispatch light turns green, press Space to launch the train
 * When the train arrives back at the station, press Up to unload the train. The Unload Restraints light turns yellow. Wait a moment.
 * When the Dispatch light turns green, press Space to push the train forward to the Load station. In Flash, you can repeat the whole process to launch the train again, but in Ruffle, the train is soft-locked at this point. If you squint, the safety bars on the trains are stuck in the down position.

After looking into this for a while, I suspect it's a frame-execution-order bug.
One issue is that the train clip does a `gotoAndPlay` rewind upon arriving back at the station, and so the clip gets recreated, at which point the train clip gets recreated, and the safety bar animation state resets. Either some other code needs to reset the safety bar animation to the proper frame, or the clip shouldn't get recreated at all. The movie clip state is quite complicated at this point so it requires some deeper investigation.

(Unrelated to this specific bug, looks like this renders a blank screen for me since the upgrade to wgpu 0.6.)

**Comment by JamesAllgood** [comment]
Now the rendering broken for masked layers is closed and done, and this is still an issue. 

Is it an issue with something else?

**Comment by JamesAllgood** [comment]
Re coded the sim to fix the frame skipping issue
