### ISSUE TITLE
Ruffle crashes the webpage on iPadOS 15.7

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#10620]
### Describe the bug

This issue happens since nightly-2023-01-17, so this should be [one of these commits](https://github.com/ruffle-rs/ruffle/compare/nightly-2023-01-15...nightly-2023-01-17).

This version can be tested here:
https://ruffle-regressions.github.io/?version=0.1.0-nightly.2023.1.17

### Expected behavior

Ruffle was working on iPadOS 15.7, using nightly-2023-01-15:
https://ruffle-regressions.github.io/?version=0.1.0-nightly.2023.1.15

### Affected platform

Self-hosted version

### Operating system

iPadOS 15.7.3

### Browser

Safari

**Comment by n0samu** [comment]
Can you provide some detail on what device you are testing on, how to reproduce the crash, and what happens when the crash occurs? I think this might be a performance issue with your device. On my iPhone with iOS 15.7.3, Ruffle works, but it's easy to crash the demo by loading a more intensive SWF. (The symptom of this crash is a page reload along with the message "this webpage was reloaded because a problem occurred".) The performance regression is probably caused by the switch to wgpu-webgl (but don't tell Dinnerbone that 😆)

**Comment by Toad06** [comment]
You're right, I should have given more details.

> The symptom of this crash is a page reload along with the message "this webpage was reloaded because a problem occurred".

That's quite the issue I'm facing, but it's worse. Here are the different steps of the issue:
- Ruffle loads, then crashes the page a first time.
- Safari reloads the page.
- Ruffle loads, then crashes a second time.
- Safari displays an error: "A problem repeatedly occurred with the page".

Each crash happens a few seconds after the page load, so the SWF causing the crash is... the Ruffle logo. 😅 So I expect any site that uses Ruffle to crash Safari on my device.

> what device you are testing on

My device is an iPad Air 2. Definitely not recent but still. 😄

**Comment by n0samu** [comment]
And thanks to #9904, `preferredRenderer: "webgl"` can also be used to switch off wgpu if necessary.

**Comment by Toad06** [comment]
Fixed by #18431, now fallbacks to the WebGL renderer instead of crashing.
