### ISSUE TITLE
ruffle breaks video playback on espn.com due to invalid plugins array

### ISSUE THREAD

**Issue by paulschreiber** [ruffle-rs/ruffle#10798]
### Describe the bug

Ruffle breaks video playback on espn.com.

ESPN uses Chartbeat, and loads this JS:
https://static.chartbeat.com/js/chartbeat_video.js

```js
    function ra(a) {
        var b = r.navigator
          , c = r.window.screen
          , e = [b.userAgent, b.platform, (new Date).getTimezoneOffset(), c.width + c.height + c.colorDepth];
        t(b.plugins, function(a) {
            e.push(a.name + a.description + a.filename + a[0].type)
        });
        b = r.performance;
        e = e.concat([b && b.now ? b.now() : "", document.title, r.location.href, u(), oa()]);
        return e.concat(a || []).join()
    }
```

Without Ruffle, the output of the `a[0]` is
```
MimeType {type: 'application/pdf', suffixes: 'pdf', description: 'Portable Document Format', enabledPlugin: Plugin}
```

With Ruffle, the output is:
```
MimeType {type: 'application/pdf', suffixes: 'pdf', description: 'Portable Document Format', enabledPlugin: Plugin}
MimeType {type: 'application/futuresplash', description: 'Shockwave Flash', suffixes: 'spl', enabledPlugin: RufflePlugin}
undefined
```

This causes `a[0].type` to  throw a TypeError:
```
TypeError: Cannot read properties of undefined (reading 'type')
```

and the video no longer plays.

### Expected behavior

No TypeError. Video playback unaffected.

### Affected platform

Browser's extension

### Operating system

macOS Ventura 13.3.1

### Browser

Chrome 112.0.5615.137

**Comment by Lord-McSweeney** [comment]
This is a regression caused by #10333, which added a plugin to the plugins list: `RufflePlugin {__mimeTypes: Array(0), __namedMimeTypes: {…}, name: 'Ruffle Extension', description: 'Ruffle Extension', filename: 'ruffle.js'}`

The issue with this plugin is that it doesn't have a `[0]` because it doesn't actually handle anything; it's only there to prevent the self-hosted instance from overriding the extension.
