### ISSUE TITLE
Special characters are sometimes not displayed

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1099]
Seems to only happen when "useoutlines" is equal to 0 in "DefineEditText" tag.

In the sample below, the following text is displayed in Flash: "demo: àâäéèêëìîïòôöùûüÿÀÂÄÉÈÊËÌÎÏÒÔÖÙÛÜŸ".
Ruffle will only show "demo: ".

[special_chars.zip](https://github.com/ruffle-rs/ruffle/files/5168065/special_chars.zip)

**Comment by Herschel** [comment]
This is sort-of expected with our current device font rendering because it uses an embedded version of Noto Sans which only includes the basic characters. It's a good idea to include some more characters, but there will always be some we are missing until we switch to a different way of rendering system fonts.

**Comment by ousia** [comment]
@Herschel, isn’t this issue a duplicate of #1862?
