### ISSUE TITLE
Cat Ninja goes to a black screen after a certain level

### ISSUE THREAD

**Issue by SipSup3314** [ruffle-rs/ruffle#11012]
### Describe the bug

On the epilepsy level, you can complete it normally, but when you go to the next level, it will fade black and not fade out into the next level. Here is the swf:  
[catninja.zip](https://github.com/ruffle-rs/ruffle/files/11454709/catninja.zip)

### Expected behavior

Level fades to black and fades out on next level

### Affected platform

Self-hosted version

### Operating system

ChromeOS 108

### Browser

Google Chrome 108

**Comment by n0samu** [comment]
To clarify, level 23 is the level that's being referred to as "the epilepsy level": https://youtu.be/iNO0sdD5J3A?t=411

So the problem is actually happening on level 24. It's really far into the game, so I used the practice version of the game from https://www.speedrun.com/catninja/resources, which allows you to skip levels. The easiest way to reproduce the bug is to load the practice version in Ruffle, repeatedly press C until it says "Level selected: 24" at the top, then press V to go to the level.

The error is:
```
ERROR run_frame:run_all_phases_avm2: ruffle_core::avm2::events: Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x1eddbe47088 }) to handler FunctionObject(FunctionObject { ptr: 0x1edcc304818 }) : TypeError: Error #1010: A term is undefined and has no properties. (accessing field: walkable)
        at environment::FallingSpike/update()
        at environment::EnvironmentManager/updateVector()
        at environment::EnvironmentManager/update()
        at Main/update()
```

**Comment by SipSup3314** [comment]
This bug has been fixed a while ago
