### ISSUE TITLE
Ruffle extension does not work on Tooli's Classic Games site

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#11050]
### Describe the bug

Example game page: https://www.tooli.co.kr/flash/472106

The Ruffle extension does not load on pages of the Tooli's Classic Games site. It seems like some JavaScript on the page is interfering, but I have not been able to confirm/diagnose this yet.

### Expected behavior

Flash games should load and play like they do on other sites.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Edge 113

**Comment by Toad06** [comment]
I don't think there is a conflict with a JavaScript code. It seems like our polyfill code doesn't run for this embed because Ruffle doesn't detect it as a Flash content:

`<EMBED src="https://file.tooli.co.kr/flash/3dlogic.swf" width=700 height=517 type=application/octet-stream>`

If I remove the `type` attribute or replace its value with `application/x-shockwave-flash`, the file loads as expected (well, not really because there's a CORS related issue, but that's another story).

**Comment by Toad06** [comment]
I think the behavior in this situation is (was) not consistent across browsers.

In #968, I posted a zip file that contained the "embed_wrong_type" test; it was expected for Ruffle to polyfill the "embed" element, despite the `type` attribute having an unexpected value. This test was probably run with Firefox.

This test was later merged in #1132, but the expected output was changed (no polyfill expected). This time, the test was probably run with Chrome.

So I don't think that Chrome (or a fork) with Flash Player enabled would play the file at https://www.tooli.co.kr/flash/472106.

However, it could still be a good idea to change our implementation to be more lenient. What do you think?
