### ISSUE TITLE
First bowser fight in Super Mario 63 is not completeable

### ISSUE THREAD

**Issue by swaggybaguette** [ruffle-rs/ruffle#11077]
### Describe the bug

Mario spawns inside a platform near the pipe that takes you to bower and is stuck there. ![image](https://github.com/ruffle-rs/ruffle/assets/125625453/2250d36d-c744-43a1-8eed-584361c52783)

Steps to reproduce:

-Take the shortcut to the bowser 1 fight on a new save file (shortcut seen here: https://youtu.be/3ZnULk4CA60?t=41 )

### Expected behavior

Mario spawns at the start of the level and is able to complete the level and bowser fight
![image](https://github.com/ruffle-rs/ruffle/assets/125625453/9c366faf-0773-40f7-800e-db72f123a205)

### Affected platform

Online demo

### Operating system

Manjaro Linux, x86_64, Linux 6.1.25-1-MANJARO

### Browser

Librewolf 102.0.1

### Additional information

This only occurs in ruffle versions 2023-05-15 and 2023-05-16, versions prior work fine, I am playing the 2009 version of Super Mario 63

The link to the swf is here https://cdn.discordapp.com/attachments/704769195749146634/1108132691246862406/Super_Mario_632009_Ver..swf

This same thing also happens in another flash implementation called waflash (likely not relevant or helpful but I thought I'd mention it)

**Comment by iwannabethedev** [comment]
This is rather time-consuming to reproduce, due to having to use speedrunner tactics to get there without spending lots of time, and also knowing how to play the game.

@swaggybaguette Could you post both a video of the expected behavior and of the bug? From start to finish? I think that would be very helpful for people seeking to debug and fix this.

**Comment by Toad06** [comment]
I bisected the issue to 4a26ceb14bbcb414daeb06cfc3f15e98349b6565.

I used an edited version of the game that skips the tutorial level ([available here](https://github.com/ruffle-rs/ruffle/files/11035076/mm63.zip)).

**Comment by swaggybaguette** [comment]
> This is rather time-consuming to reproduce, due to having to use speedrunner tactics to get there without spending lots of time, and also learning how to play the game.
> 
> @swaggybaguette Could you post both a video of the expected behavior and of the bug? From start to finish? I think that would be very helpful for people seeking to debug and fix this.


sure https://files.catbox.moe/ixdo1y.mp4

**Comment by iwannabethedev** [comment]
Given @Toad06 's excellent work and idea with both making it much faster to reproduce and also bisecting the issue to https://github.com/ruffle-rs/ruffle/commit/4a26ceb14bbcb414daeb06cfc3f15e98349b6565 , I am tempted to revert those changes bit by bit locally, and then see if I can isolate the specific piece of code that causes the bug.

(I reviewed that PR carefully myself, so I am a bit embarrassed that it has such a regression).

**Comment by Toad06** [comment]
Maybe it could be worth inspecting `fn winding_number_line` first, because a previous change in this function caused a regression (still pending): https://github.com/ruffle-rs/ruffle/issues/8420#issuecomment-1336502015 , so maybe that the changes in 4a26ceb14bbcb414daeb06cfc3f15e98349b6565 made things worse. This is just a suggestion and it's possible that I'm way off. :)
