### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#11316]
### Describe the bug

Both https://www.npmjs.com/package/@ruffle-rs/ruffle and https://unpkg.com/@ruffle-rs/ruffle list current nightly as 2023-05-31, but when added to https://www.video-vectorial.tk/ as:

``` html
<script src="[https://unpkg.com/@ruffle-rs/ruffle](view-source:https://unpkg.com/@ruffle-rs/ruffle)"></script>
```

The contextual menu displays 2023-05-20 as the number to the self-hosted version.

I don’t know whether the information about version number is wrong or https://unpkg.com/@ruffle-rs/ruffle contains an older version.

Many thanks for your help.

### Expected behavior

Current version should display nightly from 2023-05-31.

### Affected platform

Self-hosted version

### Operating system

Fedora Linux 37

### Browser

Firefox 113.0.1

**Comment by adrian17** [comment]
I think this might just be a caching issue. When I opened your URL, it shows 05-31.

**Comment by n0samu** [comment]
You probably have the Ruffle Firefox extension enabled. I think #10333 makes the extension in charge of polyfilling even if it's older. And I guess it's supposed to negotiate with the selfhosted copy of Ruffle and pick the newer one, but that version negotiation has been broken for forever because we aren't using proper semver. The effect is the older Firefox extension is used instead of the selfhosted copy of Ruffle.
