### ISSUE TITLE
Happay Pet Picture Matching - Weird Loop Error

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#11443]
### Describe the bug

Somehow this file is not really readable... Never saw this error before.

Loading SWF file https://www.spiele-umsonst.de/azad/downloads/flashgames/happypetpicturematching.swf

ruffle_web-wasm_extensions.js:716 ERROR  Error decompressing SWF: corrupt deflate stream log.target = "swf::read";log.module_path = "swf::read";log.file = "swf/src/read.rs";log.line = 114;

### Expected behavior

Should Load & run

### Affected platform

Online demo

### Operating system

All

### Browser

All

**Comment by n0samu** [comment]
Wow, this is the scariest and most weirdly obfuscated SWF that I have ever seen 😨 
I have no idea where to even begin with this one 😖

**Comment by Toad06** [comment]
Yeah, there's a lot of strange things to say the least.

Clicking one of these items in JPEXS causes the program to hang:
![a1](https://github.com/ruffle-rs/ruffle/assets/14274782/e17c86af-d3a2-43fe-b3b1-a2b743296248)

Some other stuff that makes no sense:
![a4](https://github.com/ruffle-rs/ruffle/assets/14274782/938bb784-33fe-4b98-810d-f03eeb69cabd)
![a2](https://github.com/ruffle-rs/ruffle/assets/14274782/c63f465e-613b-4252-9361-c97b45507e19)

There's at least something I agree with:
![a3](https://github.com/ruffle-rs/ruffle/assets/14274782/df8e19bb-fb65-4d4d-815d-defd883c7276)

**Comment by desertking** [comment]
Yet somehow this runs in Adobe Flash Player...

**Comment by Lord-McSweeney** [comment]
A list of issues I've noticed that actually make sense:
- Empty `DoAction` tags (despite this being an AS3)
- `Define*` tags inside `DefineSprite` (`DefineSprite` is not allowed to hold those tags, this issue is similar to #10621)
- Several randomly scattered broken and empty `DoInitAction` tags
- Non-UTF8 ABC data (specifically, non-utf8 characters scattered throughout class and variable names) causing a VerifyError- I believe this is the biggest issue here (similar to #10148 and #9953).

**Comment by Aaron1011** [comment]
This will be fixed by https://github.com/ruffle-rs/ruffle/pull/14908

**Comment by Lord-McSweeney** [comment]
Fixed by #14908
