### ISSUE TITLE
Bubble Blob - Game level not starting

### ISSUE THREAD

**Issue by freeworldgroup** [ruffle-rs/ruffle#11786]
### Describe the bug

Game loads normally, but when you go to start playing and selecting a game mode it returns to menu instead of getting into the game. 

http://www.freeworldgroup.com/games8/gameindex/bubbleblob.htm

### Expected behavior

Game level should begin.

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Chrome

**Comment by Lord-McSweeney** [comment]
This is the error which causes the issue (and it also starts a spam of errors):
```
Error occured when running AVM2 frame script: TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: promptButton)
	at game_fla::MainTimeline/setPowerUpNum()
	at game_fla::MainTimeline/frame4()
	at flash.display::MovieClip/flash::display::MovieClip::nextFrame()
	at game_fla::MainTimeline/classicModeButtonClick()
```

**Comment by Aaron1011** [comment]
This is a tricky nested goto issue. The call to `nextFrame()` triggers the framescript function `frame4()`, which calls `prevFrame()`. This results in the `frontPad` child of `MainTimeline` getting removed, since it only exists in frame 4. Ruffle then sets `frontPad` to `null`, resulting in the above error when the SWF tries to do `frontPad.promptButton`.

I think that the `prevFrame()` call ends up doing nothing when run on the *same* MovieClip that's in the middle of a goto.

**Comment by freeworldgroup** [comment]
game works well now
