### ISSUE TITLE
Some errors (neave_tv.swf 2006, FLV works one time only)

### ISSUE THREAD

**Issue by TemaisgameNoobas** [ruffle-rs/ruffle#11821]
### Describe the bug

Launched Neave.TV with new FLV support, at first it displays correctly, but when i try to switch the video this happens:
![image](https://github.com/ruffle-rs/ruffle/assets/60001674/494860c7-356c-4bd5-8b25-0c4e6f3c5cb1)
![image](https://github.com/ruffle-rs/ruffle/assets/60001674/7007c75b-e750-45a5-8ae6-0a724c32688e)
SWF:
[issue.zip](https://github.com/ruffle-rs/ruffle/files/11947306/issue.zip)

### Expected behavior

Playing videos fine

### Affected platform

Self-hosted version

### Operating system

Ubuntu 22.04

### Browser

UnGoogled Chromium Version 100.0.4896.127

### Additional information

Ruffle was unmodified, and it plays first video fine.

**Comment by n0samu** [comment]
Note for people looking at this issue: `adhis.mp4` and `format.flv` are the FLV videos that it loads. Yes, adhis.mp4 is actually an FLV video. The problem is that selecting the second video ("FLV Sample") doesn't show the video (which is just text on a green background)
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/fd9cb7f9-807b-46c2-9cab-9fcc2339126f)

**Comment by TemaisgameNoobas** [comment]
> This issue has progress. Now, a sign appears that reads "Sorry, it seems like _video_ is on slow conection at the moment". It switches the video every 10 seconds. ![image](https://user-images.githubusercontent.com/60001674/262835387-7e86ba0b-fda7-4328-b76e-5f0963fc36ec.png)

Im going to open a seperate issue for this.
