### ISSUE TITLE
Playing Bored Witch´s Castle

### ISSUE THREAD

**Issue by LeoKids** [ruffle-rs/ruffle#1195]
This may be Fixed but im not Sure

For Some PCS The Bored Witch´s Castle Works well but Stuck At Loading

That game was Made in 2001 (Maybe AS1/AS2?) And It was about one of the triplets Had to collect all the Objects 

But in a ruffle, It works Well for me Though When I Collect the Object or the Points (Yellow Circles that when you go towards it it disappears and recovers your health) It doesn't Collect it, Wouldn´t Show the Object Collected Switching to 1 or Much.

So, Can you fix it?

**Comment by Herschel** [comment]
Could you post a link to the game or attach the SWF? Thank you!

**Comment by LeoKids** [comment]
The Triplets Website is offline but at least I can Send you an Archive of it,

[http://web.archive.org/web/20081229023534/http://www.thetriplets.com/](url)
Its located in there in Playground Section and Games Section.

But if you want a direct LINK To the game
[http://web.archive.org/web/20081106134642/http://www.thetriplets.com/play/castellbruixa/castellbruixa.html](url)

**Comment by kmeisthax** [comment]
This game appears to be attempting to grab `txts.txt` from the same server, so I get some network errors and missing character IDs at least on desktop. Wayback Machine has no archive of that file since they don't archive SWF resources at all. I'm not sure if that has anything to do with it, however.

The hit detection in this game is shape-based, that may be the cause of the problem with collision detection. The rest of the code has a number of things that I would register as oddities if I wasn't aware of how ridiculously forgiving AS2 was with capitalization and types.

I think I have an idea why it's not loading on some PCs, too:

```
preload = Math.floor(_root.getBytesLoaded() / _root.getBytesTotal() * 100) + " %";
if(preload == "100 %")
{
   gotoAndStop(4);
}
else
{
   gotoAndPlay(2);
}```

For those unaware, floating point numbers have a fixed amount of precision. The more operations you do on them, the more rounding might happen to them, which changes the result. Furthermore, they're binary, not decimal numbers, so "whole" fractions in decimal like 0.2 are actually repeating in decimal and will get rounded. All that means is that it's entirely possible, depending on the machine and how Ruffle was compiled, for this to produce a value like "100.000000023 %" instead of "100 %", which means the preloader would never pass.

**Comment by Herschel** [comment]
The specific issues with the item collision is because the items array is initialized with `new Array(1,2,3,4,5)`, which was not working correctly. (#119)

There are some reading the text in some of the text fields (SWF5 text encoding is locale-dependent, so this should be ANSI -- text language is Catalan(?))
