### ISSUE TITLE
Epic Battle Fantasy 3: Invisible Text

### ISSUE THREAD

**Issue by waspennator** [ruffle-rs/ruffle#11967]
### Describe the bug

[548041_Epic_Battle_Fantasy_3_secu.zip](https://github.com/ruffle-rs/ruffle/files/11995808/548041_Epic_Battle_Fantasy_3_secu.zip)
(Maximize Flash Player and Ruffle in order to see it)
When you press play, normally there should be a warning on the side telling you not to resize the game as it can lead to visual issues, but for some reason, this isn't showing up on ruffle, which is weird cause ruffle debug does seem to detect it as existing and visible.

![Screenshot 2023-07-09 120255](https://github.com/ruffle-rs/ruffle/assets/78768499/01e01930-420f-48b2-aa45-e78c377aaa17)

### Expected behavior

![Screenshot 2023-07-09 120120](https://github.com/ruffle-rs/ruffle/assets/78768499/0659d274-5fe5-4e73-b1a2-62e232e8d7c9)
There should be a warning about resizing the game on the far left of the screen when maximized once you press play.

### Affected platform

Desktop app

### Operating system

Windows 11

**Comment by n0samu** [comment]
This is not a bug - it happens because the text is placed outside the stage area, and by default Ruffle letterboxes the off-stage areas. If you run the desktop app with ` --letterbox=off` you'll see the text. This made me notice that the letterbox setting was somehow omitted from the "Open Advanced" menu though, I guess I'll fix that!

**Comment by waspennator** [comment]
Closing since pr to turn off letterboxing is merged now and only happens when it's on.
