### ISSUE TITLE
Avoid anti-decompile avm

### ISSUE THREAD

**Issue by Zaseth** [ruffle-rs/ruffle#1236]
Hi there!

I'm not sure if this is ever thought of, but I came across [this ](http://www.xgenstudios.com/stickarenaclassic/ballistick2.swf
)SWF using something very interesting. When opening the file in JPEXS and viewing any script object, the following is shown:

![image](https://user-images.githubusercontent.com/24899039/94427702-c90dad80-018f-11eb-8f90-113fbee11ff1.png)

The so called 'ConstantPool' here is being used to mess up decompilers. I'm not sure how Ruffle currently handles this, but in my opinion they should be ignored and even removed.

**Comment by kmeisthax** [comment]
So, repeated/obfuscated constant pools should work fine in Ruffle - we already have to support them for completely unobfuscated init code, which assumes it can reference it's constant pool anywhere.

I actually ran the game on desktop and it did initialize to the point where it tripped protection and kicked me over to XGen Studios. I'm not able to quickly see what the protection is checking for or patch it out to see if the game runs - I guess the obfuscator did it's job at least.

Interestingly, the game panics after this point, rather than giving me the piracy shame screen that it was supposed to. The panic happens *within* the crate we use to launch a web browser, so I suspect it has something to do with the fact that it takes the game a good minute to initialize. I'm still not sure what `buffering RedrawRequested event` is or why it's delivered as a panic.

I'll need to triage this further before I can say whether or not this actually works, as there's probably *an* issue (or twenty, it *is* using MX) in here.

**Comment by Zaseth** [comment]
Thank you for taking a look at it! One more thing, there's also an Unknown tag (255) in the swf used to trip decompilers, but I'm guessing this is already a known tactic.

**Comment by Zaseth** [comment]
A note: There's another version of this game; Stick Arena Dimensions.

**Comment by Herschel** [comment]
Thanks for the report! This is a case of #458 (unknown tag types contain obfuscated AS bytecode). Handling this is the last big "gotcha" for good AS2 support. I'm going to be doing some long-overdue cleanup some of `swf` in the near future so that we can properly handle these.
