### ISSUE TITLE
Descendants with attribute QName don't seem to work (xml..@[q])

### ISSUE THREAD

**Issue by evilpie** [ruffle-rs/ruffle#12570]
The following should produce `value1value2`:

```
var xml =
<alpha>
    <bravo attr1="value1" attr2="wrong">
        <charlie attr1="value2" attr2="wrong"/>
    </bravo>
</alpha>;

var q = new QName("attr1");
trace("xml..@[q]: " + xml..@[q]);
```

We are currently treating this as `xml..[q]`, i.e. matching this as elements instead of attributes.

JPEXS also decompiles `xml..@[q]` as `xml..[q]`, so I am not quite sure where difference in bytecode actually would be.

**Comment by sleepycatcoding** [comment]
Seems JPEXS might be decompiling this wrong, since for the `getdescendants` opcode a MultinameLA is passed. Also because it is a lazy multiname and name is resolved at runtime and the passed name is a QName, we seem to discard the Attribute flag here: https://github.com/ruffle-rs/ruffle/blob/19ad492eaaca522f082a0d0961acbeb01d0484d3/core/src/avm2/multiname.rs#L252
