### ISSUE TITLE
Zombotron — TypeError

### ISSUE THREAD

**Issue by elsandosgrande** [ruffle-rs/ruffle#1289]
As of the tenth of October, when attempting to play the original Zombotron with Ruffle desktop, whether with a local build which was built from the latest committed code or with the latest nightly build, [the following occurs (warning, flashing imagery)](http://mellemws.my.to/direct/Screencast_from_2020年10月10日_17時26分41秒.webm), as opposed to [the expected result](https://kernel.ubuntu.com/~kernel-ppa/mainline/). My laptop is running Ubuntu Focal with [the oibaf graphics PPA](https://launchpad.net/~oibaf/+archive/ubuntu/graphics-drivers) and [the latest mainline kernel](https://kernel.ubuntu.com/~kernel-ppa/mainline/).

The terminal log continuously produce just one line: 

```
***
[2020-10-10T15:26:58Z ERROR ruffle_core::display_object::movie_clip] Got TypeError: undefined is not an Object when constructing AVM2 side of display object
[2020-10-10T15:26:58Z ERROR ruffle_core::display_object::movie_clip] Got TypeError: undefined is not an Object when constructing AVM2 side of display object
[2020-10-10T15:26:58Z ERROR ruffle_core::display_object::movie_clip] Got TypeError: undefined is not an Object when constructing AVM2 side of display object
***
```

The SFW in question: http://mellemws.my.to/direct/zombotron.swf

---

If this ticket breaches the following terms of the contributing guidelines, I appologise in advance and shall note this to avoid future incidents:

* A "this SWF doesn't work at all" report (what about it doesn't work?)
* Duplicate issues for each piece of content using an unimplemented feature

**Comment by kmeisthax** [comment]
I retested this game and it still flashes, but the logged error is now that it's taking too long to execute. If I comment out the execution limit on desktop (entirely not an option, AVM2 needs optimization), then I instead get a bunch of errors about not being able to access `flash.display.SimpleButton` and `flash.media.Sound`. So this is now waiting on AS3 button and sound access.

**Comment by Lord-McSweeney** [comment]
This game works better now, but has the following issues:
At the beginning, the button fills backwards (not sure if this is intentional behavior)
The SWF can't be resized (see #8921)
`ERROR core/src/avm2/events.rs:422 Error dispatching event EventObject(EventObject { type: "addedToStage", class: flash.events::Event, ptr: 0xeb40a20 }) to handler FunctionObject(FunctionObject { ptr: 0xeb8eed8 }) : RustError("Cannot access property ::addEventListener of null or undefined")`

**Comment by Lord-McSweeney** [comment]
I somehow managed to get `Focus is now on None` in this SWF, which should be impossible in AVM2.

**Comment by MartySVK** [comment]
I can start level 1, but it is impossible to move

**Comment by n0samu** [comment]
After a lot of trial and error, I found that the WASD keyboard controls become unresponsive if you click directly on certain text fields in the game before gameplay begins. Clicking any of this text triggers the problem:
![image](https://user-images.githubusercontent.com/71368227/229286584-3618e2b7-2f6f-4a2b-80b2-5e4597863257.png)
As does the "low battery" text on the loading screen:
![image](https://user-images.githubusercontent.com/71368227/229286610-8488948e-56cd-4254-8e9c-2a090d84747e.png)
A message like this always appears when the issue is triggered:
`2023-03-31T21:32:35.770780Z  INFO ruffle_core::focus_tracker: Focus is now on Some(EditText(EditText { ptr: 0x1f1ed553520 }))`
It seems like text fields are stealing focus, preventing keyboard input from being processed correctly.

@SN902 pointed out that the same issue occurs in [Labyrinth: Secrets of ShadowHaven](https://www.kongregate.com/games/bomtoons/labyrinth-secrets-of-shadowhaven) if you click on the "Press S to start" text before starting the level:
![image](https://user-images.githubusercontent.com/71368227/229286803-8a76a35e-3bb2-42a5-9450-e86d030e0b17.png)

**Comment by Aaron1011** [comment]
The avm2 mouse pick code allows targeting a non-editable EditText. I think we need to edit the focus tracker to ignore a non-editable EditText if it gets targeted.
