### ISSUE TITLE
Regression: Windows XP Tour Button issue

### ISSUE THREAD

**Issue by p0008874** [ruffle-rs/ruffle#12938]
### Describe the bug

https://github.com/ruffle-rs/ruffle/assets/75534590/ca1b3d5a-6b9d-4337-9c1a-a6ba6bcc3c6a

### Expected behavior

It should be normal.

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by n0samu** [comment]
The files can be downloaded from #10859 here: https://github.com/ruffle-rs/ruffle/files/11349563/mmTour.zip
Extract the zip and run tour.swf.

As far as I can tell, this seems to be some kind of timing/loading issue or race condition that only occurs on desktop. But I guess this was exposed by #10792; I've bisected this regression to commit c74a43e6435bc4139293211ef6fdf18f932cc8e8. Though due to the nature of the bug, I can't be 100% confident about any bisect.
