### ISSUE TITLE
Ruffle does not append ? paremeters to urls properly

### ISSUE THREAD

**Issue by Fancy2209** [ruffle-rs/ruffle#13898]
### Describe the bug

I tested [Kingdom Rush](https://armorgames.com/play/12141/kingdom-rush?flash) through the extension dinnerbone sent on the discord, who included fixes to make AGIv1 work
When I click the buy Premium buton, it sends me to 
https://armorgames.com/purchase/

### Expected behavior

The button to Buy Premium would send me to 
https://armorgames.com/purchase/?sku=KingdomRush%2DPremium&username=Fancy2209

### Content Location

https://cache.armorgames.com/files/games/kingdom-rush-12141.swf?v=1379178890

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Mozilla Firefox Developer Edition 120.0b7

**Comment by n0samu** [comment]
Can you check if this also happens in the desktop app? If not, I think this has the same root cause as this problem I mentioned in https://github.com/ruffle-rs/ruffle/issues/2092#issuecomment-1256827662:
> web builds of Ruffle are ignoring query strings passed to getURL

IIRC, the problem is that Ruffle's web backend is erroneously treating GET parameters as form values, so the parameters never end up being added to the request.

**Comment by Fancy2209** [comment]
> Can you check if this also happens in the desktop app? If not, I think this has the same root cause as this problem I mentioned in [#2092 (comment)](https://github.com/ruffle-rs/ruffle/issues/2092#issuecomment-1256827662):
> 
> > web builds of Ruffle are ignoring query strings passed to getURL
> 
> IIRC, the problem is that Ruffle's web backend is erroneously treating GET parameters as form values, so the parameters never end up being added to the request.

It does not work on desktop
[Test.zip](https://github.com/ruffle-rs/ruffle/files/13286204/Test.zip)

**Comment by n0samu** [comment]
@Fancy2209 Your test doesn't work in Flash Player either. It wouldn't make sense if it did work, because you set the request method to POST in your URLRequest. So of course it is not going to use GET parameters.

**Comment by Fancy2209** [comment]
> @Fancy2209 Your test doesn't work in Flash Player either. It wouldn't make sense if it did work, because you set the request method to POST in your URLRequest. So of course it is not going to use GET parameters.

It did work when I tried...

**Comment by n0samu** [comment]
Further discussion has clarified that Flash Player's navigateToURL uses a POST request where it can (in the browser) but falls back to a GET request in the standalone player. (Of course, this applies to URLRequests like this one where the method is set to POST)

**Comment by Dinnerbone** [comment]
This is a fairly easy problem to solve, so I'm promoting this to good-first-issue. If someone would like to get started with Ruffle development, this is a good one to try out!

The issue is that our `navigateToUrl` implementation in avm2 is incomplete. This call specifically: https://github.com/ruffle-rs/ruffle/blob/3fd53b8ca135c2f54eaa5a5b1bc87653867ccd57/core/src/avm2/globals/flash/net.rs#L35-L39

That `None` should be `Some` sometimes, depending on the `data` property.

There's existing code that reads that property and translates it correctly - it either needs to be copy pasted, or ideally made into a reusable method: https://github.com/ruffle-rs/ruffle/blob/62e9eb9d6f7b8046356346af2149ce23fadba9ae/core/src/avm2/globals/flash/display/loader.rs#L162-L196

If anyone needs help please [join us in discord](https://discord.gg/ruffle) - and don't forget to read [contributing.md](https://github.com/ruffle-rs/ruffle/blob/62e9eb9d6f7b8046356346af2149ce23fadba9ae/CONTRIBUTING.md)!

**Comment by svitkin** [comment]
@Dinnerbone Trying to tackle this as a newbie to Ruffle and a relative newbie to Rust. Noticing that the part of the `vars_method` argument that would be the query parameters (I think) is typed as `IndexMap`. Because of that, does that mean the code in `loader.rs` to handle the `method` and `body` wouldn't work? It seems to directly modify the url or converts the `data` to bytes in the case of a `POST` request.

**Comment by andwhyisit** [comment]
This is still an issue.

An .swf file contains the following line:
navigateToURL(new URLRequest("download.php?wp=" + myWpTitle + "-" + _loc2_ + ".jpg"));

The button directs to "download.php?". Everything after the question mark is stripped out.

**Comment by Fancy2209** [comment]
> This is still an issue.
> 
> An .swf file contains the following line: navigateToURL(new URLRequest("download.php?wp=" + myWpTitle + "-" + _loc2_ + ".jpg"));
> 
> The button directs to "download.php?". Everything after the question mark is stripped out.

Open a new issue and link the game there please!
