### ISSUE TITLE
Nanaca Crash: Misaligned 'record' numbers

### ISSUE THREAD

**Issue by BlueMaxima** [ruffle-rs/ruffle#1440]
![image](https://user-images.githubusercontent.com/35991016/97770645-39419180-1b89-11eb-96ef-ea1ab9300de3.png)

**Comment by Toad06** [comment]
Seems this is caused by the `TextField.autoSize` property which is not completely implemented yet (cc #280). 

For instance, removing this piece of code:
`score_txt.autoSize = "right";`
produces a way better rendering:
![rrrr](https://user-images.githubusercontent.com/14274782/100118046-bce35b00-2e75-11eb-90af-38b752f00577.png)

**Comment by n0samu** [comment]
The only remaining problem seems to be the slightly misaligned "best record" number:
![image](https://user-images.githubusercontent.com/71368227/229242713-3c4c0b8f-3121-4da7-a157-f1e240e0846e.png)
I don't know why that in particular is wrong, since the other text field is basically the same yet looks fine in Ruffle.

**Comment by n0samu** [comment]
I've opened #10660 with a minimal reproduction of the issue. I'm lost trying to follow Ruffle's complicated text layout code, but hopefully someone can take it from here!
