### ISSUE TITLE
Error in Epic coaster (https://www.kongregate.com/games/knigg/epic-coaster)

### ISSUE THREAD

**Issue by Afganitia** [ruffle-rs/ruffle#14453]
### Describe the bug

When you die, instead of dying, the train continues offscreen, without end. 

### Expected behavior

Should return to start. 

### Content Location

In kongregate: https://www.kongregate.com/games/knigg/epic-coaster

### Affected platform

Desktop app

### Operating system

W10

### Browser

Firefox 120.0.1

**Comment by n0samu** [comment]
Hi, this happens because Kongregate has misconfigured their website, resulting in the game requesting the Kongregate API SWF from the incorrect URL. Same root cause as #9573. There are two ways to fix this:
- Install a userscript manager such as Tampermonkey, then install the [Kongregate Flash games fixer userscript](https://greasyfork.org/en/scripts/438325-kongregate-flash-games-fixer).
- Play the game on a different website such as Armor Games: https://armorgames.com/play/6450/epic-coaster?ruffle
