### ISSUE TITLE
error at https://sites.google.com/view/super-math-game/platform-racing-2?authuser=0

### ISSUE THREAD

**Issue by SpaceWallaby936** [ruffle-rs/ruffle#14577]
### Describe the bug

on platform racing 2 fails to load past the first screen

![image_2024-01-01_135940070](https://github.com/ruffle-rs/ruffle/assets/142070939/24ef8747-3165-4a5f-bdfe-b223d6c50102)

### Expected behavior

![image_2024-01-01_135908052](https://github.com/ruffle-rs/ruffle/assets/142070939/042ab481-b63f-420f-952c-7150df6595d4)

### Content Location

https://sites.google.com/view/super-math-game/platform-racing-2?authuser=0

### Affected platform

Self-hosted version

### Operating system

Windows 10

**Comment by evilpie** [comment]
So there is number of issues with this game in general and in the way this is hosted.

- Apparently the Flash code only supports http: and not https: (which is used by the page)
- It's still trying access `https://pr2hub.com/download.txt?<random>` to download the actual SWF, but that domain doesn't have CORS, so this will never work. (Unless the host is changed)

Just going to https://pr2hub.com/ directly would help here.

Or running the SWF locally, but it still has some other issues:
- There is a regression from #14166. Because the loader SWF is using an older version, for some reason the loaded SWF can't access the `JSON` class.
- This needs a stub for `DateTimeFormatter`

**Comment by bls1999** [comment]
Hey! Current PR2 maintainer here. We did some weird stuff with CORS after the flash EOL, so any browser version of PR2 not hosted on pr2hub.com probably won't work.

Instead, try this: https://pr2hub.com/download

**Comment by n0samu** [comment]
See also: #12935

@bls1999 I've put together a browser package with Flash support: https://archive.org/details/basilisk-portable-with-flash
The game works in this browser. But I guess you must have some strange server-side rules because the game does not work in the standalone [Adobe Flash projector](https://web.archive.org/web/20220401020702/https://www.adobe.com/support/flashplayer/debug_downloads.html). I would appreciate it if you allow the game to work standalone in the Flash projector (please disable any user-agent-based rules on the server side). This would allow us to work on getting the game running in Ruffle, allowing you to run the game on your website in modern browsers!

**Comment by n0samu** [comment]
Nevermind that, I've got the game running in Ruffle 🎉 
![image](https://github.com/ruffle-rs/ruffle/assets/71368227/af801da6-c98a-4fb5-8b85-ae6933a58523)
