### ISSUE TITLE
minus sign does not appear

### ISSUE THREAD

**Issue by chadock62** [ruffle-rs/ruffle#14761]
### Describe the bug

hi!
in a serie of questions for pupils, minus sign does never appear . Plus, divide or multiply are ok...
Here is a picture of it, and the swf zipped !
Thanks a lot
Franck
![2024-01-15 11 49 10](https://github.com/ruffle-rs/ruffle/assets/125816492/1b071a92-dc63-4442-8536-492724d74ce7)

### Expected behavior

Show the sign minus, so that kids could choose right answer!

### Content Location

[exo307.zip](https://github.com/ruffle-rs/ruffle/files/13938003/exo307.zip)

### Affected platform

Browser's extension

### Operating system

Windows 11 

### Browser

Brave

**Comment by n0samu** [comment]
Hi @chadock62, this happens because your SWF's text fields are set to use device fonts, but Ruffle on the web cannot use device fonts, so it falls back to its own "fake device font" which does not include the minus sign character `−`. And your SWF's embedded Tahoma font does not include this character either. The easiest way to fix this problem would be to instead use the almost identical-looking en dash character `–`, which are included in Ruffle's fake device font and the SWF's embedded Tahoma font. Or you could add the minus sign character `−` to the SWF's embedded Tahoma font and set the text fields to use the embedded font instead of device fonts. Or if you are unable to republish the SWF, a third option would be to [follow the instructions in our FAQ](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#how-do-i-change-the-fonts-used-by-flash-on-my-website) to create a separate SWF containing a complete copy of the Tahoma font, then configure Ruffle to load that as a device font.

**Comment by n0samu** [comment]
I've edited the SWF for you according to the second method I described (adding the character to the SWF's Tahoma font and setting the text fields to use it). Hope this helps! [exo307.zip](https://github.com/ruffle-rs/ruffle/files/13961059/exo307.zip)

**Comment by chadock62** [comment]
Thank you very much for all this help!

But we have 100 files like this one and i can't edit them:
Isn't it possible to create a Windows app/service that would communicate
with ruffle web extension the missing system fonts??
Or integrate those maths basic symbols to the web extension ??

Anyway thank you for this great job.

Sincerely,
Franck

**Comment by n0samu** [comment]
Yes, you should follow the instructions in the FAQ to create an SWF containing the required font and configure Ruffle to load it.
