### ISSUE TITLE
Flash from a different URL than Host

### ISSUE THREAD

**Issue by zohebnsr** [ruffle-rs/ruffle#1500]
Is there a way to make a Flash run from a different URL (e.g. CDN).

Explanation: 
suppose My site is a.com where I uploaded Ruffle files.
However, flash files are on b.com which is a CDN. 
When flash and ruffle both are on the Host, file works. When page loads via CDN (after cache it changes flash URL), then flash won't load.
Is there a work around for this? I tried upload Ruffle on CDN, but that doesn't work.

**Comment by kmeisthax** [comment]
You need to configure your CDN to allow cross-domain requests from your main website. Once you do that Ruffle should work normally. I need to know what CDN provider you use before I can tell you how to configure it for CORS.

Ruffle runs in the web sandbox, which means all cross-domain accesses have to be CORS-authorized. Flash doesn't have this requirement because it was an unsandboxed (or less-sandboxed) browser plugin with it's own HTTP stack. So it treated SWFs like an image format where you're allowed to have cross-domain content, at least for the root movie. We obviously cannot emulate that - at least, not in the self-hosted version.

**Comment by zohebnsr** [comment]
Did you mean to add swf in CORS header? I just tried that and game loaded. However, now swf files loads from host URL and not from the CDN. Is this how it works (Don't know about CORS)? I am using BunnyCDN by the way,

**Comment by zohebnsr** [comment]
Never mind. Please ignore last reply. I added SWF to wrong pull zone. My bad! 
I added swf to CORS header and now it works as I wanted to. If that's what you were talking about, you can close this Thread(Issue). Thanks for the help. I really appreciate it.

**Comment by kmeisthax** [comment]
Yup! That's basically it.
