### ISSUE TITLE
Crashed when playing a game on archive.org

### ISSUE THREAD

**Issue by lflee** [ruffle-rs/ruffle#1607]
Game: https://archive.org/details/helicoptergame_flash
Platform: built in browser in Twitter in Twitter app for iOS.
Twitter version: 8.44.1
iOS version: 14.2

**Comment by Toad06** [comment]
Thanks for reporting an issue.

I think it's related to #1580 (fixed by #1602 in master): if you've clicked/touched one of the numbers near "Distance:" or "Best:", Ruffle will crash as soon as the helicopter hits a wall; otherwise everything should work as expected.

Please let us know if you've actually experienced a different crash.

**Comment by Herschel** [comment]
Should be fixed now, thanks for the report!
