### ISSUE TITLE
Context menu uses default browser font, should be changed to Exo 2 for consistency

### ISSUE THREAD

**Issue by WumboSpasm** [ruffle-rs/ruffle#1670]
For most people it's going to be Times New Roman, which isn't stylish. I know this isn't intentional from the WIP images in the Discord.

Tested on Firefox Developer Edition with the Ruffle extension.

**Comment by Toad06** [comment]
Good idea, especially since it's also possible to do horrible things as in the snapshot below. 😛 Maybe we'd need to add an `all: initial;` CSS in the container?

![worth](https://user-images.githubusercontent.com/14274782/100150705-532c7680-2ea0-11eb-902f-4b56e123de01.png)
[testFont.zip](https://github.com/ruffle-rs/ruffle/files/5592722/testFont.zip)

**Comment by WumboSpasm** [comment]
Ruffle now uses Arial for the context menu and panic screens as of #1711. Exo 2 and Lato (the font used on the demo page) were attempted, but due to extension limitations the only way they can be used is by encoding them in base64 and inserting them into the CSS (not very practical). Unless another method of loading non-default fonts is discovered, Arial will have to do for now.
