### ISSUE TITLE
Level wont start in CEC 3 TW

### ISSUE THREAD

**Issue by TherNoNick** [ruffle-rs/ruffle#16724]
### Describe what you were doing

Car eats car 3: twisted dreams-my favorite game in CEC series. After I found out about riffle, I immediately went to play it, but when I started the level, it just didn't start

### What does the crash message say?

The crash message is didnt say anything. The game just have infinite loading

### Ruffle Version

final version

### Affected platform

Browser's extension

### Operating system

Windows

**Comment by kjarosh** [comment]
This issue is identical to https://github.com/ruffle-rs/ruffle/issues/16723, the only difference being the affected platform. However, it seems that this issue is not directly related to the platform, so I'm gonna close this issue as a duplicate.

Duplicate of https://github.com/ruffle-rs/ruffle/issues/16723.
