### ISSUE TITLE
Ageless War: Tooltip does not disappear after clicking upgrade button

### ISSUE THREAD

**Issue by n0samu** [ruffle-rs/ruffle#16789]
### Describe the bug

In [Ageless War](https://www.newgrounds.com/portal/view/567757/format/flash?emulate=flash), hovering over an upgrade button brings up a tooltip with info about the upgrade. As expected, moving the cursor away makes the tooltip disappear. But in Ruffle, clicking the button does not make the tooltip disappear, so it sticks around indefinitely. Here is a video demonstrating this incorrect behavior:

https://github.com/ruffle-rs/ruffle/assets/71368227/0cb267f7-c4fa-4d7d-8c89-95445b722d9c

### Expected behavior

In Ruffle versions 2024-04-21 and older, the tooltips behave correctly:

https://github.com/ruffle-rs/ruffle/assets/71368227/7262eae2-419a-446b-9ea3-740b532b07ed

### Content Location

Page URL: https://www.newgrounds.com/portal/view/567757/format/flash?emulate=flash
SWF URL: https://uploads.ungrounded.net/567000/567757_time_wars_game___FOG.swf

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

This was regressed by #15955. Bisected to commit b9e9a3e1f2f58a2ced3f6f9a19ec26f158c0056f.

**Comment by kjarosh** [comment]
I've decided to bypass AVM2 when firing roll over events on focus change. This issue is not easy to debug and I'm working on AVM2 support for those events anyways, so I assume that the AVM2 version is currently implemented incorrectly (which makes sense as AVM2 differentiates between keyboard and mouse focus, so perhaps it also does for keyboard and mouse hover).

**Comment by n0samu** [comment]
Seems fixed, closing for now
