### ISSUE TITLE
https://web.archive.org/web/20120207181052/www.nissan.co.jp/

### ISSUE THREAD

**Issue by Deanomac** [ruffle-rs/ruffle#16908]
### Describe the bug

Im not sure, I use this a alot and this is my first time reporting a bug.

### Expected behavior

Sometimes it works sometimes it doesnt.

### Content Location

basically any car website between 2005-2013 that used flash.

### Affected platform

Browser's extension

### Operating system

11

### Browser

chrome

**Comment by n0samu** [comment]
This is a problem with Wayback Machine, you can avoid it by accessing the page from this URL instead: 
https://web.archive.org/web/20120207181052/http://www.nissan.co.jp/
The content still appears blank because the URL of the XML file has a randomized parameter. Wayback does have the XML file saved but because of the parameter, it does not load. We can't do anything about this either.
