### ISSUE TITLE
web: Performance regression in Cubefield

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#1703]
This issue only affects the web backend.
Nightly builds <= 2020-11-03 were unaffected.

- Navigate to https://www.newgrounds.com/portal/view/288800 in Chrome or Firefox with the extension.
- Click "New Game". Notice the game suddenly becomes very laggy.
- Wait a little bit, the game will run at its normal speed when you leave the corridor.
- The game will however become laggy again if you manage to reach the next corridor.

I've run a bisect and it appears the issue is (surprisingly) caused by commit 0c38dafd0d5e3495d75f011c7faa122ed0e69f31.

**Comment by parkerlreed** [comment]
Same on desktop. Performance tanks in the corridors/areas with higher cube density on screen.

(Only on ARM where it has 4 cores and a low lower CPU perf. Stays consistent on big desktop)

**Comment by parkerlreed** [comment]
https://www.youtube.com/watch?v=stHoqqXOGt8

**Comment by adrian17** [comment]
It appears that it was caused by https://github.com/ruffle-rs/ruffle/pull/1470 .
Even if the change reduces allocations. it also makes rustc even more eager to insert `memcpy`s - which from what I've seen, are especially heavy on wasm.

Also made a fast comparison of a 2 second window with a profiler:
![2020-11-25_18-42-33](https://user-images.githubusercontent.com/4729533/100264032-8c232480-2f4e-11eb-8d01-186ca408643f.png)

**Comment by Toad06** [comment]
Fixed by #1993.
