### ISSUE TITLE
HEEELLP

### ISSUE THREAD

**Issue by XxAshleyxXMoon** [ruffle-rs/ruffle#1739]
when i was trying to press on a game it said there was an error or something its done this to me before pls fix it if u can

**Comment by rdrpenguin04** [comment]
What error?

**Comment by manokara** [comment]
Which game?

**Comment by ousia** [comment]
@XxAshleyxXMoon,

congratulations for your first issue reported to Ruffle (and your first contribution at GitHub).

As @rdrpenguin04 and @manokara have stated, developers can fix errors they can reproduce.

If you were so kind, please contribute the following information, since otherwise it is impossible to know which problem you had with Ruffle:

1. URL of the game you was trying to play,

1. If you get a message similar to the one added below, please click on “View Error Details”, select all text, copy it and paste it here (this will contain the URL of the game).

    Keyboard shortcuts to select all text and copy it, once you selected text on “View Error Details” are _ctrl+a_ (select all) and _ctrl+c_ (copy). To paste it, press _ctrl+v_.

![ruffle-error-message](https://user-images.githubusercontent.com/203767/100488789-9260fe80-3110-11eb-9b3a-6fbf31f0a63f.png)

I hope it helps.

**Comment by Poopooracoocoo** [comment]
Also know that there's additional information (useful for if it doesn't crash but still has issues!) that Ruffle spits out into the console in Developer Tools (F12). If there's too much to read through, you can just scroll to the top. What you're looking for is if the SWF is a newer, more complicated and _unimplemented_ type written in AS3 that runs in AVM2. Hope this helps :))
