### ISSUE TITLE
MovieClip.hittest with shapeflag is not yet implemented

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#177]
Opening this so that we can track that `hittest` isn't fully done yet.

To implement this we will likely need to ask down to the backend to perform hit testing for us, as inside core we don't have any idea where a shape is actually visible on the screen.

**Comment by Herschel** [comment]
We'll want to render the object to a render target and test the opacity of the target pixel. This is similar to how the official Flash Player does it, because changing the stage antialiasing affects the result of hitTest. (This broke the collision detection in some games...!) This will also be used for mouse hit detection on buttons, which respect the object's shape (currently we just use the AABB).

This will require implementing render targets on all backends.

**Comment by TylerGlaiel** [comment]
I used hittest with shapeflag on some MASSIVE objects back in the day, (krazy kar pre-generated its entire map https://www.newgrounds.com/portal/view/276119) so I have a hard time believing that it actually rendered the entire object to a bitmap to test collision against it (or that this would be the right way to emulate it)

**Comment by Dinnerbone** [comment]
There isn't really any more efficient method of doing so that I can think of. We're already tessellating the shape (turning it from vector to pixels) to render it out to the screen, we either do it again once per test (extremely expensive) or cache it (essentially, saving the result of the render and using that for hitting). Given that the hit detection changes based on your graphics settings, it really would have been done this way in Flash too - except that we can do it much cheaper as we aren't software rendering.

**Comment by ROBERT-MCDOWELL** [comment]
Sorry for my stupid question but why SVG wouldn't be a good solution to convert Flash vectors?

**Comment by Dinnerbone** [comment]
SVG is just a way of expressing vector graphics, it's not a way of converting them to pixels. That process is called tessellation, and we currently use [lyon](https://github.com/nical/lyon) to do that (though there's a WIP PR to switch to using [pathfinder](https://github.com/servo/pathfinder). Ultimately, we're doing that already once to render it to the screen - it makes perfect sense to reuse that information to perform hittesting, as it is completely identical.

**Comment by TylerGlaiel** [comment]
im just saying I think the landscape in Krazy Kar was on the order of 100000 x 10000 pixels which would be pretty far beyond the max render target size in webgl (and use about 125mb of memory at 1 bit per pixel cached, or 8 gigs if cached in RGBA). and krazy kar 2 (https://www.newgrounds.com/portal/view/300110) had a mode that was 10x larger than that. somehow flash 7 was able to handle that back in 2006

**Comment by TylerGlaiel** [comment]
its possible/probable that what flash was doing was equivalent to rendering the shape (ex using code that already existed within their software renderer to get the color of the pixel at that point, probably by counting edge crossings along a horizontal ray) but it almost certainly wasn't literally rendering the whole thing (and that approach would cause some games, like my 2 I mentioned, to not emulate properly)

**Comment by ROBERT-MCDOWELL** [comment]
@TylerGlaiel  
Finally some developers start to tell the truth... :D

**Comment by ROBERT-MCDOWELL** [comment]
@Dinnerbone 
ok gotcha, I found this link maybe it will help
https://users.rust-lang.org/t/announcing-pixels-hardware-accelerated-pixel-frame-buffer/34326

**Comment by Dinnerbone** [comment]
Just took a quick look at that movie, all of the sprites are vector graphics. Size doesn't really matter, if it's tessellated out to 10x10 or 100,000x100,000. What matters is what's put on the screen (and yes, it absolutely wouldn't be the whole thing, occluded to just what's visible on screen, I agree). That will need to happen anyway for rendering or for hit testing, so again it'll be the same process of rendering out what's visible and hit testing those exact pixels that are visible.

**Comment by TylerGlaiel** [comment]
maybe I'm misremembering but I'm pretty sure that shapeflag hit test still worked for things that were off-screen

**Comment by Dinnerbone** [comment]
Aha, maybe! That was my bad for assuming, then. :D

**Comment by Herschel** [comment]
Naturally we wouldn't render the entire object to a buffer, we'd render to a 1x1 render target centered around the point in question (similarly for button mouse picking).

Mainly I was pointing out that it's not purely a point-in-polygon on the shape data, but that there's some sort of rendering and sampling being done of the final transformed shape, demonstrated by the fact that hitTest is affected by AA, line styles and caps, holes "disappear" if you scale the shape down, etc. So the easy way to implement it is to just render-the-thing using whatever backend is in use. (I do agree that it'd be good to be able to do this in software!)

**Comment by TylerGlaiel** [comment]
I had at least a few games that would do on the order of hundreds (possibly thousands?) of shapeflag tests per frame. rendering stuff to 1x1 renderbuffers hundreds of times just seems like it would be extremely slow

flash is an enigma i guess. I think I also remember that you could force flash to skip rendering frames (by syncing a piece of audio to an animation) and it would cause collision to mess up when that happened as well.

**Comment by Herschel** [comment]
Thousands, eek! Okay, I'm with you; it's not too hard to implement, and it's good to have a renderer-agnostic way to do this regardless.

**Comment by TylerGlaiel** [comment]
yeah if you want test cases Aqua Slug (https://www.newgrounds.com/portal/view/334324) and supersoldier (https://www.newgrounds.com/portal/view/284305) both used the same shapeflag-based platforming technique, aqua slug is probably the most tests there (each entity had 8 or 10 collision probe points, and it tested those against 3 separate clips (solid, cloud, water), if any collisions occurred it'd move the character one pixel at a time and re-test until it wasn't colliding anymore)

**Comment by magcius** [comment]
Yes, I'm quite sure Flash used some parts of their scanline renderer core to do hit tests, but it likely didn't actually render the object. If it knows the AABB bounds of each shape, it can easily run the spans for the specific Y-line that the object is on, and that would be quite fast.

I forget if Flash has proper winding mode support or if it's non-zero winding. If it's non-zero winding, this is even more free, since it just needs to sort the spans, rather than compute the actual winding curve.

It might make sense for Ruffle to implement a scanline renderer going forward to handle hit tests with efficiency.

**Comment by Herschel** [comment]
Flash default winding is even-odd, but it can be changed to non-zero in the newer shape tags (although I don't think this is exposed in the IDE anywhere?), as well as via the AS drawing API.

Scanline renderer would be a great end-goal, both for this and as a rendering backend in general.

I think to start we can do this analytically, iterating across all edges in the shape and calculating winding based on a horizontal raycast. This gives us a straightforward renderer-agnostic implementation, to get up and running in a reasonable timeframe. The difficult part is strokes, because a) they are affected by the transform of the object, and b) handling wacky endcaps and joins seems difficult. To start, we could just assume all-round joins (probably 99% of cases), and then these can be handled with a point-to-segment/curve distance test.

From there we could toy with pre-processing the shape data to sort the edges, which a scanline renderer would want anyway.

Naturally all of the above has to handle self-intersecting edges as well (e.g., making sure the spans remains sorted in a scanline renderer).

The nice thing is we can support different methods as we implement them (analytical point-in-shape, backend render target, scanline rendering, ...) and toggle them via a setting.

**Comment by TylerGlaiel** [comment]
flash sets 2 fill styles one for the left and one for the right of any path (see StyleChangeRecord) so theoretically all you need is to check the single edge closest to the test point along any axis to see if a fill is set on the same side of the path as the test point is, assuming that the spec isn't lying about that. 

are you sure that strokes are effected by transform? It doesn't seem to be the case to me

**Comment by Herschel** [comment]
Default is for strokes to scale (but can be changed in the IDE which creates a LineStyle2 with non-scaling strokes). Try making a movie clip with a 5px stroke and scaling it.  "Hairline" strokes appear not to scale but are actually normal strokes with a width of 1 twip -- Flash just renders strokes with a min width of 1px, and if you scale a clip with hairline strokes >20x you will see them scale as well.
![image](https://user-images.githubusercontent.com/36278/87085676-1d367080-c1e5-11ea-8611-6bdb619fa31f.png)


You can't rely entirely on FillStyle direction because a) even-odd winding means you can have a clockwise FillStyle1 inside a clockwise FillStyle1, and this would still generate a hole, and also weirdo stuff like this:
![image](https://user-images.githubusercontent.com/36278/87085369-9ed9ce80-c1e4-11ea-8b92-e390d3a0dfd9.png)
(Flash IDE will always try to normalize these and generate a vertex at the intersection, but this is not guaranteed; it's not-entirely-uncommon to see self-intersections in complex art, and you can also draw this shape via the drawing API.)
