### ISSUE TITLE
Add mobile detection

### ISSUE THREAD

**Issue by testing-platform-games** [ruffle-rs/ruffle#18052]
**Describe the feature**
Mobile detection can work by preventing mobile devices from playing an unsupported game on the web build (e.g. Mission in Snowdriftland) by using an attribute like 
html''

let player = ruffle.createPlayer();
player.config = {
    "MobileSupport" : "true",
};

or
let player = ruffle.createPlayer();
player.config = {
    "MobileSupport" : "false",
};

 and throwing up an error saying that this device can't run this content.

**Comment by torokati44** [comment]
I think this should be done on the embedder side, rather than in Ruffle itself.

**Comment by testing-platform-games** [comment]
It is to simplify the process so that people who do not know how to do that in html/javascript can do it with ease

**Comment by n0samu** [comment]
This is definitely outside the scope of what we do, sorry

**Comment by danielhjacobs** [comment]
I have to agree that I don't think Ruffle should be doing this, and Ruffle still needs to rely on what's available in JavaScript. There is no one-size-fits-all solution for detecting a mobile browser in JavaScript.

You can use a complex RegEx like the one listed on https://stackoverflow.com/a/11381730, but that's subject to becoming incomplete as new devices with new user agents are released and as noted on https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent it's very rarely a good idea to use user agent sniffing.

You'd be able to use https://developer.mozilla.org/en-US/docs/Web/API/NavigatorUAData/mobile#browser_compatibility if all the modern browser supported that, but they don't.

You could base this on screen resolution, but someone may just have resized their desktop browser window.

The orientation property of the Screen interface may have once been usable for this, but not anymore since desktop browsers now support it too: https://developer.mozilla.org/en-US/docs/Web/API/Screen/orientation#browser_compatibility

You can check the `window.orientation` property is defined but that's subject to removal in the future or not being added to any hypothetical future browsers since it's deprecated: https://developer.mozilla.org/en-US/docs/Web/API/Window/orientation.

You can check if the device is a touchscreen but that will also detect tablets and touchscreen desktops.
