### ISSUE TITLE
King Dugan's Dungeon Text cut

### ISSUE THREAD

**Issue by calthax** [ruffle-rs/ruffle#18108]
### Describe the bug

When I play King Dugan's Dungeon on Newgrounds at https://www.newgrounds.com/portal/view/598976 the bottom part of the text gets cut out 
![KDD Text cut](https://github.com/user-attachments/assets/c72652ac-e1b9-4215-8bfb-f14ac8215bab)

### Expected behavior

The text is supposed to display normally

### Content Location

https://www.newgrounds.com/portal/view/598976

### Affected platform

Browser's extension

### Operating system

Linux Mint 22

### Browser

Firefox 130.0.1

**Comment by kjarosh** [comment]
I see two main causes of this not working currently:
1. slight inconsistencies related to spacing between Ruffle and FP — that requires work from the ground up and a lot of tests, here the text is a bit too low in Ruffle (leading?);
2. behavior related to text clipping — FP does not clip pixels but lines (with the exception of the first line which is never clipped), I believe this SWF uses this property and text bounds are slightly smaller than the text itself, which FP renders fully and Ruffle clips — unfortunately, I don't think we can duplicate this behavior due to 1., as we may clip text which shouldn't be clipped.

**Comment by kjarosh** [comment]
Fixed by https://github.com/ruffle-rs/ruffle/pull/18332
