### ISSUE TITLE
XML not loading into SWF?

### ISSUE THREAD

**Issue by dpoetry** [ruffle-rs/ruffle#1811]
I've configured everything and for the most part all my flash files in an Electronic Literature creation of mine seem to work really well. 

However, I am having a problem with pulling in an XML file on top of the SWF file.  This might seem overly complicated. But I'll try to explain.  The html file loads p1.swf.   Then p1.swf uses LoadMovie to load a p1add.swf file.  Then the p1add.swf file uses xml to load a bunch of images/jpgs.    So either the p1add.swf isn't loading properly or the XML file inside the p1add.swf file isn't loading. 

I am guessing the issue is it not loading the XML file. As other sections of this work use the LoadMovie function just fine and load external SWFs on top of other SWFs. 

Here is the overall work: http://www.dpoetry.com/ruffletest/wittenoom2/starthere.html

And here is the page in with the XML files not loading: http://www.dpoetry.com/ruffletest/wittenoom2/artwork/p1.html

And here are the relevant files: 

The HTML file: http://www.dpoetry.com/ruffletest/wittenoom2/artwork/p1.html
The primary SWF file: http://www.dpoetry.com/ruffletest/wittenoom2/artwork/p1.swf
The LoadMovie SWF file: http://www.dpoetry.com/ruffletest/wittenoom2/artwork/p1add.swf
The XML File: http://www.dpoetry.com/ruffletest/wittenoom2/artwork/images.xml
All the files: http://www.dpoetry.com/ruffletest/wittenoom2/artwork/

LASTLY:  This is what the page above should look and function like: http://www.secrettechnology.com/wittenoom/artwork/p1.html.   (will have to enable flash)

NOTE: The above URL from secrettechnology does not have Ruffles loaded. So everything still works within Flash. 

Does any of that make sense? 

cheers, Jason Nelson

**Comment by dpoetry** [comment]
Here is another example of the XML file not working. 

http://www.dpoetry.com/ruffletest/sydney/

This is the working version in Flash.....(enable the flash player)

http://www.secrettechnology.com/sydney/

So it appears the issue is primarily the XML files not working. Do you have any idea of how to fix this?
Or perhaps there is another work around?

cheers, Jason

**Comment by Fancy2209** [comment]
I think ruffle doesn't support XMLs yet

**Comment by n0samu** [comment]
Hi @dpoetry, sorry for the long delay triaging your issue. This is not actually a problem with XML loading, but a few separate problems (one of which has been recently fixed!)
- External image loading was not yet implemented, so the falling pieces of paper were not appearing. It is now implemented since #6547.
- The pieces of paper appear blank because bitmap drawing is not yet implemented on the web backends. It is already working on the desktop app (#7254) and we are working to bring that functionality to web soon.
- Your second sample (sydney) uses ActionScript 3. Support for AS3 is still in the very early stages.

**Comment by n0samu** [comment]
It seems like all of the originally mentioned problems are fixed now. I've opened a new issue related to Sydney's Siberia here: #11882
