### ISSUE TITLE
(Question) Do you compare the Ruffle performance with the original Flash Player performance?

### ISSUE THREAD

**Issue by hardBSDk** [ruffle-rs/ruffle#18244]

**Comment by Croworbit** [comment]
Yes, ruffle is compared to flash player a lot. even if the devs did not, many people discuss it in issues as well.
optimizations are made often, so ruffle should slowly improve.

**Comment by Dinnerbone** [comment]
We don't have any published numbers on our performance right now, because it can be very situational, but we do constantly try to benchmark and improve where we can.

In some scenarios we're actually faster than Flash, usually by leveraging the gpu. In some scenarios we're much slower, right now our actionscript execution is slower than Flash Player's for example.

If you find a game or animation that you think is unreasonably slow please feel free to open an issue about it, but rest assured we are always working on improving our performance and optimising things.

**Comment by hardBSDk** [comment]
@Croworbit That's great to know!

@Dinnerbone Thanks for your answer!

Sure, I know that slowness should be reported (I already did months ago), I need to retest my games with the current performance to close these issues.
