### ISSUE TITLE
Regression in buttons

### ISSUE THREAD

**Issue by 123jjck** [ruffle-rs/ruffle#18610]
### Describe the bug

1. Enter the game: https://xarium.cc/playtest.php
2. Try to hover and click any of these objects:
![Image](https://github.com/user-attachments/assets/65d0b705-6361-4666-bd8f-141a916a2cc6)
![Image](https://github.com/user-attachments/assets/16ab73a3-0599-4d2c-bf44-b3736416ad34)
3. Nothing happens

### Expected behavior

Buttons respond to pointing and pressing:
![Image](https://github.com/user-attachments/assets/bc497312-53c6-4170-8b2f-8fee1020aa56)

### Content Location

https://xarium.cc/playtest.php

### Affected platform

Self-hosted version

### Operating system

Windows 11

### Browser

Google Chrome 131.0.6778.70

### Additional information

Probably due to #18434 - [nightly-2024-11-03](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2024-11-03) works fine, but starting with [nightly-2024-11-05](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2024-11-05) there are problems

**Comment by kjarosh** [comment]
CC @Toad06

**Comment by Toad06** [comment]
This game loads internal SWFs. One of the files contains the following code:
```as // child.swf
this.onRollOver = function() {
   mco.gotoAndStop("over_fr");
   ShowHint(this_mc);
};
this.onRollOut = this.onReleaseOutside = function() {
   mco.gotoAndStop("out_fr");
   RemoveHint();
};
```

If you open the file directly in Flash Player or Ruffle, this won't work because `this` refers to the root. For the same reason, this issue also occurs if you load it into a different level using `loadMovieNum`.

However, loading the file into a target movie clip that is part of the root works in Flash Player:
```as
this.createEmptyMovieClip("container", this.getNextHighestDepth());
loadMovie("child.swf", "container");
```

This doesn't work in Ruffle because `fn is_root` returns `true` in this situation, as this function actually indicates "whether this display object represents the root of loaded content".

So replacing the `is_root` check with `DisplayObject::ptr_eq(self.as_displayobject(), self.avm1_root_no_lock())` prevents the issue from occurring.

[test.zip](https://github.com/user-attachments/files/17780861/test.zip)

**Comment by Toad06** [comment]
I've opened the PR. I believe there may be other places where we should use `avm1_parent().is_none()` instead of `is_root()`. For example, in the file "test.zip" from my previous message, pressing the TAB key selects the movie clip in Flash Player, but in Ruffle, nothing happens.
