### ISSUE TITLE
Playing The Witch (1)

### ISSUE THREAD

**Issue by LeoKids** [ruffle-rs/ruffle#1868]
Im playing it,It works correctly but when i Start,It Seems that Ruffle Doesnt recongnize when i start,It will be controlled by Ruffle Not Me! Just End so Short! and it repeats again!

**Comment by ousia** [comment]
Hi @LeoKids,

sorry, but developers can only fix what they can reproduce. Let me try to help, but we need to improve the issue report first.

Probably the issue you are experiencing is most obvious to you, but the rest of us need a clear description of your issue.

Some information is needed to be able to understand what you are speaking about.

Please, provide the address of the game. “The Witch (1)” seems to be too generic to identify a particular Flash game.

Please, compose clear and short sentences (instead of what it seems a huge single one). Now it is really hard to guess what you mean.

I try to translate your description. Sorry if I get it wrong.

> While I’m playing the game<a href="#fn1" id="bfn1">¹</a>, it works fine. But when I start it<a href="#fn2" id="bfn2">²</a>, Ruffle cannot detect when the game has been started.

Sorry, but here I have to guess:

> Ruffle prevents user interaction. So the game is over earlier than it should be. After the game has ended, Ruffle restarts it again. 

Sorry, my interpretation may be totally wrong and misleading. Please, correct me, if this happens.

Provide the address for the game. And provide a video displaying the issue you mention, if this is easier for you.

Just in case it helps.

#### Footnotes

<a href="#bfn1" id="fn1">¹</a> Remember that, unless you provide us with its address, the game is unknown to the rest of us. 
<a href="#bfn2" id="fn2">²</a> In the previous sentence, you stated that the game works fine while you are playing it. Unless you explain this in detail, this is contradictory with your issue report (since you describe that you are not able to play the game after you start it).

**Comment by Poopooracoocoo** [comment]
@LeoKids Is this the same game that you filed #1195 for? You included a link to the SWF for _The Witch's Castle_, a game from 2001 in Catalan.

You should also tell us how you're using Ruffle. I'm guessing that you were using the nightly that was available 4 days ago (when you filed your issue) in the web demo.

**Comment by ousia** [comment]
URL for the game might be (as suggested by @Poopooracoocoo) may be the following one:

> http://web.archive.org/web/20081106134642/http://www.thetriplets.com/play/castellbruixa/castellbruixa.html

**Comment by LeoKids** [comment]
No,The game was this

https://web.archive.org/web/*/http://www.lestresbessones.com/elpati/jocs/cont/labruixa.swf

**Comment by LeoKids** [comment]
https://web.archive.org/web/20120701093758/http://www.lestresbessones.com/elpati/jocs/labruixa.html

**Comment by ousia** [comment]
According to your report, SWF is contained in:

> https://web.archive.org/web/20120701093758oe_/http://www.lestresbessones.com/elpati/jocs/cont/labruixa.swf

**Comment by LeoKids** [comment]
Yes Ousia.
