### ISSUE TITLE
no video on 2004 'f-the-vote'  swf

### ISSUE THREAD

**Issue by akhepcat** [ruffle-rs/ruffle#1908]
Apparently I'd saved off this swf back in 2004 (along with the classic "All Your Base are Belong to Us"  - which works fabulously!)
and while the audio of the swf plays back, there's no video after the embedded "click to play" is pressed.

Two errors pop up:
    [2020-12-10T17:14:16Z ERROR ruffle_core::library] Tried to instantiate non-registered character ID 21
    [2020-12-10T17:14:16Z ERROR ruffle_core::display_object::movie_clip] Unable to instantiate display node id 21

This SWF  *may* be  NSFW - I don't really know anymore.    

I will make it available for testing, but unless asked for, I won't attach it to the bug report directly.

**Comment by ousia** [comment]
@akhepcat, any chance to get the address of the SWF file?

https://archive.org is also a valid option.

Otherwise, it is impossible to check video or anything with that file.

**Comment by torokati44** [comment]
Referencing #723 as an umbrella issue that most likely covers this.

**Comment by akhepcat** [comment]
https://web.archive.org/web/20040901033320/http://www.fthevote.com/process.php   seems to contain the swf.

**Comment by ousia** [comment]
Direct link: https://web.archive.org/web/20040901033320oe_/http://www.fthevote.com/fthevote.swf.

**Comment by torokati44** [comment]
The changes in #2173 make the video play just fine - although the latest commit (as of right now: 86f1498bfb025695619644001e3cd1b189726c68) actually regresses here fairly badly; the commit before that seems to work well.

**Comment by torokati44** [comment]
It seems the video is missing some frames? Not sure if this is a framerate conversion artifact, or what, but Adobe player doesn't seem to mind, nor did Ruffle before 86f1498.
With 86f1498, I get an `error when seeking to video frame 1: Attempted to seek to unknown frame 1`, and as a consequence, seeking to any frames past that will fail, until the next keyframe.
The same thing happens with many frames throughout the clip, getting the playback stuck most of the time.

**Comment by kmeisthax** [comment]
It's not a framerate artifact. I wrote code to avoid out-of-order seeks that would decode incorrectly, to match Flash Player behavior. The design of H.263 is such that you can only seek to the next frame forward *or* to frames that update the entire screen and are marked as doing so; if some code tries to do that then it snaps back to the previous keyframe.

Since timeline movies don't skip around their source stream, this particular rule only matters for ActionScript seeks, which I'm not implementing in the H.263 PR, but it still needs to be enforced anyway. Or at least, that's what I thought, but I guess there's always exceptions with Flash.

**Comment by kmeisthax** [comment]
c3b24959 should resolve the regression.

**Comment by torokati44** [comment]
With #2173 merged, I think this issue is now resolved, and can be closed. Can you verify, @akhepcat?

**Comment by akhepcat** [comment]
Verified, ruffle-nightly-2021_08_24-linux-x86_64.tar.gz   plays the SWF perfectly.

Closing this ticket with thanks to the team!
