### ISSUE TITLE
Add warning dialog for AS3 movies

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#1978]
We should display a warning dialog for AS3 movies indicating that they probably won't work properly. It can be similar to the panic dialog, but it should be dismissable and maybe not as orange :-)

We could reuse this warning dialog for other errors (404, etc.).

Since this is fairly high priority to improve user experience, we could focus on implementing this for web initially.

**Comment by SamMorrowDrums** [comment]
I had a go just using system dialogs. Of course, if we want to display something like suggested `It can be similar to the panic dialog, but it should be dismissable and maybe not as orange :-)` this PR is not really correct.

**Comment by Diatonator** [comment]
I'm not sure how I feel about system dialog option (if you're talking dialogs like "Don't click away from our 9999999$ giveaway!11"). I would go with fairly unintrusive, but also noticeable option. Like most sites do "cookie warnings" for example, this could be placed somewhere at the top or the bottom of the player, with an X button, fairly transparent.
Also I don't support "panic" similar option, because there are AS3 flashes which do work fairly well, just with barely noticeable differences. Maybe because there is not much of actual AS3 in them. This "panic" will disrupt (at least visually) what's already working basically.

**Comment by SamMorrowDrums** [comment]
> I'm not sure how I feel about system dialog option (if you're talking dialogs like "Don't click away from our 9999999$ giveaway!11"). I would go with fairly unintrusive, but also noticeable option. Like most sites do "cookie warnings" for example, this could be placed somewhere at the top or the bottom of the player, with an X button, fairly transparent.
> Also I don't support "panic" similar option, because there are AS3 flashes which do work fairly well, just with barely noticeable differences. Maybe because there is not much of actual AS3 in them. This "panic" will disrupt (at least visually) what's already working basically.

Yeah I certainly think that's possible, it was only a case that doing the async handling and styling makes this a bigger ticket. 

Is this an intermediate step that's even workable or is it making it worse?

It does all the work required to prepare the code for alternative implementations, so it's definitely a step towards showing information to end users.

**Comment by Poopooracoocoo** [comment]
https://github.com/GoogleChrome/dialog-polyfill is an alternative to alerts

**Comment by Diatonator** [comment]
> Is this an intermediate step that's even workable or is it making it worse?

I'm not sure how others will react to this, I'm just a fan of less distraction. If you think that releasing this in a current state will reduce the number of logged issues you would like to reduce already, and increase the productivity of bug fixing, then I won't object for sure.
