### ISSUE TITLE
Ruffle Error on https://get.adobe.com/flashplayer/about/

### ISSUE THREAD

**Issue by VFDan** [ruffle-rs/ruffle#2038]
# Error Info
Error name: TypeError
Error message: bi[e] is not a function
Error stack:
```
hi@https://get.adobe.com/flashplayer/about/:3:32170
bind/<@https://wwwimages2.adobe.com/ubi/template/identity/lib/prototype.js:209:23

```

# Player Info
Allows script access: false

# Page Info
Page URL: https://get.adobe.com/flashplayer/about/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-19
Channel: nightly
Built: 2020-12-19T00:34:27.448Z
Commit: 042e9a444b98f7dbf920a070ffe240ad01e7cbe4

**Comment by rdrpenguin04** [comment]
Hello!

I am actually working on getting that SWF to run currently. It is one of the simpler AVM2 programs I know of, but it still requires a lot of setup to get working.

I'm almost wondering if there should be a tracking issue for this file, since it would be a major step towards AS3 compatibility?

**Comment by rdrpenguin04** [comment]
Although, this doesn't seem to have to do with AVM2...? This happens in Ruffle's loader it would seem.

**Comment by Toad06** [comment]
Thanks for the report.

This is an issue implying a conflict with the `prototype.js` library, so I'm closing this in favor of #1507 and #1630.

Thanks again.
