### ISSUE TITLE
Stinkoman 20x6 doesn't work

### ISSUE THREAD

**Issue by atomic1fire** [ruffle-rs/ruffle#2057]
First level causes the game to glitch out (console says something about missing nodes?)

Level 10 loaded but didn't have a platform.

 https://homestarrunner.com/stinkogame/v7/stinkogame.html

Figured I'd post it here as it just came out.

**Comment by kmeisthax** [comment]
Level 1 actually takes too long to draw and the script timeout terminates execution. This causes all hell to break loose. We'll need to optimize whatever it's doing so that it doesn't die in the loader.

Level 10 appears to be referencing unregistered characters - that's why there's no platform. There's a whole bunch of `Export already exists` errors when the game loads; and JPEXS outright states it uses library exports, which I have no idea if we handle correctly yet. For what I presume is the same reason Level 10 also fails to grab it's cutscene audio.

Also, the new FMV kinda spooked me a bit since I was testing the video branch and thought for a second that my code was somehow working correctly (it's not wired up yet). They actually cut their FMV up into images, presumably for Ruffle, which is nice.

**Comment by n0samu** [comment]
Strangely, the timeout only seems to occur in Chromium-based browsers, not Firefox. (On my machine, at least)

**Comment by salty-horse** [comment]
Levels 1 and 10 no longer exhibit the issues mentioned. Can this be closed?

**Comment by Sonikkustar** [comment]
Game appears to work fine now.

Level 1:
![image](https://github.com/ruffle-rs/ruffle/assets/22226938/a62a81da-2c4c-4c5f-9eec-852d4b8f042b)

Level 10:
![image](https://github.com/ruffle-rs/ruffle/assets/22226938/b3aa5401-f788-43cb-b8d7-9b56ab77442d)

Site now uses ruffle-nightly-2023-11-24.
