### ISSUE TITLE
Ruffle Error on http://playporngame.com/porngame/lost-spirits.html

### ISSUE THREAD

**Issue by qqwww666** [ruffle-rs/ruffle#2070]
# Error Info
Error name: Error
Error message: panicked at 'cannot recursively acquire mutex', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/wasm/../unsupported/mutex.rs:22:9
Error stack:
```
Error: panicked at 'cannot recursively acquire mutex', /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/wasm/../unsupported/mutex.rs:22:9
    at Object.Y (http://playporngame.com/html/core.ruffle.8523be3f1afb3ed16c0c.js:1:20617)
    at __wbg_new_df6e6ab7a65c4c4d (http://playporngame.com/html/ruffle.js:1:35853)
    at wasm-function[1117]:259
    at wasm-function[1457]:373
    at wasm-function[3876]:65
    at wasm-function[3036]:224
    at wasm-function[4230]:39
    at wasm-function[4182]:40
    at wasm-function[4232]:35
    at wasm-function[813]:987
```

# Player Info
Allows script access: false

# Page Info
Page URL: http://playporngame.com/porngame/lost-spirits.html
SWF URL: http://playporngame.com/porn-games/lost-spirits.swf

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-18
Channel: nightly
Built: 2020-12-18T00:34:17.923Z
Commit: beed570475728423564d319543f95a4f67300382

**Comment by Poopooracoocoo** [comment]
Is that Chrome 69? Can you reproduce on another browser? 
Here are some options instead of updating Chrome:
- Install a Chromium based browser like Edge, Brave, Vivaldi, Opera, etc
- Install another Chrome channel like Canary (but I think Beta will replace your installation of Chrome!)
- Install Firefox
- Maybe check chrome://flags for some WASM stuff and enable them??

And when does it crash? It doesn't seem to crash immediately although I feel really awkward doing anything more than pressing play lol.
