### ISSUE TITLE
Allow JavaScript API to load via URL

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#21]
Currently the JavaScript API accepts a Uint8Array of the SWF data to load, requiring the user to fetch the data manually. This was because I didn't want to deal with JS futures/promises in wasm-bindgen while it was not stable. Now that this has stabilized, the API should take in the URL as a string and fetch the content itself. This is also necessary to support streaming downloads (#18).

**Comment by wizzwizz4** [comment]
How do you plan to deal with CORS in the web? It can't be fully compatible with Flash in this way, since Flash uses crossorigin.xml.

**Comment by Herschel** [comment]
Yes, unfortunately we have to live with CORS, so loading arbitrary remote URLs will be no go.

**Comment by larsiusprime** [comment]
This sort of exposes some tensions in building a truly accurate "Flash Emulator" -- the web platform itself will not allow a completely faithful rendering that reimplements some of the fundamental security issues like this one.

A desktop version might still be allowed to do it in some form, however? Probably would want to put in caveats about that if one chose to go this way.

As for the web, this might be a historical curation/preservation/"restoration" issue more than a simple tech blocker -- might have a chat with BlueMaxima from FlashPoint? To get the FlashPoint project to work they sometimes had to modify SWFs to spoof remote content and work around site locks. It is a modification of the original artifact and thus not "pristine", but in certain cases it might be the only way to preserve certain works. That sort of task might be out of scope for the ruffle project itself, but it's something to keep in mind for any preservationists/historians/curators/librarians who want to make use of the project in its web based format.

**Comment by Herschel** [comment]
There will certainly be cases where we cannot be accurate due to the nature of web APIs. Hopefully the desktop player will make up for these cases.

In this specific case, I picture Flash sites would host the Ruffle code directly on their server, which should avoid issues (assuming the SWF and ancillary content is hosted locally), or they could even add the proper CORS headers.

I definitely consider quality-of-life features such as spoofing remote content, fixing site locks, etc. to be in the scope of the project! In fact, this should be easier for us because we can intercept the calls to `URLRequest` etc. and return whatever value we prefer, as opposed to having to reverse engineer and alter the SWF content itself? I picture passing a JS parameter block when you initialize Ruffle with various options for the above. (Probably should make a separate issue for this).

 (cc @BlueMaxima)

**Comment by larsiusprime** [comment]
Just FYI not sure if BlueMaxima's github account is all that active, you'll probably have better luck reaching out to him on twitter: https://twitter.com/bluemaxima

Is he on the Discord, too?

**Comment by KuromeSan** [comment]
i dont get why javascript doesnt let you just send a request without CORS (just wirthout cookies) and acturally read the response .. 

like it would be trivial to make a server side script on your current origin that just GET's a page cross-origin and returns the output but whatever .

**Comment by wizzwizz4** [comment]
@KuromeSan What is "without CORS"? Note that some bank websites (and similarly high-risk targets) are vulnerable to sending sensitive data to users on a "logged-in IP", even if they say "no, please don't!".

**Comment by kmeisthax** [comment]
So, the underlying problem is that unrestricted cross-origin communication completely breaks the security model of the web, even if you only allow it a little bit. (See also: [the problem with Google Chrome's `<portal>` element](https://research.securitum.com/security-analysis-of-portal-element/)) Not every website puts a nice bright "THIS IS SENSITIVE INFORMATION" flag on their data, so the only way to keep those websites secure from data exfiltration is to make cross-origin requests explicitly opt-in.

`crossorigin.xml` in particular was a bad idea and a source of *frequent* security bugs. We technically could emulate it in WebExtension Ruffle, but I don't want to, and we'd probably get banned from Chrome if we did. Consider this an "[intervention](https://developers.google.com/web/updates/tags/interventions)" to the Flash platform. If a website wants their cross-origin Flash content to work on Ruffle they'll have to add CORS support to their server and mark those particular files as cross-origin safe.

**Comment by Herschel** [comment]
This is in place now.
