### ISSUE TITLE
ruffle dont work on spielaffe.de

### ISSUE THREAD

**Issue by SoftwareRat** [ruffle-rs/ruffle#2100]
![image](https://user-images.githubusercontent.com/40393784/103153143-3f697e00-4786-11eb-90ba-56ff78746eb5.png)

**Comment by Poopooracoocoo** [comment]
devtools console logs:

![image](https://user-images.githubusercontent.com/51363864/103163985-6cd32c00-4859-11eb-9825-fd74633aac53.png)

CORS errors :(

**Comment by Toad06** [comment]
`www.spielaffe.de` tries to load files from `cdn.spielaffe.de`, which doesn't work due to security restrictions of modern web browsers. Ruffle cannot bypass this, so the website owner will have to create a CORS configuration (([#1672 (comment)](https://github.com/ruffle-rs/ruffle/issues/1672#issuecomment-732483040)).
