### ISSUE TITLE
Smearing of Bitmaps

### ISSUE THREAD

**Issue by littleguystar** [ruffle-rs/ruffle#2143]
Some bitmaps are smeared out.
I should test it more, but it seems to be large ones only
![unknown 1](https://user-images.githubusercontent.com/76085046/103244788-f266e280-4912-11eb-9ddb-df8ae6f4c956.png)

**Comment by spikything** [comment]
Seems related to this [https://www.spikything.com/games/superbughunt/](url) where, only on mobile, the game background bitmap has a similar 'smearing' issue. It's possibly a video memory allocation issue, because the bitmap in question is a stretched and rotated tiled fill to a large shape on the stage - if memory serves (this game is nearly 20 years old :) Direct link to the SWF [https://www.spikything.com/games/superbughunt/super-bug-hunt.swf](url)

**Comment by littleguystar** [comment]
> Could you post the SWF your are testing with? (Either a link, or ZIP and attach here).
[https://cdn.discordapp.com/attachments/722866209682620521/794986665080913990/772648_echidna-ruins.swf](url)
The only actionscript 3 is the vcam

**Comment by spikything** [comment]
@Herschel is there some type of automated 'integration-level' testing for graphics, to which I could contribute? I noticed the graphics unit tests which seem to trace a bunch of things out (such as the DisplacementMapFilter test), though I'm not entirely sure how they work. What I'm talking about would be simple SWF files which puppet around graphics using various filters, masks, etc. Run inside headless Chrome, using something like Selenium to compare the actual output to reference screenshots, for example. We used similar test cases at YouView TV when it was running on the unfinished Stagecraft 2 runtime (Adobe AIR for TV) to isolate problems with rendering, hardware acceleration, etc.

**Comment by torokati44** [comment]
This might have been fixed by #2264, specifically by https://github.com/ruffle-rs/ruffle/commit/0754f0a3b3dc83ec5e65e498668550857ba43426 .

At least on for me, on Linux desktop (Vulkan), the before and after screenshots:

![image](https://user-images.githubusercontent.com/288816/108211881-88f29b80-712d-11eb-8f1c-ee21e7454ec1.png)

![image](https://user-images.githubusercontent.com/288816/108211983-a9baf100-712d-11eb-984c-00fb997850d9.png)
