### ISSUE TITLE
game works with Nightly 2020-12-11 but not with the latest version

### ISSUE THREAD

**Issue by net-lix** [ruffle-rs/ruffle#2149]
game (Locked Cabin AS2) works with Nightly 2020-12-11 but not with the latest version (Nightly 2020-12-28)

error: `ruffle_web_bg.js:1257 SharedObject::get_local: Unable to parse movie URL`

working game (with Nightly 2020-12-11) : https://en.playit-online.de/game/locked-cabin/

![image](https://user-images.githubusercontent.com/30718270/103275555-bb510980-49c4-11eb-8e66-2caf54c40843.png)

in the current demo the game restarts again and again:

![image](https://user-images.githubusercontent.com/30718270/103275723-14b93880-49c5-11eb-80ef-41ed209c7418.png)

swf file: https://www.playit-online.de/games/adventure/lockedcabin/lockedcabin.swf

**Comment by Toad06** [comment]
Thanks for the report.

It looks like this issue is related to commit https://github.com/ruffle-rs/ruffle/commit/367404ddd8631e2be5cbd12cdf3a8fb9888fc33a.

FWIW, changing the following code in `core/src/avm1/globals/shared_object.rs`:
`activation.context.shared_objects.insert(name, this);`
to:
`activation.context.shared_objects.insert(full_name, this);`
seems to do the trick.
