### ISSUE TITLE
Ruffle Error on https://www.freekigames.com/grub-guardian

### ISSUE THREAD

**Issue by EthanZeigler** [ruffle-rs/ruffle#2156]
# Error Info
Error: Error creating player

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.freekigames.com/grub-guardian

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:78.0) Gecko/20100101 Firefox/78.0
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2020-12-28
Channel: nightly
Built: 2020-12-28T00:42:22.474Z
Commit: 8d707bc6ab747ae5039ce629f07c09aabfac2553

----
Happy to answer any questions. This seems to happen for every flash game on the site.

**Comment by Toad06** [comment]
Thanks for the report.

An external JS library is defining a variable named `Window` (the capital letter matters - it doesn't overwrite the native `window` object) and Rust doesn't seem to like that. Renaming `Window` to anything else prevents the panic.

In `web/src/lib.rs`, I've changed:
`.map_err(|_| "Error creating player".into())`
to:
`.map_err(|e| e.to_string().into())`

to get the "real" error:
`Error: Expected window`

**Comment by Herschel** [comment]
Yikes, wonder if this should be filed upstream on `wasm-bindgen`.

**Comment by Toad06** [comment]
I've made additional testings, it actually appears that `Window` is a native function. Overwriting it ends up creating issues, just like prototype.js did with `Array.prototype.reduce`.

The function that causes this issue is in `core.ruffle.js`:
```
const __wbg_instanceof_Window_49f532f06a9786ee = function(arg0) {
    var ret = getObject(arg0) instanceof Window;
    return ret;
};
```
Forcing the function to return true immediately prevents the issue from happening. I think we'll have to detect if `Window` has been overwritten and if it is, running a code like: `Window = window.constructor;` (assuming constructor hasn't been overwritten as well 😅).
