### ISSUE TITLE
Friv games are stuck on a white screen and couldn't load.

### ISSUE THREAD

**Issue by IIWare** [ruffle-rs/ruffle#2205]
Hi, I was sad about the death of flash games, but then I recently heard about this project, so I would like to play friv games, but it's taking a while, stuck on a white screen for a long time, I had a strong internet connection, but when I load flash games that isn't from friv, it loads smoothly, so what caused friv games to be stuck on a white screen? thanks.

**Comment by Toad06** [comment]
Thanks for the report. The issue is that `frivclassic.com` tries to load files from `l.funo.com`, which doesn't work due to security restrictions of modern web browsers. Unlike the official Flash Player, Ruffle cannot bypass this and unfortunately ends up displaying a white screen. You can see ([#1672 (comment)](https://github.com/ruffle-rs/ruffle/issues/1672#issuecomment-732483040)) for additional information.

**Comment by IIWare** [comment]
@Toad06 thanks for telling me, I found the error, and I came up with an idea:

so we could mirror all the SWF's from l.funo.com, so to mirror it, first a user loads a friv game (http://www.frivclassic.com/menu/games/redball/f.html) and then the extension (not the user, the ruffle extension) checks the url and then copies the text in URL between "es/" and "f.html" (the text in between them is redball) and then the extension adds the text twice into the friv game's SWF file (http://l.funo.com/z/redball/redball.swf) then the extension uploads the SWF to another website with all the friv SWFs.

so if the swf doesn't exist in that another website, the extension copies the friv SWF file to another website with all the friv SWFs, then the extension tells friv to load the SWF from that website with all the friv SWFs.

if the SWF exists in that another website, then the extension can tell friv to load the SWF from that another website.

this is just an idea of how could the extension load friv games, on how to improve the extension.
