### ISSUE TITLE
A few visual problems in the flash clip

### ISSUE THREAD

**Issue by Diatonator** [ruffle-rs/ruffle#2241]
Chrome 87.0.4280.88
Tested on nightly builds 2020_12_15 and 2021_01_03 

https://z0r.de/1656

![image](https://user-images.githubusercontent.com/75184268/103492422-c203d480-4e3b-11eb-9577-c002f5ac9995.png)

This flash has a few problems

1) No text on the left-bottom:
![image](https://user-images.githubusercontent.com/75184268/103492430-d942c200-4e3b-11eb-9389-5d305c69d2ff.png)

I bet the "string data" error is related to this, and probably it's the '(c)' character.

2) At the end of a flash loop (around 20-30 sec in) you will see a two highly distorted "spartans" emerging from the earth:

Adobe:
![1656_Adobe](https://user-images.githubusercontent.com/75184268/103492553-cb417100-4e3c-11eb-9db0-9bc7b4f1ffa6.gif)

Ruffle:
![1656_Ruffle](https://user-images.githubusercontent.com/75184268/103492555-cf6d8e80-4e3c-11eb-9490-e5bc6a4c618b.gif)

I believe those distorted are the "spartans" which were used in a different way in this flash. The first distorted one got the "talking mouth", and you can actually see that mouth undistorted, and another distorted one got another head attached to him.

I actually seen the similar distortion in this flash:

https://z0r.de/2264 (EPILEPSY WARNING)
![image](https://user-images.githubusercontent.com/75184268/103492691-aa2d5000-4e3d-11eb-9e32-f439c4718a25.png)

**Comment by Toad06** [comment]
1/ This is a SWFv5 text-decoding issue, just like #2043.

2/ This one is more mysterious. On the desktop backend (Windows), a bunch of errors are logged before the file actually plays: `ERROR ruffle_render_wgpu] Tessellation failure: TooManyVertices`.
![renderer](https://user-images.githubusercontent.com/14274782/103543504-ec3aae00-4e9e-11eb-8ec7-632921670233.png)

**Comment by torokati44** [comment]
In at least https://z0r.de/2264 there is a shape with so many complex paths that `register_shape_internal` indeed ends up producing a mesh with something like 130k vertices* (if I checked it right), and an `u16` index format can't deal with that - or maybe it just trips an artificial limitation for sanity. For the non-GPU paths this is not a problem, because with those, the meshes never have to be serialized into IBOs/VBOs.
- Switching to `wgpu::IndexFormat::Uint32` might help, but this _might_ also have performance implications.
- Or, `register_shape_internal` could also split up these extremely complex shapes into several smaller `Mesh`es, and return a `Vec`?

I also tried increasing the curve approximation tolerances for both fills and strokes, but the paths themselves are made up of so many elements (which are not curves) that it didn't make much of a difference.

[*]: Maybe it was auto-vectorized from a noisy bitmap or something like that? I haven't checked if this is how it is actually stored in the .SWF or it's something that ends up happening at runtime. By the looks of it, https://z0r.de/1656 also has something like this.

**Comment by Herschel** [comment]
Bad triangulation fixed by #2264. These types of graphics are usually made with the "Trace Bitmap" function in the Flash software. Bumped the index format to u32, this should be fine. This was on my todo list for a while, kept forgetting about it!

@Diatonator Could you file a separate issue for the text problem? Thank you!

**Comment by Diatonator** [comment]
@Herschel done https://github.com/ruffle-rs/ruffle/issues/2283

**Comment by Diatonator** [comment]
I'll also test here as I get the build with the changes:
http://eye.swfchan.com/flash.asp?id=4473&n=1285.swf

The output now at some parts is hilarious
![swfchan_id4473](https://user-images.githubusercontent.com/75184268/103641642-1ce41b80-4f63-11eb-9d23-05e915b62f9a.gif)

**Comment by torokati44** [comment]
Couldn't see a single graphical glitch now with this .swf either, at least on Deskop, with the Vulkan backend.
