### ISSUE TITLE
Key.isDown mixed with KeyListener diverges from Flash player behavior

### ISSUE THREAD

**Issue by PastoTreering** [ruffle-rs/ruffle#2242]
https://www.newgrounds.com/projects/games/1573817/preview/filetype/0

The above .swf when emulated via Ruffle has different behavior than Flash Player when:
1. Press and hold the period "." key 

Ruffle result: one red box is drawn, then another shortly thereafter
Flash player result: only one red box is drawn

![ruffledemo](https://user-images.githubusercontent.com/40899110/103494849-60b51480-4ded-11eb-9376-49017ef6033c.gif)

as2 code:
```
var keyListener:Object = new Object();
keyListener.onKeyDown = function() {
	addBox();
};

Key.addListener(keyListener);

var pDown = false;
var cv = 0;

wrap.onEnterFrame = function() {
	if (Key.isDown(190)) {
		if (!pDown) {
			addBox();
			pDown = true;
			cv++;
		}
	}	
	
	if (!Key.isDown(190)) {
		pDown = false;
	}
}

function addBox() {
	var t = this.attachMovie("test", "test" + cv, cv);
	t._x = cv * 30;
}
```

**Comment by Herschel** [comment]
Can't repro this one, two squares are created when holding down . in both the Flash Player and Ruffle (desktop and web).

I think this is caused by not having "Control -> Disable Keyboard Shortcuts" setting enabled in the Flash IDE test player. If you enable is setting, two squares are created.  With this setting disabled, I think the test player's "Step Forward One Frame" shortcut captures the period and steals focus.

**Comment by Herschel** [comment]
Confirmed with Nick, working as intended
