### ISSUE TITLE
Ruffle Error on https://www.pleasurepad.co.uk/

### ISSUE THREAD

**Issue by digitaldexterity** [ruffle-rs/ruffle#2250]
# Error Info
Error name: CompileError
Error message: WebAssembly.Module doesn't parse at byte 0: modules doesn't start with '\0asm'

# Player Info
Allows script access: false

# Page Info
Page URL: https://www.pleasurepad.co.uk/

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-02
Channel: nightly
Built: 2021-01-02T00:44:12.942Z
Commit: 83c32e8693ec7d585713d457599b87b81e2057c3

**Comment by Poopooracoocoo** [comment]
![image](https://user-images.githubusercontent.com/51363864/103644166-0dd48c00-4faa-11eb-9407-6a32540dfabf.png)

The version of Ruffle on that website was updated and now tells you that's it's an issue with how wasm files are served. The site administrator will have to fix it. This error now appears because the version that was there before didn't have the new error.

**Comment by Poopooracoocoo** [comment]
Fixed by site.
