### ISSUE TITLE
Various minor graphical issues

### ISSUE THREAD

**Issue by alexb910** [ruffle-rs/ruffle#24]
In the flash animation _Hyakugojyuuichi!!!_, the opening text renders wrong in Firefox on Windows 10. I've also tested it in Chrome and the desktop player, and it renders as it would in Flash. 

![hyaku2](https://user-images.githubusercontent.com/8029914/63228279-a0f70100-c1be-11e9-8d88-e89001e3f867.png)
Above is how the text is supposed to be rendered, as seen in Chrome.

![hyaku1](https://user-images.githubusercontent.com/8029914/63228285-b1a77700-c1be-11e9-9312-43dc89d6cc46.png)
This is the same text as seen in Firefox.

I've also noticed that in the same animation, gaps appear between sliced images where there were none in Flash. (This happens in both Chrome and Firefox.) Also, some text that's yellow with a black outline in Flash is entirely white in Ruffle.

![hyaku3](https://user-images.githubusercontent.com/8029914/63228361-912bec80-c1bf-11e9-880d-0e6779db38f4.png)

![hyaku4](https://user-images.githubusercontent.com/8029914/63228367-9a1cbe00-c1bf-11e9-9bbb-7829756a61be.png)

**Comment by Herschel** [comment]
Fixed color transforms in Firefox in https://github.com/ruffle-rs/ruffle/commit/fecb981b135f45b98ec54c450bc135f72a030695. Firefox required the feColorMatrix filter to be inside an SVG element. However, while investigating this I noticed that Safari has the same issue because it doesn't support `CanvasRenderingContext2d.filter` at all. I opened #25 for this.

Fixed the scaling in Firefox in https://github.com/ruffle-rs/ruffle/commit/d0413da3817f4c5ac12a9de81391017f44d36c18. Set the `preserveAspectRatio="none"` attribute on generated SVGs to prevent Firefox from fudging with the dimensions.

The seams in the lower images are an unfortunate side effect of the antialiasing of SVG rendering in browsers and will be noticeable in most movies. Flash generates art with mostly no overdraw or overlapping shapes, but SVG renderers expect overlapping shapes in this case and cause ugly seams as shown. I don't think there is any easy way to fix this, and I think it won't matter much we switch to WebGL for rendering.

Thank you for reporting!
