### ISSUE TITLE
Error on https://revision.madrevision.com/bowman2/

### ISSUE THREAD

**Issue by PunkyMark** [ruffle-rs/ruffle#2409]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://revision.madrevision.com/bowman2/

# Browser Info
Useragent: Mozilla/5.0 (X11; CrOS x86_64 13505.73.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.109 Safari/537.36
OS: Linux x86_64

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-08
Channel: nightly
Built: 2021-01-08T00:51:10.664Z
Commit: cb9bdcdfdbc3ca2e5812f176713f7976b62fc28f

**Comment by ogiwon** [comment]
I have the same fetching poblem but it looks differently on my site with big error letter in red screen. Waiting patiantly for any clues :)

**Comment by Futurama39** [comment]
I tried with both Firefox and Chrome on 2021-01-12 and i am unable to reproduce. Site works just fine. Does the error happen any time or do you have to do something to trigger it?

**Comment by Toad06** [comment]
I'm also unable to reproduce using the extension, and there's no selfhosted build on the page.

In case you did use the selfhosted build and removed it because it wasn't working, there are chances that Ruffle wasn't able to load the `.wasm` because of CORS issues (eg. if Ruffle is hosted on `madrevision.com`, it couldn't load on `revision.madrevision.com` without configuring the webserver to allow the CORS requests - https://enable-cors.org/server.html).
