### ISSUE TITLE
Error with ActionScript3

### ISSUE THREAD

**Issue by basiluspp** [ruffle-rs/ruffle#2512]
Hi,

First of all, very nice project !

I'm having trouble with the Chrome Extension related to ActionScript3. Do you have any idea when it'll be supported?

It's for an internal hosted application so unfortunately I can't show you our usage.

Cheers,

![image (5)](https://user-images.githubusercontent.com/77450882/104610139-10a73f00-5684-11eb-9b5d-69b9774f7dcd.png)

**Comment by ousia** [comment]
@basiluspp, many thanks for joining GitHub to report this issue.

I’m only an average user that reports issues from time to time.

As you may have already noticed, #1368 keeps track of AS3 related issues.

That issue doesn’t include a timeline, since tasks will be solved as soon as it is possible for the persons involved in development.

Don’t get me wrong, but everyone here is interested in experienced issues are solved right now.

As you might agree, having all issues fixed will take time and the number of persons involved in development is limited.

If your issues are critical, your organization might consider sponsoring [ruffle-rs](https://github.com/sponsors/ruffle-rs) (or its lead maintainer [Herschel](https://github.com/sponsors/Herschel)).

[Just in case you wonder, I cannot code and I’m not part of @ruffle-rs. I’m only writing this just in case it might help.]

Many thanks for your interest in the project and have fun with _Ruffle_.

**Comment by Poopooracoocoo** [comment]
Closing as per what Pablo said. :)
