### ISSUE TITLE
web: Governor of Poker - Game Pauses all the time

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2514]
Hey,

this is also an AS2 game which could possibly work fine. I always enjoyed the game and played hours over hours. Sadly the game pauses all the time. Maybe you can fix it soon 👍 

https://www.newgrounds.com/portal/view/445178?emulate=flash

**Comment by conradlempert** [comment]
i'm interested as well :)

**Comment by conradlempert** [comment]
I've got it to work (not in the browser though).

1. Download the Flash Player program from Adobe (Win/Mac/Linux):
https://www.adobe.com/support/flashplayer/debug_downloads.html

2. Download the swf for governor of poker:
https://spielen.govofpoker.com/games/governor-of-poker-1.swf

3. Open the swf file in Flash Player.

**Comment by n0samu** [comment]
The problem is related to the code in the game's `as.FocusControl` class. It uses a `focus_mc` MovieClip with an onSetFocus handler, as well as the Selection.setFocus method. These features are not fully implemented yet - see #263, #271, #2789.

It's still possible to play the game in Ruffle - you just need to turn off "Automatic Pause" in the options menu. Getting to the options menu is a bit of a pain - you need to repeatedly click the right spot on the screen quickly enough for it to register between Pause menu popups.

**Comment by Stefannag** [comment]
Indeed, the @n0samu's solution will work, but the game is still not playable. Maybe is just for me, but once in the game scene, I can't get the character do to anything - clicking here - there, but nothing will happen. 

Maybe we will play this in the future! :)

**Comment by n0samu** [comment]
Ah, you're right. That's too bad!
