### ISSUE TITLE
tequila zumbi 2

### ISSUE THREAD

**Issue by Lucianoferreirajunior12** [ruffle-rs/ruffle#2549]
não funciona esse jogo !!!

**Comment by manokara** [comment]
Luciano, pelo visto o Ruffle foi mal configurado no Click Jogos. Todos os jogos Flash estão dando este erro, eles que tem que resolver por lá.

-----

Link: https://www.clickjogos.com.br/jogos/tequila-zombies-2

Game is AS3, but that's not the problem. There has been quite a few reports from this brazilian website and all of the Flash games there are giving MIME errors (at least from what I've tested so far), probably because they didn't [follow this](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configure-wasm-mime-type).

**Comment by Toad06** [comment]
This was an issue on Clickjogos's end - now fixed.
