### ISSUE TITLE
Error on Xeno Tactic 2 on jeu.cc

### ISSUE THREAD

**Issue by Shweetz** [ruffle-rs/ruffle#2575]
I tried to play Xeno Tactic 2 in-browser here: https://jeu.cc/xeno-tactic-2
Game loads and seems fine but enemies take no damage so it's pretty sad
Also the ad button "link open in a new window" in the top left doesn't open anything

EDIT: Also tried after downloading "Nightly 2021-01-16" and running on my computer but it's the same

**Comment by n0samu** [comment]
Direct SWF URL: http://jeu.cc/components/flash/xenotactic2v32MICRO.swf

Towers lock onto enemies correctly at first, but don't seem to register when enemies are destroyed and keep trying to fire at them, instead of targeting new enemies.

This error is shown over and over in the terminal: 
`WARN  ruffle_core::avm1::globals::movie_clip] MovieClip.localToGlobal: Missing point parameter`

Seems like basically the same issue as #5711. And strangely, it's the same error as #7667, which was already fixed. Not sure what's up with that.
