### ISSUE TITLE
Error on file:///C:/Users/carduel/OneDrive/Work/Sesulka/droje/republika4.html

### ISSUE THREAD

**Issue by Carduel** [ruffle-rs/ruffle#2619]
[republika4.zip](https://github.com/ruffle-rs/ruffle/files/5831154/republika4.zip)

# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at e (file:///C:/Users/carduel/OneDrive/Work/ruffle/ruffle.js:1:31896)
    at i (file:///C:/Users/carduel/OneDrive/Work/ruffle/ruffle.js:1:33923)
    at i.next (<anonymous>)
    at a (file:///C:/Users/carduel/OneDrive/Work/ruffle/ruffle.js:1:34005)
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: republika4.swf
Param movie: republika4.swf
Param quality: high
Param bgcolor: #ffffff
Param play: true
Param loop: true
Param wmode: window
Param scale: showall
Param menu: true
Param devicefont: false
Param allowScriptAccess: sameDomain
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined
Attribute 4: undefined

# Page Info
Page URL: file:///C:/Users/carduel/OneDrive/Work/Sesulka/droje/republika4.html

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-17
Channel: nightly
Built: 2021-01-17T01:05:59.152Z
Commit: c2b768c453f281a988c71a829e7a71bb106302fa

**Comment by evilpie** [comment]
So what you are trying to do is not going to work because file: URLs can not fetch other resources. This includes the ruffle.wasm file:
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///home/tom/Desktop/testing/ruffle/ruffle_nightly_2021_01_17_selfhosted/43f8e1e34e0629f740121b10aab750da.wasm.

You can try using a local HTTP server. The blog post [Restrictions on File Urls](https://textslashplain.com/2019/10/09/navigating-to-file-urls/) explains this problem in detail.

**Comment by Herschel** [comment]
Ruffle will not run from a local filesystem due to security restrictions in browsers. You can [run a local test server](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server) or upload Ruffle to a server. Better error messages for this are coming in #2622. Hope this helps.
