### ISSUE TITLE
can't open http://tv.haoqu99.com/4/fhzw.html

### ISSUE THREAD

**Issue by xiantong666** [ruffle-rs/ruffle#2648]
can't open http://tv.haoqu99.com/4/fhzw.html

**Comment by Toad06** [comment]
`tv.haoqu99.com` tries to load the SWF file from `hq.ioioz.com`, which doesn't work due to security restrictions of modern web browsers. Ruffle cannot bypass this unlike the official Flash Player, so it's up to the website owner to either host the file on the same domain or create a CORS configuration ([enable-cors.org](https://enable-cors.org/index.html)).
