### ISSUE TITLE
http://superflashmariobros.czxzyyyk.de no error, just freezes

### ISSUE THREAD

**Issue by br4nnigan** [ruffle-rs/ruffle#2811]
using Firefox plugin, Browser (Waterfox classic) freezes

**Comment by Poopooracoocoo** [comment]
How is it on another browser? :)

**Comment by br4nnigan** [comment]
:P

In Chromium it kinda works, fails in a different way. First off I get the warning that this is AS3. But it fails in the same way as the official Flash player.

The swf loads and shows the start screen, but back then when I made this, you could just hit space (maybe after focusing the embed) as was defined in the script to start the game. With the official player you have to right click "play" now for some reason but then you can play the game. But since Ruffle does not have that option in the right click menu I'm stuck.

But I get it, my browser sucks.

**Comment by n0samu** [comment]
Waterfox Classic is not supported by Ruffle. More interestingly though, in a supported browser the game works fine until it gets stuck here:
![image](https://user-images.githubusercontent.com/71368227/197422180-1cf4f6a8-ccff-4a33-ad7f-0b61cd009c33.png)

If the main SWF file is loaded directly (instead of going through the loader), you can right-click => Play to start the game, just like if you load the main SWF in Flash Player. But there are some collision problems:
- Mario always dies from touching the enemy at the start, even if jumping directly on top of it.
- Mario can sometimes walk in midair (??)
![image](https://user-images.githubusercontent.com/71368227/197422510-a09d0377-e23c-4598-bc22-d037ab1935a5.png)
- Mario can get stuck inside of blocks.
![image](https://user-images.githubusercontent.com/71368227/197422555-d01fb23a-97b4-4a86-ab78-98644a1af81c.png)

**Comment by br4nnigan** [comment]
well apparently I missed that Ruffle only supports ActionScript2 or at this point 25% of the AS3 API which is probably why the game is stuck at that point or the collision problems exist (which tbh might just be bad programming, this game was my very first project, although jumping on the enemy always worked!). Thanks for checking it out though
