### ISSUE TITLE
web: Epic City Builder - Stops after intro

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#2820]
Hello,

one of the first games I sponsored a long time ago. It seems to be written in AS2 but it doesn't get past the loader. Maybe you can help out :)

https://www.spiele-umsonst.de/epic-city-builder-t1836.html

**Comment by Herschel** [comment]
There is white "Hier Klicken" text at the end of the "Spiele Unmost" video that has a drop shadow filter. Drop shadows are unimplemented currently, so it's invisible because of being white-on-white. The button still functions and the game seems to function.

Closing in favor of the filter effects issue, #15.
