### ISSUE TITLE
https://www.maxgames.com/play/frontline-defense.html white screen

### ISSUE THREAD

**Issue by sungruhyun** [ruffle-rs/ruffle#2874]

**Comment by Toad06** [comment]
`www.maxgames.com` tries to load the SWF file from `farm.maxgames.com`, which doesn't work due to security restrictions of modern web browsers. Unlike the official Flash Player, Ruffle cannot bypass this, so it's up to the website owner to either host the file on the same domain or properly configure the web server to allow the CORS requests (https://enable-cors.org/server.html).
