### ISSUE TITLE
Ruffle Flashplayer Emulator Firefox Rejected

### ISSUE THREAD

**Issue by SBCounty79** [ruffle-rs/ruffle#2911]
I am unable to find the extension any longer on Mazilla available apps.  When I download the extension from Ruffle FireFox rejects it saying it has not been verified.

**Comment by torokati44** [comment]
Please follow the instructions on the [Usage page](https://ruffle.rs/#usage) precisely:
![image](https://user-images.githubusercontent.com/288816/106061188-5688ec00-60f5-11eb-8332-98f2974d0536.png)

And in regular Firefox, it is uninstalled every time the browser is closed, because it is not yet "signed".

**Comment by SBCounty79** [comment]
Made it in and the video attempted to play.  This is the error and I filed an error report with GitHub.

**Comment by SBCounty79** [comment]
Figured out how to load in Chrome and had a similar error.  Filed error report.  Thank you so much for your help.  Still no luck.  Trying for finish a class.

**Comment by ousia** [comment]
Adding Ruffle to https://addons.mozilla.org (or AMO) would be great, as https://github.com/ruffle-rs/ruffle/issues/1876#issuecomment-741505119 suggested.

For many users, the current method with Firefox is cumbersome or too complex (I must confess that I haven’t made it work.)

For animations known to work, I can recommend friends to use Firefox, but not to install a developer version of Firefox to install an extension.

Could it be considered adding Ruffle to AMO?

Many thanks for your help.

**Comment by SBCounty79** [comment]
That’s why I tried it in Chrome also and had a similar error.  There again it is not in the Google store either.  Is Ruffle considered to more for animation not videos?  There are percentages on the Ruffle page is that the percent that it works on?  I’m no expert but I was able to find my through the install, not so bad to do.  What is also interesting is I did get it off of the M

**Comment by ModernKit** [comment]
Don't mean to self-promote, since we're also users of Ruffle, but we've created an extension which uses Ruffle emulator under the hood: https://addons.mozilla.org/en-US/firefox/addon/flash-player-emulator/

It's probably easier to install than the developer mode method and periodically updates with new Ruffle versions via AMO.

**Comment by SBCounty79** [comment]
That’s the one!!!!!  We will try again.  It tried to work.  I was wondering if Adobe was blocking flash files from playing.

**Comment by SBCounty79** [comment]
?I got it to work to work in Chrome.  We'll see if it works tomorrow when we try to finish the class!!!  Thank you so much for all the help!!!!  Thought you might want to know that it worked.

________________________________
