### ISSUE TITLE
Problem loading https://ruffle.rs/demo/

### ISSUE THREAD

**Issue by jmc92** [ruffle-rs/ruffle#2972]
When I try to load your demo page here > https://ruffle.rs/demo/ I get a black page, and the small popup that says "A web page is slowing down your browser, what would you like to do? with the options to either stop it or wait.

**Comment by jmc92** [comment]
Note: I haven't even tried running a flash file, since I cannot even get to that point.

**Comment by Poopooracoocoo** [comment]
Which version of Firefox are you using and on which platform?

**Comment by Herschel** [comment]
The demo page automatically loads a sample SWF when you visit it. If you press "Wait", does a file eventually play?

**Comment by jmc92** [comment]
I'm using Waterfox, which is essentially firefox. And I tried disabling all addons/running it in safe mode. I went to the ruffle demo and got the same problem. If I wait, nothing happens. If I wait a few minutes, and then tell the page to stop, part of the blue banner for the ruffle demo finally shows. If I have the ruffle addon enabled, and I do not tell it to stop, eventually all my other tabs start to go black as well.

I don't have this problem when I try it on an old version of Chrome I have.

**Comment by sunlightspectre** [comment]
Hello there, @jmc92 ! I have a similar issue, and had filed an open thread, which I closed; at this moment, Ruffle doesn't play too nice with Waterfox, at least classic! I'm currently trying to isolate why that is, so that it can be addressed. I think it might be possible to correct using polyfill, as it seems to be features missing from classic present in modern chromium browsers. 

Just to clarify, the pages hang, you get a script stop message, and it'll be like...

"A script is causing your browser to slow down; flash/flashtest/etc :3"?

**Comment by Herschel** [comment]
We don't officially support Waterfox. Closing in favor of #2568.
