### ISSUE TITLE
Synj vs Horrid - Movieclip discrepancy

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#30]
If you watch the Swivel'd version of Synj vs Horrid, at the 1:09 mark you see Synj running through the jungle. His post is static but his body shakes violently as it tweens across the screen.

https://www.newgrounds.com/portal/view/79158

In Ruffle, Synj's body tweens across the screen but isn't shaking. Something about that shaking body movieclip may be unusual.

**Comment by Herschel** [comment]
This animation is inside a 1-frame movie clip, which Ruffle currently handles incorrectly:

a) 1-frame clips in Flash are auto-stopped and do not run at all.
b) When a timeline rewinds because of a loop or goto, clips that are still on the timeline are incorrectly destroyed and recreated.

Fixing these will solve this issue. I consider making test cases for these frame/action sequencing issues part of #16.

**Comment by Herschel** [comment]
This particular case is fixed in 7b6a3d525a532ccc3169a6ee1fd80d363a4df279. Also added a test for it.

Rewinding gotos still need to be fixed properly -- see #33.
