### ISSUE TITLE
Clicking on 'more info' button in AS3 warning fails to open GitHub 

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle#3079]
**Describe the bug**
![image](https://user-images.githubusercontent.com/51363864/106888870-47c8b780-673b-11eb-8d6c-0c61c9ed1d9d.png)
![image](https://user-images.githubusercontent.com/51363864/106888888-4dbe9880-673b-11eb-8ef8-5c9a92fd318b.png)

https://www.newgrounds.com/portal/view/540919?emulate=flash

**Expected behavior**
GitHub page would open properly.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Self-hosted
**What platform are you using?**
Ruffle version 2021-02-03. Chrome 88 on Windows 10 with Intel integrated graphics.

**Comment by C-Listensprechen** [comment]
Github wouldn't work for me either, and it was for a Ruffle bug report...and I expect it's because Github REQUIRES that you register for an account first, and that's what I had to do to report the bug report bug. If Ruffle could see clear to accept non-Github bug reports, it would get more of them I'm sure.
