### ISSUE TITLE
[Web] Sounds keep playing when switching tabs

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#347]
Hello,

Flash games keep running in the background when switching browser's tabs, but this is not the case with Ruffle (and HTML5). I think pausing / resuming sounds when switching would help preventing issues (game used: https://www.newgrounds.com/portal/view/225944/ )

A big thank you for your great efforts in preserving the Web's history.

**Comment by ExplodingWaffle** [comment]
Just encountered this issue watching the [sbemails](https://archive.org/details/Strong_Bad_Email_142_Secret_Identity) on internet archive- the audio continues when unfocused but the animation is paused.
That said- should the expected behaviour here be pausing the audio when switching tabs or continuing the animation? I personally would much prefer the latter.

**Comment by Herschel** [comment]
In the general the modern web does not like to run things when the tab is invisible, so we are the mercy of the browser here. I think we will have to pause the app completely by detecting changes with the visibility API (https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API). 

Perhaps we can add a setting for the his behavior, but I worry what might happen if we alter the audio backend as well (using ScriptProcessor or AudioWorklet instead of pure WebAudio API).

This may actually work fine if we move some of the player inside a web Worker (#1338), it's worth some investigation.

**Comment by Toad06** [comment]
FWIW I just realized that in iPadOS 14, switching to another tab pauses audio. I really don't think this was happening in iPadOS 13 and earlier.

**Comment by Herschel** [comment]
This is a good first issue if a newer contributor wants to tackle it. The player could be paused and resumed using the JS [Page Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API).

**Comment by Couchy** [comment]
[IntersectionObserver](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) could also be useful for checking player visibility on the page.

**Comment by TheAlienDrew** [comment]
Wouldn't it just be a better idea to just skip all the frames while the page is invisible?

**Comment by Herschel** [comment]
The issue is that modern browsers do not like to run when the page is not visible, so we are at the mercy of the browser. Ruffle is not executing at all in this case, so it can't skip frames.

Possibly this can be done as we switch over to web workers, but I suspect this will be problematic on e.g. Safari which has no AudioWorklet.

**Comment by HtheB** [comment]
I made a simple Tempermonkey script to prevent Ruffle from pausing.
https://github.com/HtheB/ruffle-keep-alive

Enjoy!

**Comment by Couchy** [comment]
> For people who still wants Ruffle to continue working when the browser tab is unfocused; I made a simple Tempermonkey script to prevent Ruffle from pausing. https://github.com/HtheB/ruffle-keep-alive
> 
> Enjoy!

Doesn't that just reintroduce the original issue of audio and animation getting out of sync when the tab is in the background?

**Comment by HtheB** [comment]
> > For people who still wants Ruffle to continue working when the browser tab is unfocused; I made a simple Tempermonkey script to prevent Ruffle from pausing. https://github.com/HtheB/ruffle-keep-alive
> > Enjoy!
> 
> Doesn't that just reintroduce the original issue of audio and animation getting out of sync when the tab is in the background? Also, your script nukes the visibility and focus APIs on every webpage, not just for Ruffle. That's likely to create a lot of side effects.

I haven't experienced issues regarding this.
However, you can also pause the script if it actually does for a particular flash file.
