### ISSUE TITLE
Remove report bug button on panic screens due to invalid .wasm instantiation

### ISSUE THREAD

**Issue by Poopooracoocoo** [ruffle-rs/ruffle#3679]
http://www.juegosjuegos.com/embed/papas-pancakeria (Ruffle nightly 2021-02-02, Chrome 89, Windows 10)
![image](https://user-images.githubusercontent.com/51363864/111241299-f3c1c480-8650-11eb-93b7-99d30d83ae46.png)
heaps of people seem to think that the report bug button will report the bug to the site. 

consider renaming the button to "Report bug to Ruffle" or removing it. 

it'd also be worth changing up the wording to explain that this is not ruffle's fault.

**Comment by EmperorBale** [comment]
Maybe linking to some type of help page would be better. There could be a page on the ruffle website that shows all the common issues, with solutions to fix them

**Comment by Poopooracoocoo** [comment]
or a wiki page. 

the panic screen due to cors issues where there .wasm file couldn't be found has a link to the wiki iirc

**Comment by Herschel** [comment]
This is a good first issue for a new contributor:
Catch `CompileError`s from WebAssembly.instantiate/instantiateStreaming, and show an error message without the crash report button.

The error message could link to a wiki page describing common issues, such as if the wasm file is uploaded in ASCII mode instead of BINARY from an FTP client.
