### ISSUE TITLE
V-Cam visible / not working

### ISSUE THREAD

**Issue by TomFulp** [ruffle-rs/ruffle#368]
I've been keeping a list of entries that don't work and what appears to be broken. I thought sharing the V-Cam portion as it's own ticket might be helpful. The following movies have broken V-Cam (not sure which are AS2 or AS3):

https://www.newgrounds.com/portal/view/526607
https://www.newgrounds.com/portal/view/529760
https://www.newgrounds.com/portal/view/535948
https://www.newgrounds.com/portal/view/544549
https://www.newgrounds.com/portal/view/552384
https://www.newgrounds.com/portal/view/558931
https://www.newgrounds.com/portal/view/568753
https://www.newgrounds.com/portal/view/567786
https://www.newgrounds.com/portal/view/587853
https://www.newgrounds.com/portal/view/590741
https://www.newgrounds.com/portal/view/590465
https://www.newgrounds.com/portal/view/590330
https://www.newgrounds.com/portal/view/570414
https://www.newgrounds.com/portal/view/583752
https://www.newgrounds.com/portal/view/594471
https://www.newgrounds.com/portal/view/598916
https://www.newgrounds.com/portal/view/603347
https://www.newgrounds.com/portal/view/589225

**Comment by Herschel** [comment]
Looks like most of these are AS3.

**Comment by Spikestuff** [comment]
I only watched and compared [Harvesting (AS3)](https://www.newgrounds.com/portal/view/526607?emulate=flash) and [Kratos Tragedy (AS3)](https://www.newgrounds.com/portal/view/529760?emulate=flash) both appear to be working compared to standalone flash and it might continue onward through the rest, because of the amount and time I only checked the first two.

What's not working (which occurs in Harvesting) is anything related to depth of field / blurring and some effects (like the laser not showing blue edging) as blend modes and filter effects aren't implemented yet for AS3 titles.

**Comment by Lord-McSweeney** [comment]
All the files seem to be more or less working now.
