### ISSUE TITLE
Fishy - non-player fish not appearing

### ISSUE THREAD

**Issue by adrian17** [ruffle-rs/ruffle#380]
https://www.newgrounds.com/portal/view/81219

While there are other issues happening (related to case-insensitive properties), I'm quite sure that the non-player fish _should_ appear - since after a couple seconds, the player dies by colliding with another fish, and the game logic for checking fish's collision with the player seems to be working correctly. So the fish the player is colliding with _is_ there, but it's not visible for some reason.

**Comment by Herschel** [comment]
Two issues:

1) If properties are not defined on the object passed to `Color.setColorTransform`, they should take on default values. Currently they get coerced to 0 so the enemies are created with 0% alpha. Ruffle should check if the properties exist before using them.

2) A mistake in the game's code causes enemy `_xscale` to be set to undefined for certain fish. This has no effect in Flash, and usually Ruffle handles this correctly because undefined gets coerced to `NaN` and Ruffle checks for `is_nan`. But this is an v6 SWF which coerces undefined to 0, so _xscale gets set to 0. Ruffle should bail out if the original value is undefined.
