### ISSUE TITLE
Web target does not work on Firefox Mobile

### ISSUE THREAD

**Issue by ousia** [ruffle-rs/ruffle#385]
I’m afraid I cannot get http://ruffle-rs.s3-website-us-west-1.amazonaws.com/builds/web-demo/index.html?file=synj1.swf working either on _Android_ phone or on an _iPhone_.

I could run it some months ago, although I checked that on _Android_ only.

Is this issue known to other users or developers?

(Sorry for the too vague report 😥.)

**Comment by barisyild** [comment]
Working on Xperia XZ1.

**Comment by Herschel** [comment]
Working here as well on Pixel 3 XL, Android 10, Chrome 80.0.3987.99. (Any iOS users want to test?)

Could you provide some more info about your devices (what model, OS, browser, etc.?)

**Comment by Toad06** [comment]
I give some feedbacks too if that can help:

Tested on Android Phone (Huawei P9 Lite):
- Chrome: Works fine. There's just a message "This plugin is not compatible" that briefly appears when the page loads, before vanishing.
- Firefox: Does not work. It gets stuck on "Click to play".

Also tested on iPad Air 2 and it works fine.

**Comment by ousia** [comment]
> * Firefox: Does not work. It gets stuck on "Click to play".

I’m also using Firefox and I’m experiencing the same issue.

**Comment by Herschel** [comment]
Can confirm it doesn't work in Firefox 68.5.0 mobile on Android. Thanks!

**Comment by ousia** [comment]
I wonder whether the same issue is happening with Safari.

**Comment by Junky228** [comment]
I clicked that link using Firefox Preview on a 2016Pixel running Android 10.  Seems to be working fine, I don't have the regular version of firefox to test.  Works just fine, that wacky animated video plays with music and whatnot on the nightly build of Preview as well.-> Preview 3.2.1 (Build #20250350)
28.0.3, f0dc2cadd
GV: 73.0-20200123172213

And the Nightly version->   Nightly 200220 06:01 (Build #20510608)
34.0.0, 2ca8632b8
GV: 75.0a1-20200219095352

**Comment by Herschel** [comment]
Sorry for the delay on this one, as the Firefox mobile apps seems to be a very odd state. Confusingly on the Google Play Store there is "Firefox Mobile" 68.0, which is the current "stable" version, there is a "Firefox Mobile Beta", which must be the beta build of the aforementioned, and "Firefox Preview" 4.1.0 which contains the latest mobile browser. It seems that Firefox Mobile will be sunsetted/replaced with Firefox Preview in the future.

It took me some effort to get remote debugging working (remote debugging Firefox Desktop to Firefox Mobile does not work, you must use Firefox Preview). Ruffle does not work on Firefox Mobile because `PointerEvent` is not enabled by default on Firefox Mobile(?!). I'd have to switch to MouseEvents on Firefox Mobile for Ruffle to function.

Ruffle works as intended on Firefox Preview. Since this will be the default Firefox browser on mobile sometime soon, I think this bug is a wontfix.

If you are still having issues on iOS, please file a separate bug. Thank you!

**Comment by ousia** [comment]
@Herschel,

many thanks for your explanation. It seems reasonable to me.

In that case, the proper thing to do is to close the issue (which I’m doing now).

Many thanks for your help.
