### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by danuvita** [ruffle-rs/ruffle#4059]
Apparently, there's trouble loading a chunk

**Comment by torokati44** [comment]
Please provide more details.

**Comment by torokati44** [comment]
Most likely the same issue as these: https://github.com/ruffle-rs/ruffle/issues/2567 https://github.com/ruffle-rs/ruffle/issues/3456 https://github.com/ruffle-rs/ruffle/issues/3284 https://github.com/ruffle-rs/ruffle/issues/2463
And if so, it's caused by how Ruffle is deployed on the site you were visiting.

**Comment by relrelb** [comment]
Closing due to lack of information.
