### ISSUE TITLE
Browser extension inserts JavaScript into XML documents

### ISSUE THREAD

**Issue by StevenNL2000** [ruffle-rs/ruffle#4090]
**Describe the bug**
To support Flash everywhere, the Ruffle browser extension inserts a small amount of JavaScript into every visited page. Unfortunately, it appears that this does not only apply to HTML documents, but also to XML documents.

1. Install the Firefox extension (Chrome is also affected, but see below).
2. Navigate to any web page that serves XML with `Content-Type: text/xml`, for example: https://video.google.com/timedtext?v=jNQXAC9IVRw&lang=en.
3. Observe that the page is modified by Ruffle's inserted JavaScript.

**Expected behavior**
Ruffle should not insert JavaScript into XML documents.

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Browser extension.

**What platform are you using?**
This issue affects both Chrome and Firefox. However, the issue is sometimes not visible in Chrome because they handle raw XML files differently than Firefox.

**Comment by adrian17** [comment]
Looks like regression in 2021-04-12 build, probably caused by https://github.com/ruffle-rs/ruffle/pull/3635 or related PRs. Pinging @relrelb

**Comment by relrelb** [comment]
Unfortunately this is not a regression, as it happens to me at least with the 2021-01-12 release. It does make sense though, because the script injection logic never accounted for such a case.

**Comment by adrian17** [comment]
That's weird, I'm not getting this with 2021-04-11 .xpi.

**Comment by relrelb** [comment]
It might need a few reloads before happening.

**Comment by StevenNL2000** [comment]
@relrelb Your fix doesn't work in Firefox (tested with 2021-04-24). They don't support `document.xmlVersion`:
https://developer.mozilla.org/en-US/docs/Web/API/Document/xmlVersion

**Comment by adrian17** [comment]
For the record, I'm still not reproducing with versions before 2021-04-12. Video:

https://user-images.githubusercontent.com/4729533/115952077-6c376300-a4e4-11eb-9430-2effdb4e6321.mp4

**Comment by relrelb** [comment]
@adrian17 Thanks for pointing this out!

After some investigations, it seems that #3635 is the cause as you suspected. But I still wouldn't call it a regression:
Before #3635 the plugin polyfill script was injected by creating a `script` element, populating it using `innerHTML`, and appending it to the document.
#3635 changed this behavior slightly by using `textContent` instead of `innerHTML`.
The difference is that `innerHTML` throws an exception in XML documents (you can see `XML Parsing Error: not well-formed` in the console), while `textContent` does not.
This exception isn't thrown on Chrome, so it explains why the bug happens with 2021-04-11 on Chrome.
So #3635 didn't "regress" this bug, but rather revealed it on Firefox.

Apart from that, #4092 doesn't work on Firefox because it removed `document.xmlVersion` long time ago. A proper method to detect XML documents is described in [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/xmlVersion).
