### ISSUE TITLE
Ruffle extension overrides previous versions

### ISSUE THREAD

**Issue by gamer191** [ruffle-rs/ruffle#4150]
When using Ruffle on Firefox for windows (Version 88.0), the extension version takes priority over the version on the website. (For example: https://www.coolmathgames.com/0-full-moon uses self-hosted ruffle nightly 2021-02-11, which can be revealed by right-clicking on the game, however if ruffle browser extension version 2021-04-27 is installed on the web browser, it will show that version when right-clicking). This means that if the website owner has tested that the game is compatible with a specific version of ruffle and not future versions (not sure if that's possible but I assume so since it's an alpha) then installing the ruffle extension will break those games.

**Comment by torokati44** [comment]
For these cases, the website owner can add a `data-ruffle-optout` attribute to the `html` tag of the page, and the extension won't do anything - unless its override option is enabled, which by default isn't.

**Comment by gamer191** [comment]
Okay, thanks for clarifying

**Comment by gamer191** [comment]
Wouldn't it make more sense for Ruffle's default behavior to be not to fix what's not broken? (ie: the Ruffle extension only loads on websites that don't self-host a version of Ruffle)?

**Comment by danielhjacobs** [comment]
I wouldn't call this fixing "what's not broken". By default, when Ruffle is being used more than once (for example, through the self-hosted version and the extension), the most recent version of Ruffle takes priority. This can fix issues, since Ruffle receives near daily updates since it is still in active development. For example: https://github.com/ruffle-rs/ruffle/issues/4001. This is a description of an issue that was fixed on February 27, so would be broken with that self-hosted version but not with the extension.

**Comment by danielhjacobs** [comment]
As for your earlier point, since this is in alpha, you are correct that something could break after a new version releases, but these sorts of regresssions tend to be noticed and fixed fairly quickly, and from looking through issues on GitHub (reports of games with outdated self-hosted versions being broken with errors that have since been fixed), it's far more common that the website maintainer didn't notice something was broken with the old release, but the new release fixes it.

**Comment by gamer191** [comment]
Thank you for taking the time to explain that. As I agree with you and strongly doubt anyone will disagree I will closing this issue now :) If anyone does disagree, feel free to reopen this issue.
