### ISSUE TITLE
Sprite Init actions are ran too late

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#418]
This is another one caught whilst trying to get MX controls working. They rely on sprite init actions running in order, as earlier actions will change how later sprites are initialized (most notably with `registerClass`).

Right now we queue up all of the actions and run them at the end of the frame, but I think we need to run all inits immediately before the next `PlaceObject` can run.

**Comment by Herschel** [comment]
We need to pass around `avm` into the various run frame functions (implemented in #344) because there are other cases where things need to run immediately (`unload` clip event, immediately before the clip gets removed, for example). Only frame actions should be queued -- probably any clip event or method handler should be run immediately.

**Comment by Dinnerbone** [comment]
I had a quick attempt at just running, not queuing, but quickly ran into double-borrow issues when things were being placed as a result of an action. It's a change for someone a little more confident in that code than myself :D
