### ISSUE TITLE
Jacksmith Bug

### ISSUE THREAD

**Issue by RexPaster** [ruffle-rs/ruffle#4318]
**Describe the bug**
Provide a clear and concise description of what the bug is. If there are steps to reproduce, list them here.
If this is an issue with a specific SWF file, please provide a link to the SWF file, or you can attach the SWF by zipping it and dragging it onto the issue box.
If this is a visual issue, please attach a screenshot of the problem.

**Expected behavior**

**Is the problem with the Ruffle desktop app, extension, or self-hosted version?**

**What platform are you using?**
 - If you're using the desktop version, please list the OS you are using.
 - If you're using the web version, please list the OS, browser, and mobile device (if applicable).

Jacksmith on cool math games does not work.

**Comment by RexPaster** [comment]
I am using the web version

**Comment by danielhjacobs** [comment]
https://www.coolmathgames.com/sites/default/files/games/jacksmith.swf runs using AS3. See #1368. That's why coolmathgames doesn't even bother to try to load it on https://www.coolmathgames.com/0-jacksmith. Currently, the first error it seems to run into is that flash.text.Font is unimplemented, but there are likely other problems as well.

That's why Ruffle warns you "This content is not yet supported by the Ruffle emulator and will likely not run as intended."

**Comment by RexPaster** [comment]
Any idea when ruffle will work on jacksmith?

**Comment by danielhjacobs** [comment]
See #1368. Support is in active development, but there is still a lot of work to be done, and it will likely take several months yet.

**Comment by n0samu** [comment]
Jacksmith is working now!
