### ISSUE TITLE
The aspect ratio is adjusted incorrectly in certain games.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#4400]
## Describe the bug

![image](https://user-images.githubusercontent.com/75052171/119246681-6f467180-bbbe-11eb-9813-7537fdeec096.png)

The game I've checked is Megaman vs Metroid.
Based on the 2021-04-01 build, it appears on the screen at a normal rate,
In the 2021-05-01 or after build (this is the build I checked, and I don't know exactly when the problem occurred), I could see that the actual viewable area is displayed at a smaller percentage than the display area, as shown in the photo on the right.

[megaman-vs-metroid.zip](https://github.com/ruffle-rs/ruffle/files/6527457/megaman-vs-metroid.zip)

Update: It also happened in the'Crazy Chess' game.

![image](https://user-images.githubusercontent.com/75052171/119246941-c2b9bf00-bbc0-11eb-9f30-467d561ad745.png)

## Expected behavior
Ruffle should be displayed in the correct proportions from that flash to the visible area.

## Is the problem with the Ruffle desktop app, extension, or self-hosted version?
Tested on self-hosted.

## What platform are you using?
 - OS: Windows 10 20H2 x64
 - Browser: Chrome Latest
 - Ruffle: 2021-05-23 Nightly

**Comment by Toad06** [comment]
Thanks for the report.

This is not a bug as this is exactly how the official Flash Player renders the game. This was incorrect in the older releases of Ruffle because `Stage.scaleMode` wasn't implemented.

Now I agree that the previous rendering looks better. Normally you would use the `letterbox` option (https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#list-of-options) but this currently doesn't work when a game uses `Stage.scaleMode = "noscale"` (which  "Megaman vs Metroid" does).

Ties into #5186.
