### ISSUE TITLE
Issues with text encoding?

### ISSUE THREAD

**Issue by yurivanmidden** [ruffle-rs/ruffle#451]
I have several .swfs where I encounter issues with displaying of text fields. Several characters are dropped and strings run out of a field's bounds.

I suspect the issue of dropped characters has something to do with the encoding of the compiled file (eg. UTF16-LE vs UTF8).

For example ...

![image](https://user-images.githubusercontent.com/6409975/76868091-b3c1d900-6866-11ea-99a1-a7a6bf9dbbcc.png)

should be ...

![image](https://user-images.githubusercontent.com/6409975/76868027-9ee54580-6866-11ea-8e0b-cea1dcba50a1.png)

Anyone have an idea? :smiley:

**Comment by Herschel** [comment]
Would you be able to share an FLA/SWF displaying the issue? Possibly this is a problem with Ruffle not finding certain embedded glyphs (it looks like capital letters), or perhaps some of the HTML stripping code is incorrect (we don't support the HTML quite yet!)

**Comment by yurivanmidden** [comment]
[bi_1_060.zip](https://github.com/ruffle-rs/ruffle/files/4346041/bi_1_060.zip)

Hereby that compiled .swf and the original .fla for the particular animation above.

**Comment by Herschel** [comment]
Ruffle was incorrectly using the embedded font, which only had a few glyphs embedded, so any missing glyph would not render.

Instead, the text fields are flagged to use device fonts, and now Ruffle obeys this flag. (This does mean the font will be different because of how we do device font rendering currently).

Thanks for the report!
