### ISSUE TITLE
Obfuscated SWFs may have out-of-bounds jumps in AVM1

### ISSUE THREAD

**Issue by chrisballinger** [ruffle-rs/ruffle#458]
Glad to see people are working on preserving the SWF internet history. Was curious if the original Pandemic 2 flash game worked. It shows the loading screen but then gets stuck at 100% and the JS console shows a ton of `Unknown AVM1 opcode: Unknown {opcode: 3, data: [] }` messages.

You can find the original SWF file here: https://www.crazymonkeygames.com/swf-nr2kjn-jekb/pandemic2.swf

https://www.crazymonkeygames.com/Pandemic-2.html

Cheers!

**Comment by ROBERT-MCDOWELL** [comment]
does not seem to work even with Flash (black screen)

**Comment by Herschel** [comment]
One issue was that the operands of the modulo op (%) were backwards... oops!

This SWF is run through an obfuscater that adds out-of-bounds jumps to the bytecode. Flash Player allows these out-of-bounds jumps, and the jump hops out of the DoAction tag and into custom tags added by the obfuscator (tag type = 253) that contain more code. We'll have to refactor some of the AVM code to allow it to index outside the bounds of the slice (it acts more like a cursor over the whole SWF data, than a slice of the action data).

**Comment by chrisballinger** [comment]
@Herschel Wow, awesome, thanks for taking a look! I wish I had enough underlying knowledge to contribute a patch, but Flash internals are pretty far outside my area of expertise. I'm glad you were able to get to the bottom of the issue so quickly!

**Comment by relrelb** [comment]
Isn't this solved by #1608?

**Comment by Aaron1011** [comment]
Currently, all of the structs in `swf::types` store bytecode inline as a `Vec<u8>` (e.g. `Tag::DoInitAction.action_data` and `ClipAction.action_data`. However, we need to know the offset of the action data within the entire SWF file, so that we can correct implement negative out-of-bounds jumps.

If the `swf` crate is only intended to support Ruffle, then we could start storing indices into the SWF file, instead of `Vec<u8>`. However, if the `swf` crate is supposed to be usable as a standalone crate, then having a `Vec<u8>` available would make it much more convenient for clients who don't need to care about negative out-of-bounds jumps.
