### ISSUE TITLE
Can't run the ruffle on Linux Server

### ISSUE THREAD

**Issue by lordwars** [ruffle-rs/ruffle#491]
I have a big website of flash games who get flash games from another websites (by embed / iframe) and show them in my web.
when I run it:
![1](https://user-images.githubusercontent.com/13945210/78650589-cf4d5c00-78c7-11ea-92bc-8db3775e3079.png)
![2](https://user-images.githubusercontent.com/13945210/78650592-d1171f80-78c7-11ea-9000-a9ebe7facae5.png)
Its show my these errors^

I install the packages in dir: games/ruffle
and run the "embeds" from games/ruffle/www/index.php

**Comment by mdonoughe** [comment]
I think you need to either download the nightly build or build the source.

**Comment by lordwars** [comment]
I dont really know to use this. Its my first time I used a plugin like this
in linux with SSH.
How I build the source? (what is it mean?)
I see the nightly build, if I want to run this on domain like:
www.games.domain.co.il where I need to put the files? in the main folder?
without folder?

sorry for all of the questions but I am really need this.
Thanks!

‫בתאריך יום ה׳, 9 באפר׳ 2020 ב-4:06 מאת ‪Matthew Donoughe‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Justin-CB** [comment]
Have you read the wiki?
https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#web
Note that ruffle is alpha-quality software and does not support content in iframes yet.

**Comment by lordwars** [comment]
Oh, I am very need this for iframe. all my website have flash games (.swf)
based on another games sites. I put iframe in my website and the game run.
When did you think you will rollout a new version that compatible with
iframes? its very urgent.

‫בתאריך שבת, 11 באפר׳ 2020 ב-0:29 מאת ‪Justin-CB‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by jtvjan** [comment]
The reason your code didn't work is because you need to use `type="module"` when working with ECMAScript modules. Your script tag should look something like this:

```html
<script type="module" src="script.js"></script>
```

If you just want to use the polyfill (replaces regular objects and embeds with Ruffle) you don't need to use ES imports, just put the [latest nightly](https://ruffle-rs.s3-us-west-1.amazonaws.com/builds/web/ruffle_web_latest.zip) somewhere on your server and reference it using a script tag.  
As for iframe support, see issue #475. However, even if support is merged, note that it won't work if the iframe is from a different domain, because of a security feature called the same-origin policy. If it's referenced using an embed, you'll still have to make sure that their site has CORS headers in place.

**Comment by Justin-CB** [comment]
There is an iframe fix in the works, but it hasn't been tested. I can build it for you, but as jtvjan said, it might still not work, depending on the site you're getting the iframe from's CORS policy.

**Comment by Justin-CB** [comment]
Now that the fix has been merged, all you need to do is download the latest nightly build from:
https://ruffle-rs.s3-us-west-1.amazonaws.com/builds/web/ruffle_web_latest.zip
Extract the zip and upload the files inside (they may be in a folder) to your website.
Then follow the instructions at:
https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#polyfill
You need to use the "Advanced Usage" instructions to enable all the polyfills.
Ruffle is currently alpha/pre-alpha, so not many games will work.
You will probably need to proxy the cross-origin iframes or convince the webmasters of those sites to add ruffle themselves.
