### ISSUE TITLE
[Question] Is there, or planning for controls on video only SWFs?

### ISSUE THREAD

**Issue by thebestnom** [ruffle-rs/ruffle#503]
I have video only swf that I remeber that on flash it should have streaming control, I didn't see anything on the roadmap, and I thought I would ask

**Comment by Herschel** [comment]
Yes, this is within the scope of the project! Not much thought nor effort has been put into it quite yet, though; the main issue will be figuring out clever ways to do it on the web platform (i.e., can we leverage the H264 decoder built into the browser, while still keeping the video in the normal Flash display flow?)

**Comment by thebestnom** [comment]
leverging H264 doesn't mean to convert it frame by frame in real time?

**Comment by thebestnom** [comment]
isn't easier to make a single cotrols that would be used by all platforms?

**Comment by Herschel** [comment]
That's the question -- someone has to do the decoding. On desktop we will use something like libx264/ffmpeg. These can theoretically be cross-compiled to WebAssembly, or we could use some other web decoding library, but the performance will be bad compared to the native decoder bundled within the browser. Instead of duplicating a decoder in Ruffle, possibly we can leverage the web media APIs to decode the video using the browser itself.

(Other video formats such as Flash Screen Video will not have browser support regardless, so we would have to bundle the decoder in Ruffle.)

**Comment by thebestnom** [comment]
Oh, I didn't know flash well enough, I tought flash have it's own format when in swf... so how it's working currently?

**Comment by Justin-CB** [comment]
Most newer video-only SWF's use h.264 for video, which is natively supported by web browsers, & I think ruffle already leverages that for decoding. Older & some newer video-only SWF's use h.263 or screen video, which ruffle does not currently support on the web platform, but for which support will probably be added later.

**Comment by thebestnom** [comment]
My original question is on older flash video, which I think are made in flash itself... Im not sure the decoding, will there be controls allowing skipping and backward in the video?

**Comment by Herschel** [comment]
Ruffle will only display player controls if the original SWF file also has controls. It will not create controls if they did not exist originally.

At the moment Ruffle does not support any video format.

If you'd like the extract the video from the SWF, you should try JPEXS Flash decompiler (https://github.com/jindrapetrik/jpexs-decompiler/releases), which should allow you to extract the video from the SWF. Then you could use it on your website in a `<video>` tag to have seeking controls (or upload it to YouTube).

**Comment by Herschel** [comment]
A possible enhancement would be to scubber to allow general seeking through a main SWF timeline (and this would also handle the case of a `DefineVideoStream` tag which are tied to the timeline), but this wouldn't handle streaming videos played with e.g. the `NetStream` class.

**Comment by thebestnom** [comment]
Thanks for the answer, is it something I'll be able to help, or is it a core team decision? I don't think I the files use `NetStream`

**Comment by Herschel** [comment]
It's a question of what's possible; play/pause buttons are possible, and we need it anyway to properly pause an SWF when it's on another tab, for example.

But seeking is difficult, because SWFs can be constructed in a variety of ways, with any number of videos, buried in any place. It would only be possible for a small subset of SWFs, so I'm not sure if it's worthwhile to try to implement if the feature could be confusing and only work for a small amount of SWFs.
