### ISSUE TITLE
Remaining issues regarding AS3 builtin class properties and type casts

### ISSUE THREAD

**Issue by adrian17** [ruffle-rs/ruffle#5075]
1. As a followup to https://github.com/ruffle-rs/ruffle/pull/4422 , seems like property traits' types are not respected? Given:
```
	public class Test extends MovieClip {
		var x: Number;
		public function Test() {
                    this.x = undefined;
                    trace(this.x);
		}
	}
```
It prints `undefined`, while it should print NaN.

Note that in other cases, the coercion runs correctly:
```
var x: Number;
x = undefined;
trace(x);
```

2. Builtin function traits do not have their parameter types set, so no type coercions can occur automatically.

We _generally_ happen do the corresponding coercions manually, but for more complex types we fail to do that. For example, `point.equals({x: 10, y: 10})` should error at runtime type check, while currently it can return `true`, because the builtin function simply accepts both a Point and an object with x-y fields.

This is probably a harder issue, and a general solution might involve generating type declarations from PlayerGlobal.swc; also it'd probably mean refactoring(removing?) all the manual coercions we wrote.

3. Some builtin types like Point do not have a typed trait for fields like `x`, `y` at all.

Similar to the previous one, possibly slightly easier as it doesn't involve editing all the functions we already wrote.

(note that for this to be useful, (1) needs to be fixed too.)

**Comment by adrian17** [comment]
FYI @kmeisthax

**Comment by kmeisthax** [comment]
Number 1 appears to be a genuine oversight, I almost certainly should have added a `coerce_to_type` in `set_property`/`init_property`. I think I forgot to implement return type checking, too.

For number 2 and 3 I originally considered adding metadata for all builtins in #4422, but the problem was that it interfered with the static traits in #4249 - `Multiname<'_>` isn't a const-compatible type. (`Multiname<'static>` doesn't work, I tried) We'll need a `StaticMultiname` and related types that allows coercion into `Multiname<'_>` if we want to have type annotations on builtins.

**Comment by Lord-McSweeney** [comment]
All of the above issues have been resolved since.
