### ISSUE TITLE
Rendering test framework

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#523]
This is inspired by me spending an hour debugging why gradient-strokes don't work after some changes I made, only to learn that they didn't work before my changes too.

Today it's very hard to know if anything regresses with rendering swfs, or even if they actually improve. I don't know exactly what all works and what doesn't work, without having to go make a  bunch of swfs and test it all myself and hope that I got most cases. We need to automate this.

In an ideal world, I think we'd have a bunch of swfs and reference images from the official Flash player, and compare them to automatic screenshots from Ruffle. Unfortunately, rendering isn't deterministic basically anywhere, so even comparing ruffle vs ruffle won't be a success.

I propose that we try to go somewhat low tech and just get something in place today, so that we can revisit this in the future with improvements - and be able to prove one way or another that we did or did not break rendering with any given commit.

# What we need...
Firstly, let's make a tool that takes in a swf, uses a given rendering method, and takes screenshots of each frame. Easy as that. This should be trivial for desktop, I don't know how much work it will be for web?

In addition to that, we will need to start collecting SWFs to test with. These should be made for Ruffle so we don't run into copyright/distribution issues, and we will host them somewhere along with screenshots from the official Flash player as "gold standard". We should document exactly what's unique about each one, too.

**We should encourage everybody who wants to help to gather test SWFs**. Let's document how to make them, let's document how to use the tool, let's empower volunteers to help us develop.

# Later...
We can improve the tool. Let's make it run on a whole directory at once. Let's make it run with every rendering engine available. Can it do a really simple "this is 100% the same, don't worry" and at least rule the obvious cases out? How can we get this involved in CI?

We can improve the swf collection. Where can we properly store them, long term? Maybe we have a small website running that has each swf and screenshots of each renderer + gold standard. Maybe we just drop them all in a separate repo and call it a day.

# Thoughts?
Is there a better way to do this? Who wants to volunteer with getting started on this? :D

**Comment by ROBERT-MCDOWELL** [comment]
A kind of tool that analyzing folders of swf would be nice indeed,
like adobe scout on steroid
https://www.adobe.com/devnet/scout/articles/adobe-scout-getting-started.html

**Comment by Herschel** [comment]
This is definitely a good idea -- you can check out Dolphin's [FifoCI](https://fifoci.dolphin-emu.org/compare/4891635-4889700/) for some inspiration of this taken to the fullest.

We could add a `RenderBackend::dump_frame` to grab the last rendered frame, or build this on top of render target functionality (we need this for other things as well).

We probably want to grab specific frames for testing instead of running through an entire SWF, in order to test specific issues and avoid preloaders. To start, we could manually construct single-frame SWFs of certain issues. We could also add a hotkey to the debug build to "capture" a frame, and dump that single frame to a separate SWF (or some other format that serializes the display list).

I also have a big mental list of problematic scenes from SWFs that I have permission to use :)

**Comment by Dinnerbone** [comment]
Now that the exporter tool landed, the next step will be for @Herschel to make a repo under the ruffle-rs org for test files. We'll have the tool run on there on some frequency and commit the images it generates. If we ever see that there's a diff, we can open an issue here to fix it.
