### ISSUE TITLE
[Attack of the Puppybots] Laser attack fired from a fixed location

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#5277]
## **Describe the bug**
In 'The Powerpuff Girls: Attack of the Puppybots', a problem occurs when you switch characters (Using keyboard 'X' key) and then attack ('space' key).

The laser (bullet?) fired by the character is fixed at the position where the character was switched. After that, even if the character attacks while moving, the laser will only fire in place.

[powerpuff-girls-attack-of-the-puppybots.zip](https://github.com/ruffle-rs/ruffle/files/7147729/powerpuff-girls-attack-of-the-puppybots.zip)

### Original (Adobe Flash Player)
https://user-images.githubusercontent.com/75052171/132947149-03240da2-1486-4ed2-80d2-861400bf976e.mp4

### Ruffle Nightly 2021-09-11
https://user-images.githubusercontent.com/75052171/132947162-c39c0b12-ea15-41ce-b25e-ee3815a0beab.mp4

## **Expected behavior**
When the character attacks, the laser should be fired based on the character's position.

## **Is the problem with the Ruffle desktop app, extension, or self-hosted version?**
Tested on self-hosted & Desktop.

## **What platform are you using?**
 - OS: Windows 10 21H1 x64
 - Browser: Chrome Latest
 - Ruffle: 2021-09-11 Nightly

**Comment by Toad06** [comment]
Thank you for filling an issue.

This actually appears to be a (very old) regression. The game works as expected in the builds from [nightly-2020-11-30](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2020-11-30) to [nightly-2020-12-27](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2020-12-27).

Running a bisect shows that commit https://github.com/ruffle-rs/ruffle/commit/8d707bc6ab747ae5039ce629f07c09aabfac2553 is the one causing the issue here.

---

Before realizing it was a regression, I took a look at the file using JPEXS.

In `\__Packages\clsPlayer`, there's an inline function `this.mGpx.onKeyUp`. I added some `trace`s:

```
trace(this);
trace(_root.mc_player);
```
Both of these log "_level0.mc_player" in Flash and Ruffle, when you shoot.

```
trace(this._x);
trace(_root.mc_player._x);
```
- In Flash, both of these log the same value when you move along the x axis and shoot. This statement is still true when you switch characters.
- In Ruffle, both of these log the same value when you move along the x axis and shoot. But this is no longer the case when you switch characters, as `this._x` will now always return the position where the first character was switched, affecting the position of lasers and bullets which are created as follows:
`_loc4_ = new clsParticles(_global.game.idNumActor,_global.player.typeBullet,_global.player.bullet,this._x,this._y,_loc5_,0,0,[100,100],[100,100,100,100],0,0);`

---

Finally the code when you switch characters is located in `\frame 28\DoAction` (`_root.onEnterFrame`).
