### ISSUE TITLE
Some flash files temporarily shows a white screen with GPU disabled

### ISSUE THREAD

**Issue by Danct12** [ruffle-rs/ruffle#5379]
### Describe the bug

When Chromium is launched without GPU acceleration (--disable-gpu), some flash files temporarily shows a white screen then recovers.

These shows a white screen but after sometime they recover:
https://z0r.de/L/z0r-de_3701.swf
https://z0r.de/L/z0r-de_3707.swf
https://z0r.de/L/z0r-de_5044.swf

### Expected behavior

All the flash files should display graphics like what it used to look like.

### Affected platform

Self-hosted version

### Operating system

Arch Linux

### Browser

Chromium 94.0.4606.61

### Additional information

During the white screen moments, browser console prints a bunch of these:

```
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 94ms
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 95ms
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 101ms
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 90ms
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 87ms
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 87ms
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 87ms
ruffle.js:1 [Violation] 'requestAnimationFrame' handler took 88ms
...
```

**Comment by torokati44** [comment]
I can reproduce this, and the issue is that the `requestAnimationFrame` callback takes too long to finish, so Chrome/ium drops the frame.
See this screenshot of a profile here:
![image](https://user-images.githubusercontent.com/288816/135172322-2339421c-559a-4c3f-86d6-33075e7836b1.png)

The main culprit seems to be `update_texture`, calling `bitmap_to_png_data_uri`, and `deflate` within it..
Maybe we should look into doing much lighter compression; or none at all; turning up the optimization level for that package; or finding an alternative solution for drawing images, not involving a data URI?

**Comment by torokati44** [comment]
I just checked the `Compression::Rle` option for the PNG encoder, and it is indeed very fast, but does not solve the problem, as now the `...set_src...` call in wasm-bindgen got really slow, most likely because it has to deal with a much larger data URI.

**Comment by torokati44** [comment]
`Compression::Huffman` doesn't work either, that still takes too long.

Maybe there is a setting to ask Chromium not to drop any frames, no matter how long they take?
