### ISSUE TITLE
Momentarily inserted flash embeds aren't removed using ruffle

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#542]
Some scripts(for flash detection, I think) momentarily insert a flash embed(or object), then immediately remove it. However, this doesn't work with ruffle, and the console displays an error to the effect that the element cannot be removed because it no longer exists in the child tree.

**Comment by Justin-CB** [comment]
It looks like, for objects at least, if we remove the "src" attribute, then we could put the ruffle-object inside of the object tag. Embeds are a different story, we could potentially overlay the ruffle player over top of the embed and add an event handler for if the embed is removed.

**Comment by Justin-CB** [comment]
Also, we could just use `width:100%;height:100%` for the size of objects, rather than having to set a default.

**Comment by Herschel** [comment]
SWFObject does this for more accurate version detection, the code in question is here:
https://github.com/swfobject/swfobject/blob/master/swfobject/src/swfobject.js#L196-L215

The good news is that it's harmless; the version detection falls back to using the `plugins` array and everything otherwise works, so it seems relatively low priority to me. It would be nice if we could squelch the error in some way, but I'd like to avoid complex workarounds (instead of placing the `ruffle-object` inside the `object`, could we keep the old `object` on the DOM instead, and simply hide it+remove all attributes?).

**Comment by Toad06** [comment]
Or just don't convert "objects" and "embed" who have no "src" and "data" attribute? I don't know if this could have any downside, though.

Eg in ruffle-object.js:
```
static is_interdictable(elem) {
	if(!elem.src && !elem.data) {
		return false;
	}
	// rest of code...
}
```

**Comment by Herschel** [comment]
@Toad06 I like that solution!

The only thing I was worried about was that swfobject error handler might assume the Flash version is 8 (https://github.com/swfobject/swfobject/blob/master/swfobject/src/swfobject.js#L207), but this never runs. It bails out after 10 failures, `removeChild` succeeds, and all is okay.

This reminds me: at some point we should also support the methods that the Flash object provides, such as `GetVariable` that SWFObject uses.
