### ISSUE TITLE
Accented characters aren't displayed

### ISSUE THREAD

**Issue by BMadelaine** [ruffle-rs/ruffle#5435]
### Describe the bug

On a french teaching swf file, accented characters are not displayed as it should be.
![image](https://user-images.githubusercontent.com/50694525/136362052-ead65893-ffad-4b71-ade7-6d8707365f78.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/50694525/136362113-d9083d1a-a73a-494b-a069-aeef5111c1f9.png)

### Affected platform

Browser's extension

### Operating system

Windows 7

### Browser

Mozilla Firefox 92.0.1 64 bits

**Comment by torokati44** [comment]
These characters should now be available in the fake device font since #6224 got merged.
And since the issue was not that the font is wrong, but that some characters are missing, I think this can be closed now. Feel free to reopen if you don't agree.
To also have correct (system) fonts, #1862 should be fixed indeed.
