### ISSUE TITLE
Error on https://web.archive.org/web/20021110135258/http://www.metroid.com:80/fusion/

### ISSUE THREAD

**Issue by SuperFeatherYoshi** [ruffle-rs/ruffle#5456]
### Describe the bug

![M](https://user-images.githubusercontent.com/13864894/136802237-56212beb-6825-4173-abd0-b3dc11cfd136.PNG)
All the buttons work, but for some reason, none of the content gets displayed

### Expected behavior

Images, text, etc, to be displayed correctly.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Google Chrome 92.0.4515.131

**Comment by Toad06** [comment]
Thanks for the report.

The reason why it doesn't work is that a different inner SWF file should be loaded each time you click a button. Unfortunately, archive.org has not saved any of these files (they all throw a 404 - not found), so nothing is displayed. The same thing happens when the page is run with the official Flash Player.

There's unfortunately nothing we can do here.
