### ISSUE TITLE
avm1: `_parent` can hold a different value depending on SWF version

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#5502]
Frame 1:
```
MovieClip.prototype.move = function()
{
   trace("// trace(_parent)");
   trace(_parent);
   _X = _X + 1;
};
```

Frame 2 in a DefineSprite:
`move();`

Samples: [parent_swf.zip](https://github.com/ruffle-rs/ruffle/files/7364436/parent_swf.zip)
_Note that these are the same samples as the ones you can find in "tests/tests/swfs/avm1/target_clip_swf5/" (or "/target_clip_swf6/"), only the traces are changed._

---

`_parent` has the following value:

Flash Player:
- SWFv5:  _level0
- SWFv6: undefined

Ruffle (any SWF version): undefined

**Comment by Herschel** [comment]
This is a difference of the "base clip" behavior in SWFv5 and higher. ("base clip" is a separate kind of 'this' that describes which movie clip code is running on, and determines which clip will be affected by GotoFrame actions, etc.).

```
MovieClip.prototype.move = function()
{
   trace("// trace(_target)");
   trace(_target);
   trace("// trace(_parent)");
   trace(_parent);
   _X = _X + 1;
};
```

SWFv5: `_target` is `/instance1`.
SWFv6+: `_target` is `/`.

**Comment by Herschel** [comment]
Looking at it a little more, this is a consequence of #768. `_parent` ends up going through our `MovieClip.prototype._parent`, which would be equivalent to doing `this._parent`. Instead, `_parent` should be set as a normal var somewhere in the activation, and it looks like SWF5 needs to use `base_clip()._parent`'s parent instead of `this._parent`.
