### ISSUE TITLE
[Forest Brat] An incredibly loud and distorted sound is played.

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#5655]
### Describe the bug

In 'Forest Brat', when the game starts, the Ruffle plays a very loud and grotesque sound, unlike the usual calm background music.

Turn on the sound and compare.
**In the case of ruffle video, the sound is very loud and torn, so be sure to turn the speaker volume down sufficiently before checking.**

[Forest Brat.zip](https://github.com/ruffle-rs/ruffle/files/7531793/Forest.Brat.zip)

## 🔊 Original (Adobe Flash Player)
https://user-images.githubusercontent.com/75052171/141614494-ae3a64af-1de3-4f0a-abd1-ae74a2b35155.mp4

## 🔊 Ruffle (Nightly 2021-11-13) - ⚠ Beware of the loudness!! ⚠ 
https://user-images.githubusercontent.com/75052171/141614498-1d5bd608-3199-4cbe-88ce-3300b23dd2e1.mp4

### Expected behavior

It should have a normal sound output like the original video.

### Affected platform

Self-hosted version

### Operating system

Windows 10 x64

### Browser

Google Chrome 95

**Comment by relrelb** [comment]
Seems like #5218 wasn't sufficient; This SWF plays the `"bees"` sound very loudly because:
1. In frame 20, DoAction 7, the line `beeSound.setVolume(beeVolume);` actually sets the volume to `i32::MIN` as `beeVolume` is `undefined`.
2. The DoAction in frame 1 sets the global volume to 25.

This causes `SoundTransform::concat` to calculate the effective volume of `"bees"` as `-0x80000000 * 25 / 100 = -0x20000000`, making the shifts in the `display_object::SoundTransform` -> `SoundTransform` conversion do nothing.
Instead I think the shifts (which in fact can be `& 0x3fffffff`) should be moved to `SoundTransform::concat`, which will silence the intermediate values.

**Comment by Jmousy** [comment]
Thanks for the quick response and fixing the problem! 😄
