### ISSUE TITLE
Linting/formatting for JS code

### ISSUE THREAD

**Issue by Herschel** [ruffle-rs/ruffle#570]
Since the project has a non-negligible amount of JS code, it might be useful to enforce linting and formatting for the JS files and add this to the automated CI builds.

I'm not a web developer, so I'm not sure what the standard tools are here -- I guess ESLint (https://eslint.org/)?

**Comment by Dinnerbone** [comment]
Great idea!

I use eslint with most of my projects, but do you have any opinions on the actual code style it should enforce? Or just "match what we have now"?

**Comment by Justin-CB** [comment]
I prefer having the `{` on the next line after a function declaration & the `}` on a separate line from `else`. I also like having spaces around operators(`+`, `-`, `&&`, `=`, `==`, etc.), tho I don't always remember to put them. I also prefer to indent with tabs rather than spaces, as it's quicker in a text editor & tab width is customizable.

I also realize that you don't have to listen to me at all.

**Comment by Herschel** [comment]
I don't have strong opinions on particular style; mainly it's nice to automate it because it is one less thing to worry about, allows us to focus more on code and not worry about style nits. Maybe just use ESLint default to start.

The only style decision I'd really think about is naming convention for functions/variables, since this is user-facing and should be agreed upon before we locked into an API by release. Currently we are using `lower_snake_case` to match Rust, but JS APIs tends to favor `lowerCamelCase`, so it's worth considering which we prefer.

**Comment by Justin-CB** [comment]
Should this be closed by #577 ?
