### ISSUE TITLE
Error on https://freegames.org/mahjong-tea/

### ISSUE THREAD

**Issue by ollycrush** [ruffle-rs/ruffle#5744]
# Error Info
Error name: ReferenceError
Error message: WebAssembly is not defined
Error stack:
```
ReferenceError: WebAssembly is not defined
    at https://freegames.org/js/ruffle/ruffle.js:1:32014
    at e (https://freegames.org/js/ruffle/ruffle.js:1:32588)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://freegames.org/mahjong-tea/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.34
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-20
Channel: nightly
Built: 2021-01-20T01:07:01.467Z
Commit: 75967e377576cad9a679f1172d0b7f6e5ffd85c0

**Comment by danielhjacobs** [comment]
This issue was using a version of Microsoft Edge that included Super Duper Secure mode. This issue was most likely a result of enabling that mode, which did not allow the execution of WebAssembly, required by Ruffle. Since then, Super Duper Secure mode was renamed Enhanced Security Mode, and a new WebAssembly interpreter was released for that mode, which means Ruffle should now work even with that enabled. However, it may be slow, as noted in <https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#im-trying-to-use-ruffle-on-microsoft-edge-but-it-runs-extremely-slowly-or-i-get-a-something-went-wrong-error>. As such, closing this issue.
