### ISSUE TITLE
Text positioning is off with ruffle

### ISSUE THREAD

**Issue by Justin-CB** [ruffle-rs/ruffle#594]
This is part of #592 but also, I've noticed this with the flash versions of these animations:
http://justinbesterportfolio.xp3.biz/DArts/Animate/ghost.php
http://justinbesterportfolio.xp3.biz/DArts/Animate/fire.php
http://justinbesterportfolio.xp3.biz/DArts/Animate/fire2.php
You can compare them against the flash player or the video versions.
Basically, the 1st word seems to be positioned correctly, but the following words overlap with the 1st one & aren't wrapped correctly.

**Comment by kmeisthax** [comment]
Text labels are off because we currently do not properly implement all of Flash's legacy dynamic text support. I'm currently in the process of doing this, but it will take a while to finish. (You can spy on the increasingly misnamed `edittext-html` branch on my copy of the repo if you're interested.)

**Comment by Herschel** [comment]
The main issue is alignment (centering). I have some small fixes that will the fix the current branch that will be merged once I implement text field variables, pending @kmeisthax  full HTML changes.
