### ISSUE TITLE
if ruffle added "check for update"

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#5944]
Flash player added "check for update" this is new version update

i think ruffle is new update
if he added check update 2022?
![Untitled470_20211230110758](https://user-images.githubusercontent.com/80902993/147737741-5863200a-866f-4250-9d08-9889c95fa065.png)

**Comment by Poopooracoocoo** [comment]
The problem is that this could only serve as a link to the Ruffle page to download the extension again as extensions cannot be updated outside of the CWS or AMO. The Firefox situation is slightly different as Firefox can handle updates for signed extensions iirc. And at this point with such rapid development, there's not much of a point to just let you know that there is a new update the following day, y'know? But I'm not a dev here so yeah. My 2c as someone who dislikes seeing outdated versions of the ruffle extension. :)

**Comment by n0samu** [comment]
Ruffle now updates automatically via the Chrome/FF extension stores.
