### ISSUE TITLE
Ruffle breaks kongregate https://www.kongregate.com/games/Cheslava/heart-of-galaxy

### ISSUE THREAD

**Issue by kotenok2000** [ruffle-rs/ruffle#6141]
### Describe the bug

Html5 games do not start.
Flash games also do not start.

### Expected behavior

Kongregate works

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Google Chrome 97.0.4692.99

**Comment by n0samu** [comment]
Can confirm that even HTML5 games on Kongregate don't start with Ruffle enabled. This is because Ruffle includes a feature that tricks websites into thinking that Flash Player is enabled. When Kongregate detects that Flash Player is enabled, it uses a Flash-based loader to load the game, even if the game itself is HTML5. And Kongregate's Flash-based loader uses ActionScript 3, which is not yet supported by Ruffle. So all games, even HTML5 games, fail to load.
This is especially unfortunate because Ruffle's feature of faking the Flash player is actually really helpful on most sites. Many Flash sites would prompt you to install the Flash Player instead of showing their Flash content if Ruffle did not include this feature.

**Comment by kotenok2000** [comment]
Maybe add ability to enable and disable ruffle per site?

**Comment by n0samu** [comment]
That sounds like a good idea to me!
