### ISSUE TITLE
[Moon Fairy] Drag&Drop does not work properly from Ruffle Nightly 2022-01-25

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#6169]
### Describe the bug

The issue I found was with 'Moon Fairy', but similar games may also have issues.

In Moon Fairy, I can't dress by drag and drop. Attempting to drop after mouse dragging will not release the item.

[moon-fairy.zip](https://github.com/ruffle-rs/ruffle/files/7965764/moon-fairy.zip)

### Worked: ~2022-01-24 Nightly
![2022-01-24-worked](https://user-images.githubusercontent.com/75052171/151697118-fce16576-058c-492a-b09a-cdd224e6932d.gif)

### Not Worked: 2022-01-25 Nightly~
![2022-01-25-not-worked](https://user-images.githubusercontent.com/75052171/151697133-4351a4c1-7f77-4c88-a239-6153fb4d783a.gif)

There were no issues until Nightly build 22/01/24, but started having issues on 22/01/25.

### Expected behavior

Drag&Drop should release the item at the correct location.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2

### Browser

Google Chrome 97

**Comment by Toad06** [comment]
Thank you for the excellent bug report, as always.

I ran a bisect and it appears that da50d444600e1764780f7abc01bb21c70b277d57 (PR #6123) is the commit causing the regression. It actually restores the behaviour which existed in [nightly-2021-06-11](https://github.com/ruffle-rs/ruffle/releases/tag/nightly-2021-06-11) and the older versions.

I will try to investigate more later.

**Comment by Jmousy** [comment]
Thanks for your quick response and detailed explanation!

Sorry for not being able to analyze the code myself, but I'll be more than happy to provide information if necessary. 😄

**Comment by Toad06** [comment]
So the issue is in the `menu_fun()` function in `\frame 234\DoAction_3`. Here is a part of the code in the function:

```
// ...
_mc[_loc6_].onPress = function()
{
   sound4();
   var _loc2_ = this._name.substr(1,2);
   var _loc3_ = this._name.substr(3,2);
   if(_loc2_ != 0)
   {
      this._visible = false;
      // etc.
   }
};
_mc[_loc6_].onRelease = function()
{
   this._visible = true;
   // etc.
};
_mc[_loc6_].onReleaseOutside = function()
{
   this._visible = true;
   // etc.
};
// ...
```

1- When clicking on an item in the game, it triggers the `onPress` event above which disables the visibility of the item in the menu.
2- Releasing the mouse then triggers the `onReleaseOutside` event in Flash Player but nothing happens in Ruffle. This is because we never fire button events when they are invisible, but `onReleaseOutside` seems to be the exception.

Here is a [smaller file](https://github.com/ruffle-rs/ruffle/files/7966764/sample.zip) that also reproduces the issue.

**Comment by Jmousy** [comment]
I have confirmed that the issue is resolved in build 2022-01-31.
Thanks for the quick resolution!
