### ISSUE TITLE
Error on https://collegesexgames.com/play.php?flash=sexymaid

### ISSUE THREAD

**Issue by wtnbsbr** [ruffle-rs/ruffle#6325]
# Error Info
Error name: ReferenceError
Error message: WebAssembly is not defined
Error stack:
```
ReferenceError: WebAssembly is not defined
    at https://collegesexgames.com/ruffle/ruffle.js:1:68321
    at Array.forEach (<anonymous>)
    at Object.yi.f.wasm (https://collegesexgames.com/ruffle/ruffle.js:1:67974)
    at https://collegesexgames.com/ruffle/ruffle.js:1:35888
    at Array.reduce (<anonymous>)
    at Function.yi.e (https://collegesexgames.com/ruffle/ruffle.js:1:35865)
    at o (https://collegesexgames.com/ruffle/ruffle.js:1:2651)
    at o.next (<anonymous>)
    at https://collegesexgames.com/ruffle/ruffle.js:1:2951
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: false

# Page Info
Page URL: https://collegesexgames.com/play.php?flash=sexymaid

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.56
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-12
Channel: nightly
Built: 2021-01-12T00:55:17.048Z
Commit: 73d123091014e190f4bc4d8edf98cab2e671cc3a

**Comment by danielhjacobs** [comment]
This issue was using a version of Microsoft Edge that included Enhanced Security Mode before it allowed execution of WebAssembly, required by Ruffle. This issue was most likely a result of enabling that mode. Since then, a new WebAssembly interpreter was released for that mode, which means Ruffle should now work even with that enabled. However, it may be slow, as noted in https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#im-trying-to-use-ruffle-on-microsoft-edge-but-it-runs-extremely-slowly-or-i-get-a-something-went-wrong-error. As such, closing this issue.
