### ISSUE TITLE
Youtube Videos Don't play

### ISSUE THREAD

**Issue by CoolDino1** [ruffle-rs/ruffle#6504]
### Describe the bug

![Screenshot 2022-03-21 at 09-49-17 About Buddy Personal Testimony](https://user-images.githubusercontent.com/98194448/159287085-e0ac99c2-8483-464c-80e5-4424e9601686.png)
Youtube videos that were embedded using Flash won't play with Ruffle. I am using today's version. Here is a link to a page with this problem: https://sarahbethonline.com/buddydavis/aboutbuddy/testimony.html
The Youtube video still exists but won't play.

### Expected behavior

I expected the youtube video to play.

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Mozilla Firefox version 98.0.1

### Additional information

It says 'Ruffle wasn't able to run the Flash embedded in this page. You can try to open the file in a separate tab, to sidestep this issue. Open in new tab

**Comment by danielhjacobs** [comment]
This is the same issue as #4030, except that these videos don't work even without Ruffle because of [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content#fixing_mixed_content_issues). The YouTube embed source being used on this https website is http.

The reason Ruffle is able to even attempt to load the content, while the embed without Ruffle cannot, is because of the default value of upgradeToHttps (https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#list-of-options).

**Comment by CoolDino1** [comment]
Thanks!
