### ISSUE TITLE
HUGE LAG when referencing objects

### ISSUE THREAD

**Issue by starblinky** [ruffle-rs/ruffle#6516]
### Describe the bug

If you reference objects, it will cause HUGE lag. I have attached an example SWF file and FLA.

This ONLY seems to be an issue on weaker machines, ie: mobile, old desktop computers, laptops. (I have only tested this on iPhone 12 + iPad Pro, but I have several reports of major lag happening in my game on desktop+laptop). 

Every object reference is accumulative, the more uses of it the quicker it will start to lag. But even if you have just 1 usage, if I load up the SWF on mobile and wait a few minutes it will start to lag from 60 FPS down to <8 FPS. (Tested on Newgrounds) 

Here is a screenshot from my iPhone 12, you can see it is running at 10 FPS when it should be at 60 FPS:
![IMG_B6B200353B48-1](https://user-images.githubusercontent.com/51274080/159911240-40d523cf-6599-4f4f-b932-4810354c4bff.jpeg)

ATTACHED FLA EXAMPLE:
[TEST BUG.zip](https://github.com/ruffle-rs/ruffle/files/8341264/TEST.BUG.zip)

**I can even delete all but 1 "CHICKEN MC" and if I wait a few minutes, it will cause severe lag on iPhone 12 and the phone will start to become hot.** 

### Expected behavior

It should not lag this badly. 

### Affected platform

Online demo

### Operating system

ios 15.3.1

### Browser

Safari

**Comment by adrian17** [comment]
After the leak was fixed in https://github.com/ruffle-rs/ruffle/pull/6528 , has this improved?

**Comment by foumart** [comment]
I think the problem that @starblinky highlighted was fixed with the mentioned update (the demo has a constant 26fps on my android device and doesn't drop below that in time).
However there are other similar problems with a game I'm working on, which are not present when running on the Flash Player (tested with Adobe Scout). Basically with each next level loaded the game starts to lag more and more. I will create a bug report as soon as I have a test case.
