### ISSUE TITLE
A serious error caused my computer to have a blue screen

### ISSUE THREAD

**Issue by URGERKING** [ruffle-rs/ruffle#6817]
### Describe the bug

When I open [seer.61.com](url) Not even waiting for the page to load,My computer began to crash and turned into a blue screen a few seconds later.
I previously found that some scripts I installed on tempermonkey would conflict with ruffle.But I didn't expect such a serious problem.

The second time, I turn off the function of tempermonkey in advance(not disable tempermonkey from the manager) and entered [seer.61.com](url).But flash was still not loaded correctly.I'm a little depressed. Maybe it's because of the problem of ActionScript 3.0. (I'm only a layman)
But  when I pressed the button of tampermonkey,the error happened again.My computer began to crash and turned into a blue screen a few seconds later.

I'm not sure if there is any connection between these two add-ons.But I don't want to try again

### Expected behavior

Flash shouldn't crash my computer even if it doesn't load correctly

### Affected platform

Browser's extension

### Operating system

Windows 7 x64

### Browser

Mozilla Firefox 99.0.1

### Additional information

[042822-43321-01.zip](https://github.com/ruffle-rs/ruffle/files/8580776/042822-43321-01.zip)
[042822-50294-01.zip](https://github.com/ruffle-rs/ruffle/files/8580778/042822-50294-01.zip)

looks like github doesn't support to upload dmp files,So I renamed these dmp files...

**Comment by n0samu** [comment]
These crashes are unrelated to Ruffle. As far as I can tell, that site does not load any Flash content at all unless you use one of the special web browsers that it tells you to download (which I have not tested). Ruffle does not run on that page at all.

I analyzed your dump files and found that the crashes are due to faulting network drivers, specifically tdx.sys and netio.sys. The cause of this would be either failing hardware or corrupted system files. You should probably run System File Checker (SFC) to repair your system, and if that fails, reinstall Windows.

**Comment by URGERKING** [comment]
ok...seems like it's my computer's problem.sorry for wasting your time
