### ISSUE TITLE
Minecraft tower defense has severe issues with ruffle

### ISSUE THREAD

**Issue by Juliods** [ruffle-rs/ruffle#6960]
### Describe the bug

The bug happens some time after the game starts. The towers start shooting and the monsters are eliminated, however as soon as the time between waves start if there are still any mobs on the screen they become immortal. Forcing an early loose 

The skip wave button cam be used multiple times in-between waves instead than only once every wave.

link to the game: https://www.clickjogos.com.br/jogos/minecraft-tower-defense

### Expected behavior

The mobs should be vulnerable to tower fire at all times and traps too. And the skip wave button should only be capable of being used once every wave.

### Affected platform

Browser's extension

### Operating system

Ubuntu 20.04LTS

### Browser

Mozzila Firefox 100

### Additional information

URL to the game: https://www.clickjogos.com.br/jogos/minecraft-tower-defense

**Comment by Aaron1011** [comment]
That link is giving me a 404

**Comment by Aaron1011** [comment]
This will be partially fixed by https://github.com/ruffle-rs/ruffle/pull/5492

**Comment by n0samu** [comment]
Looks like this game has been removed from Clickjogos. Checking Wayback, they were using a very old version of Ruffle. I'm able to reproduce the issue with the Skip Wave button there: https://web.archive.org/web/20220531221315/https://www.clickjogos.com.br/jogos/minecraft-tower-defense
But it seems like the bug had already been fixed in the latest version of Ruffle at the time this issue was created.

As for the issue with mobs being immortal, that will be fixed by #9447.
