### ISSUE TITLE
Amorphous+ - Newly loaded sprites flicker for a few seconds, only with canvas renderer

### ISSUE THREAD

**Issue by NotWearingPants** [ruffle-rs/ruffle#6969]
### Describe the bug

SWF: [Amorphous+](https://cache.armorgames.com/files/games/amorphous-plus-2044.swf)

When loading this SWF in the online demo, the game itself works as intended, but some sprites flicker.

It seems to me that it happens for sprites for at most 5 seconds from the first time they are loaded, and after that all future uses of the same sprite don't flicker anymore.

In the video you can see the red plus at the top-right of the menu screen flicker, the menu items as I hover over them (they change to their "hovered" sprite), the player character, and also the green enemies.

https://user-images.githubusercontent.com/26556598/168320439-41938695-8c19-43e6-9d17-f2b91b324753.mp4

The game also runs very slow which is apparent in the video, as opposed to the same SWF running on native flashplayer on the same machine which is considerably faster. This is not the main point of the issue but if it can be profiled somehow it would be awesome

### Expected behavior

Expected the red plus to stay visible at all times, the menu items to switch to a hovered state without disappearing, the player character to be visible, and also the green enemies always come from beyond the edge of the screen so you can see that 2 of them appear in the middle of screen, because they were invisible and then suddenly rendered.

### Affected platform

Online demo

### Operating system

Windows 10

### Browser

Edgium 101

### Additional information

Ruffle version: nightly 2022-05-13

Issue number: nice

**Comment by Herschel** [comment]
This is an issue in our canvas renderer when using the drawing API or shape tweens that fall back to the SVG renderer. This happens for shapes that use gradients, etc... Loading this SVG data is an asynchronous op in JS land, causing the delay before they appear. The easiest thing to do would be to force use of the canvas drawing path for these cases somehow, even if it means certain things like focal gradients may look incorrect.

The good news is that this isn't an issue in the WebGL renderer, which was mistakently broke and should be fixed in tomorrow (5/14) build by #6970. But we should still try to fix this in the canvas renderer.

**Comment by NotWearingPants** [comment]
Well it was a coincidence that I checked it right when the WebGL renderer had the #6970 bug, it's now working great in nightly 2022-05-14, a whole lot faster as well.
