### ISSUE TITLE
[Naval Fighter] Game doesn't start when plane is selected and incorrect level is displayed

### ISSUE THREAD

**Issue by Jmousy** [ruffle-rs/ruffle#7008]
### Describe the bug

[Naval Fighter.zip](https://github.com/ruffle-rs/ruffle/files/8708313/Naval.Fighter.zip)

In Naval Fighter, you need to select a plane to start the game, but clicking does not respond and the game does not progress.

![image](https://user-images.githubusercontent.com/75052171/168813334-dac779d8-97fb-420b-ae2c-c15505319f8f.png)

Compare it with Adobe Flash Player (original) in the image above, you can see that the displayed stage number and description are different. (Level 5 instead of Level 1, description is different...)

(The two images above are before the start of the first stage, for Ruffle, check it out on Nightly 2022-05-17.)

### Expected behavior

The correct information should be displayed and the game should start after selecting the plane.

### Affected platform

Self-hosted version

### Operating system

Windows 10 21H2

### Browser

Google Chrome 101

**Comment by Toad06** [comment]
Thanks for the report.

This seems to be an issue with the XML parser. The following warning is logged into the console:
> Couldn't replace_with_str inside of XML constructor: error while parsing attribute at position 35: Attribute key must be directly followed by = or space

---

`<?xml version="1.0" encoding="windows-1251"?><tag attr1="hello"attr2="world">`

A code like this one errors in a browser because of a missing space between `"hello"` and `attr2`. This case happens a bunch of times in the XML string of this game.

---

`new XML("<?xml version=\"1.0\" encoding=\"windows-1251\"?><tag attr1=\"hello\"attr2=\"world\">");`

This code outputs:
- in Flash Player:
`<?xml version="1.0" encoding="windows-1251"?><tag attr1="hello" attr2="world" />`

- in Ruffle:
`<tag attr1="hello" />`

[Sample](https://github.com/ruffle-rs/ruffle/files/8712021/xml.zip)

**Comment by Herschel** [comment]
@relrelb Any interest in fixing this one? Not sure if quickxml can be massaged to handle this.

**Comment by relrelb** [comment]
`quick-xml` can be patched further, but I think we should better implement our own Flash-compatible XML parser, because this is not the only incompatabilty. For instace, Flash accepts attributes surrounded by single quotes, which is banned in XML spec and rejected by `quick-xml`.

**Comment by Herschel** [comment]
I agree, we will need all of our own XML, HTML, and CSS parsers to match the Flash behavior.

Just a note that AVM2 has a separate XML parser + E4X implementation as well, which I'm fairly certain is more faithful to the spec (though I haven't checked this). The original AVM1 era XML implementation is still accessible in AS3 via `flash.xml.XMLDocument`.

**Comment by Jmousy** [comment]
![image](https://user-images.githubusercontent.com/75052171/178136402-77a53659-b687-4f83-88dc-a800888e709f.png)

I found another game (Rush Race) from the same developer (Game Team) has a similar problem, so I'll leave it for reference.

[rush-race.zip](https://github.com/ruffle-rs/ruffle/files/9078681/rush-race.zip)

**Comment by n0samu** [comment]
Fixed by #10471
