### ISSUE TITLE
Visual bug in http://www.zefrank.com/showcase/maya/index.html

### ISSUE THREAD

**Issue by CrazyNaut** [ruffle-rs/ruffle#7261]
### Describe the bug

In the animation linked below, the planets are meant to orbit around the sun. Instead, they seem to all be stuck in the sun's position.
http://www.zefrank.com/showcase/maya/index.html

https://user-images.githubusercontent.com/57976747/174501209-f32d7217-1118-4e5a-94bb-872bbbaf83cd.mp4

### Expected behavior

https://user-images.githubusercontent.com/57976747/174501227-36a4be13-3b2f-46e3-a378-c13bce27b2a0.mp4

### Affected platform

Desktop app

### Operating system

Windows 10

**Comment by Toad06** [comment]
Scratch my previous post, in fact the values are not set because the following code in `\DefineSprite (19: sun1)\frame 1\DoAction` doesn't work as expected:

```
i = 1;
while(i < numplanets)
{
   attachMovie("ball","ball" + i,i);
   this = eval("ball" + i); // <-- this line
   this.tar = "_parent.sun";
   this.speed = 0.01;
   // (...)
}
```

- In Ruffle, `this` is always "_level0.instance49.planet", probably because `this` is not mutable (as mentioned in #7239).

- In Flash Player, the value of `this` changes every time it is set ("_level0.instance4701.planet.ball1", "_level0.instance4701.planet.ball2", etc.).
