### ISSUE TITLE
Super Mario Star Scramble not looking correct on extension

### ISSUE THREAD

**Issue by mero09-99** [ruffle-rs/ruffle#7424]
### Describe the bug

going to the website: https://playmariogames.com/super-mario-star-scramble
and playing the game with the Ruffle Extension, latest version 2022-07-16 the background is cut off and black if you go up
works fine on ruffle demo 
works fine on flash player
![smssre](https://user-images.githubusercontent.com/109428504/179361868-22d021f2-415c-42a6-b9b5-1e9b19fcebef.png)
issue
![smssrd](https://user-images.githubusercontent.com/109428504/179361877-b4271978-a007-4981-bd38-0498139875ab.png)
no issue

### Expected behavior

the background continues as far as you can see, even while up high or jumping

### Affected platform

Browser's extension

### Operating system

Windows 10

**Comment by n0samu** [comment]
I don't blame you for thinking that this is an issue with the Ruffle extension! However, I tried it in a Flash-supported web browser and it behaves the same way:
![image](https://user-images.githubusercontent.com/71368227/179362229-785bbd39-ed3f-4e67-b930-6c397d86df3a.png)
This problem occurs because of the settings that the website used when embedding the SWF. Specifically, it was embedded with `bgcolor="#000000"`, which overrides the sky color that is supposed to fill the background when Mario moves upwards in the level. (`#000000` represents a black color).
You may also note that the movie's natural resolution is 600 by 400 pixels, but the website embedded it at 700 by 520 pixels. That doesn't contribute to this issue, but it shows once again how careless this website was!

**Comment by mero09-99** [comment]
The website is the issue, okay!
Thanks for saying!
this issue is solved.
