### ISSUE TITLE
Ruffle Error on https://www.electricman.space/

### ISSUE THREAD

**Issue by ItWorksOnLocal-png** [ruffle-rs/ruffle#7460]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at <anonymous>:1:876
    at https://electricman.space/ruffle/ruffle.js:1:67052
    at Array.forEach (<anonymous>)
    at vi.f.wasm (https://electricman.space/ruffle/ruffle.js:1:66979)
    at https://electricman.space/ruffle/ruffle.js:1:35299
    at Array.reduce (<anonymous>)
    at vi.e (https://electricman.space/ruffle/ruffle.js:1:35276)
    at o (https://electricman.space/ruffle/ruffle.js:1:2595)
    at o.next (<anonymous>)
    at https://electricman.space/ruffle/ruffle.js:1:2895
```

# Player Info
Allows script access: true
Player type: Object
SWF URL: electricman.swf
Param game: electricman.swf
Attribute 0: undefined
Attribute 1: undefined
Attribute 2: undefined
Attribute 3: undefined

# Page Info
Page URL: https://www.electricman.space/

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-02
Channel: nightly
Built: 2021-01-02T00:44:12.942Z
Commit: 83c32e8693ec7d585713d457599b87b81e2057c3

**Comment by n0samu** [comment]
This error occurs because the website loads Ruffle from `https://electricman.space`, which counts as a different "origin" from `https://www.electricman.space` for the purposes of CORS. The site owner should change the script tag to load Ruffle from a relative URL to prevent this problem. But to fix this issue for yourself, you can simply access the site from https://www.electricman.space instead.
