### ISSUE TITLE
Error on https://archive.org/details/stick-rpg-complete

### ISSUE THREAD

**Issue by LiamCU1** [ruffle-rs/ruffle#7705]
# Error Info
Error name: TypeError
Error message: WebAssembly: Expected Response or Promise resolving to Response

# Player Info
Allows script access: false

# Page Info
Page URL: https://archive.org/details/stick-rpg-complete

# Browser Info
Useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
OS: Win32

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-12-16
Channel: nightly
Built: 2021-12-16T00:12:02.888Z
Commit: 07c533045604f42610bb3ca5480d9443b78f7fb7
Is extension: false

# Note
This is happening for all games on the internet archive.

**Comment by n0samu** [comment]
Thanks for reporting. Can you check if the issue is still occurring now? If so, follow these steps to send us a more details about the error:
1. Right-click an empty area of the game's webpage and click Inspect
2. Click the Console tab
3. Right-click any of the console messages and click "Save all Messages to File"
4. Comment here and attach the file that was saved

**Comment by n0samu** [comment]
Hi, we've found a solution to this issue which you can find here: https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#internetarchive
