### ISSUE TITLE
Error on https://thesbcommunity.com/games/sb_dunces/

### ISSUE THREAD

**Issue by bnagle22** [ruffle-rs/ruffle#7746]
# Error Info
Error name: TypeError
Error message: Failed to fetch
Error stack:
```
TypeError: Failed to fetch
    at https://www.thesbcommunity.com/games/ruffle/ruffle.js:1:67826
    at Array.forEach (<anonymous>)
    at mi.f.wasm (https://www.thesbcommunity.com/games/ruffle/ruffle.js:1:67753)
    at https://www.thesbcommunity.com/games/ruffle/ruffle.js:1:35882
    at Array.reduce (<anonymous>)
    at mi.e (https://www.thesbcommunity.com/games/ruffle/ruffle.js:1:35859)
    at o (https://www.thesbcommunity.com/games/ruffle/ruffle.js:1:2645)
    at o.next (<anonymous>)
    at https://www.thesbcommunity.com/games/ruffle/ruffle.js:1:2945
    at new Promise (<anonymous>)
```

# Player Info
Allows script access: true

# Page Info
Page URL: https://thesbcommunity.com/games/sb_dunces/

# Browser Info
Useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
OS: MacIntel

# Ruffle Info
Version: 0.1.0
Name: nightly 2021-01-11
Channel: nightly
Built: 2021-01-11T00:53:04.486Z
Commit: cce3a8199d48ecbce536a0e49efd501d97a2b370

**Comment by bnagle22** [comment]
game does not load

**Comment by n0samu** [comment]
This error occurs because the website loads Ruffle from https://www.thesbcommunity.com, which counts as a different "origin" from https://thesbcommunity.com for the purposes of CORS. The site owner should change the script tag to load Ruffle from a relative URL to prevent this problem; if you can, please contact the website owner and ask them to fix the problem. But to fix this issue for yourself, you can simply access the site from this URL instead: https://www.thesbcommunity.com/games/sb_dunces/
