### ISSUE TITLE
In Caravaneer in some places the letter Q does not render

### ISSUE THREAD

**Issue by tanriol** [ruffle-rs/ruffle#7976]
### Describe the bug

Steps to reproduce:
Start Caravaneer at https://www.newgrounds.com/portal/view/381821
Click through, click Story mode.
Enter "testqQend" as character name. Click Play, click through the text screen. Wait a few seconds for the character to arrive to the town.
Click the sheriff house (the building with star). Check the character name in the first dialogue option. Notice that the capital Q does not render.

### Expected behavior

The name should be rendered as entered.

### Affected platform

Browser's extension

### Operating system

Linux (Gentoo)

### Browser

Firefox Nightly (106.0a1 2022-09-13)

**Comment by n0samu** [comment]
The same problem also occurs in the official Flash Player:
![image](https://user-images.githubusercontent.com/71368227/190021464-0ce0bfdb-f3fb-4d1f-b15d-cb15cd85c890.png)
The problem occurs because the SWF's embedded bold Arial font is missing an uppercase Q:
![image](https://user-images.githubusercontent.com/71368227/190021599-7af1cb5d-a5aa-48a2-9c90-2591dd16759f.png)

Side note: the SWF also embeds a light version of the Arial font which is missing an uppercase J:
![image](https://user-images.githubusercontent.com/71368227/190021688-cd992f0e-b18d-464d-ad98-b0fb2eb27b32.png)
Maybe you can find a way to expose this issue in the game as well! 😄

**Comment by tanriol** [comment]
Hm, interesting, thank you. I should have cross-checked against the official Flash player and not against their Windows exe build (which seemed to be some Flash player version and worked correctly in Wine).

**Comment by n0samu** [comment]
Ah yes, that is interesting! Here is the SWF extracted from the EXE file that you mentioned: [caravaneer.zip](https://github.com/ruffle-rs/ruffle/files/9561329/caravaneer.zip)
With this SWF, the uppercase Q appears in both Flash Player and Ruffle:
![image](https://user-images.githubusercontent.com/71368227/190024056-8584fd65-4007-46d7-9cc1-9c9f9099e341.png)
Yet the embedded Arial fonts in the SWF do *not* have the missing characters added! I guess the way that this version of the game renders text must be different in some other way.
