### ISSUE TITLE
Got RustError when constructing AVM2 side of movie clip of type Preloader

### ISSUE THREAD

**Issue by pnkapadia64** [ruffle-rs/ruffle#8130]
### Describe the bug

I'm getting the following error on loading a game
`Got RustError("Cannot access property http://adobe.com/AS3/2006/builtin::split of null or undefined") when constructing AVM2 side of movie clip of type Preloader`
It also gives the ActionScript3 unsupported content [warning](https://github.com/ruffle-rs/ruffle/wiki/Frequently-Asked-Questions-For-Users#why-did-i-get-a-message-about-unsupported-content), but not sure if the above is also related to the unsupported content warning.

### Expected behavior

Do I wait for the ActionScript 3.0 completion of [tasks](https://github.com/ruffle-rs/ruffle/issues/1368)? Or am I missing something that can be fixed on my end?

### Affected platform

Self-hosted version

### Operating system

macOS

### Browser

Chrome

**Comment by n0samu** [comment]
Can you please provide a link to the game or attach a zip file containing the game files?

**Comment by pnkapadia64** [comment]
Yes sure, here is the game file
[wonderputt-game.swf.zip](https://github.com/ruffle-rs/ruffle/files/9690628/wonderputt-game.swf.zip)

**Comment by n0samu** [comment]
Ah yep, it's that version of Wonderputt, it should work fine once more AS3 built-in methods are implemented. For now you can use the version from the official site instead, which has a less complicated preloader. http://www.dampgnat.com/wonderputt/

**Comment by pnkapadia64** [comment]
I tried the one from the above website and it gives the same error: 
[wonderputt2.swf.zip](https://github.com/ruffle-rs/ruffle/files/9697311/wonderputt2.swf.zip)

I also found wonderputt on https://www.newgrounds.com/portal/view/577928 which uses the same Ruffle version as I do and successfully renders the game.

**Comment by pnkapadia64** [comment]
@n0samu 
I'm trying the following 
[wonderputt2.swf.zip](https://github.com/ruffle-rs/ruffle/files/9705012/wonderputt2.swf.zip)
with settings
` polyfills: false,
          autoplay: true,
          warnOnUnsupportedContent: false,
          `
and still gives an error. I checked out the game on https://www.gameflare.com/online-game/wonderputt/ as well and that works too with the same ruffle nightly version '2022-09-28' as mine

**Comment by n0samu** [comment]
Oops, I misunderstood the issue. Both versions of the game that you uploaded are identical and both of them work. The only issue is that the game needs to be loaded via a URL or file path because when Ruffle loads SWF data directly, it sets the URL to null, which the game's code does not expect. And that makes sense because as far as I know, this scenario is impossible in real Flash Player.

Anyway the point is that this is one of the Flash files that doesn't work in the Ruffle Web Demo. It should work in the desktop app and on websites though.

**Comment by pnkapadia64** [comment]
@n0samu Yes I did upload the swf file and test with the URL: https://files.crazygames.com/wonderputt.swf and https://files.crazygames.com/wonderputt/3/wonderputt3.swf which gives the same error on the ruffle demo page and my website.

**Comment by n0samu** [comment]
@pnkapadia64 Oops, I forgot to reply until now. But I've uploaded that Wonderputt SWF to my Github.io site as a reference: https://n0samu.github.io/ruffle-testing/?swf=wonderputt.swf
Let me know if that helps or if you're still having issues.

**Comment by n0samu** [comment]
Next time please ask these kinds of questions in a GitHub discussion instead of replying to an unrelated issue.
But yes, `load` can already accept a URL parameter, see https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#advanced-usage
Unfortunately Ruffle cannot report the download progress of the SWF, though.

**Comment by ReinoutStevens** [comment]
Hey @n0samu I work together with @pnkapadia64, and was replying in the context of this issue.

**Comment by n0samu** [comment]
Ah I didn't realize that, sorry.

**Comment by ReinoutStevens** [comment]
no worries, it also wasn't clear from my end :)

**Comment by n0samu** [comment]
Oh, I finally understand the issue you are having. You are trying to load the game via an ArrayBuffer using DataLoadOptions, right? Unfortunately, when loading an SWF this way, its URL is set to null, which was not even possible in Flash. A lot of AVM2 movies try to perform operations on the SWF URL, which fails in this case. Wonderputt is one game with this issue, but I just found several others including [Gravity Duck](https://n0samu.github.io/ruffle-testing/gravityduck.swf) and [Gravity Duck 2](https://n0samu.github.io/ruffle-testing/gravityduck2.swf). This is even more annoying because it means that the games don't work via the Ruffle Web Demo or Archive.org's Emularity system. See my Archive.org upload for example: https://archive.org/details/flash_gravityduck

**Comment by ReinoutStevens** [comment]
Yes, that is a nice summary :)
In the meantime, we are going to move away from using the ArrayBuffer and just not have any progress reporting ( on the download of the swf file ).

**Comment by ReinoutStevens** [comment]
Yeah that's an approach we also considered, but decided not to risk it. SWF files are usually fairly small anyway, and most time is spent on ruffling loading the file than the actual download.

**Comment by n0samu** [comment]
Alright, I've made a feature request to change this behavior. (See linked issue above.)
Hopefully someone will make this improvement!
