### ISSUE TITLE
web: drag of cube is flickering

### ISSUE THREAD

**Issue by KMicha** [ruffle-rs/ruffle#817]
In Flash, you can drag the "1 kg air cube" smoothly. Only the selected values are updated.
(On the right side, quiz answers can be picked.)

In ruffle the drag also works, but stutters. All values are shown, selection is not possible.
(On the right side, answering the quiz is not possible.)

See http://www.webgeo.de/k_230_en/#3
(on http://www.webgeo.de you can switch between using ruffle or using flash)

Version: ruffle_web_2020-06-02
![flash_k_230_en3](https://user-images.githubusercontent.com/1667683/86591350-b5d4b280-bf91-11ea-8ff4-0913a8f5567f.png)
![ruffle_k_230_en3](https://user-images.githubusercontent.com/1667683/86591393-cb49dc80-bf91-11ea-9878-50fec5d06d3d.png)
[k_230_03.zip](https://github.com/ruffle-rs/ruffle/files/4878746/k_230_03.zip)

**Comment by hatal175** [comment]
Tried taking a look.
1. cube is flickering because the drag action uses the parent's local coordinates to set x,y for the cube. But for some reason, this makes the parent move as well so their local coordinates change and flickers. Not sure what flash does differently.
2. checkboxes don't work because I think (not sure) that the code sets getState to _parent but when it executes, it uses the scope that it was defined in and not the scope it was assigned to. Slightly too complex for me at this point.

**Comment by Lord-McSweeney** [comment]
Still occurring. The checkboxes work correctly, though. One thing to note is that the stuttering only occurs when your mouse cursor is between 900 hPa and 1000 hPa (no flickering occurs when the mouse is in the small spaces at the ends). The values shown in the checkboxes section stutter even when the mouse is outside of the 900 hPa and 1000 hPa area.
