### ISSUE TITLE
BioGems Almost working but gets error after first match (AS3)

### ISSUE THREAD

**Issue by desertking** [ruffle-rs/ruffle#8270]
### Describe the bug

http://www.kongregate.com/games/mochigames/biogems - This game almost works with ruffle. There is a problem with the sitelock thou as it is made to check for http, too bad we live in https time. So you have to check locally or remove the sitelock to test it otherwise =)

This error drops after the first match 3 is made.

0183127e:0x4b0680 Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x84ba9a8 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x5f60854 }))) : RustError("Cannot access property ::length of null or undefined")

### Expected behavior

The match should work and the game progress.

### Affected platform

Self-hosted version

### Operating system

All

### Browser

All

**Comment by n0samu** [comment]
Oh, turns out it is still possible to play the game by accessing the SWF file over HTTP directly using the Ruffle extension: http://chat.kongregate.com/gamez/0012/2465/live/Main_secure.swf?kongregate_game_version=1315422023
With the Log Level set to Info, an additional error appears immediately before the one you mentioned:
`BitmapData.lock - not yet implemented`
I think that is the cause of this issue.

**Comment by desertking** [comment]
A little update. The game now works until after the first match won. It's stuck on the upgrades screen. Dunno if that is the error: 

core/src/display_object/bitmap.rs:275 Got error when creating AVM2 side of bitmap: RustError("Param <Unnamed Parameter> (index 0) was missing when calling ")

**Comment by desertking** [comment]
Seems to work now?

**Comment by waspennator** [comment]
Tested it out on my end, won my first match and didn't get stuck on the upgrade screen too.
