### ISSUE TITLE
idk how to open the app

### ISSUE THREAD

**Issue by hellohihihiiihhello** [ruffle-rs/ruffle#828]
idk how to open the app

**Comment by zanzlanz** [comment]
Check out the [Wiki](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle), the [build instructions](https://github.com/ruffle-rs/ruffle/wiki/Building-Ruffle), or even the [live online demo](http://ruffle.rs/demo) to get started.

Otherwise, do you have any other details about what you're trying to do?
