### ISSUE TITLE
Errors on Snack Dash when using website wrapper

### ISSUE THREAD

**Issue by RadikAlice** [ruffle-rs/ruffle#8365]
### Describe the bug

Character falls through the floor

### How to reproduce:
- Load game
- Skip version check with right click, 'Play'
- Click 'Play Game'

Played through via https://www.newgrounds.com/portal/view/347912/format/flash?emulate=flash

### Expected behavior

Game loading level graphics and collision properly

### Affected platform

Browser's extension

### Operating system

Windows 10

### Browser

Firefox 106.0.1

### Additional information

Shockwave version check also happens when played via Newgrounds Player
Collision does load properly with it, but graphics aren't right on it either
Must be due to the bypassing of the version check
Could perhaps be skipped by spoofing the expected version

**Comment by n0samu** [comment]
The character falls through the floor because `BitmapData.hitTest` is unimplemented:
`[WARN  ruffle_core::avm1::globals::bitmap_data] BitmapData.hitTest - not yet implemented`

To make this easier to test, I've hacked out the faulty Flash Player version check. Here's the hacked SWF:
[snackdash_noversioncheck.zip](https://github.com/ruffle-rs/ruffle/files/9848540/snackdash_noversioncheck.zip)

The glitched graphics are actually due to a problem with Adobe Flash Player. At some point between Flash Player versions 9 and 10, something changed that broke this game. It's quite a funny coincidence, considering that the broken Flash Player version check inadvertently blocks Flash Player versions 10 and above for being *less than 8.* (This is a surprisingly common thing for old Flash games though - before the release of Flash Player 10, a lot of games would only check the first digit of the Flash Player version.)

Anyway, the game is perfectly playable in the Flash Player 9 projector from here: https://archive.org/details/MacromediaFlashProjectors.7z

**Comment by RadikAlice** [comment]
Just tested the hacked version, works exactly as intended
And I see, a combination of Adobe's infinite wisdom and the classic Y2K bug-style problem
Thank you for the dedication, I lack the low-level knowledge to really help besides testing so. Thanks a ton

**Comment by waspennator** [comment]
Character no longer seems to be falling through the floor as of the latest nightly now that #10209 is merged in.

![Snack Dash Ruffle](https://user-images.githubusercontent.com/78768499/226496810-918df99d-8180-4618-b629-0f072c2f65c7.png)

**Comment by n0samu** [comment]
And thanks to #8961, the player version can be spoofed, for example in the desktop player you can use the command-line option `--player-version=9`.

**Comment by RadikAlice** [comment]
> Character no longer seems to be falling through the floor as of the latest nightly now that #10209 is merged in.
> 
> ![Snack Dash Ruffle](https://user-images.githubusercontent.com/78768499/226496810-918df99d-8180-4618-b629-0f072c2f65c7.png)

Downloaded the latest nightly just to test, can confirm
