### ISSUE TITLE
fire boy and water girl light temple not working

### ISSUE THREAD

**Issue by ROBlNET13** [ruffle-rs/ruffle#8412]
i cant press play on the swf i got from newgrounds https://www.mediafire.com/file/rnqlrgcon2u9n70/Fireboy_and_Watergirl_in_The_Light_Temple.swf/file 
here is the file

**Comment by Calvin304** [comment]
it seems this is caused by Avm2ButtonData.hit_area having its parent set in Avm2ButtonData::create_state and not removed in this case. this causes incoming mouse events to get transformed twice; once because it's assumed hit_area has no parent in <Avm2Button as TInteractiveObject>::mouse_pick so the mouse event is transformed to local space and again through TDisplayObject::hit_test_shape.

**Comment by Calvin304** [comment]
this is fixed in #8744
