### ISSUE TITLE
Browser extension interferes with a game using Ruffle by default

### ISSUE THREAD

**Issue by RB565** [ruffle-rs/ruffle#8413]
### Describe the bug

I was playing Doeo on https://www.newgrounds.com/portal/view/436085. It can use Ruffle without the extension. I have the extension and the game doesn't load. I turned it off and it loads, must've been interfering with it.

### Expected behavior

A game that can use Ruffle without the extension should still work even if I have the extension installed.

### Affected platform

Browser's extension

### Operating system

Windows 10

**Comment by n0samu** [comment]
We've known about this problem for a long time but no one knows how to fix it 😦

**Comment by n0samu** [comment]
I've been looking more into this bug recently. I found that it's very reliably reproducible in Firefox if I:
1. Open a new tab
2. Go to any Newgrounds game URL
3. Click the Play button and wait for the game to load
4. Click the browser's Back button
5. Click the browser's Forward button
6. Click the game's Play button again.

You might have to repeat this a few times, but usually when I do this, I get a panic like the one below:

<details>
# Error Info
Error name: ChunkLoadError
Error message: Loading chunk 339 failed.
(error: https://uploads.ungrounded.net/ruffle_wrapper/lib/339.js)
Error stack:
```
__webpack_require__.f.j@moz-extension://056d6ecb-8d62-4b0d-8a0c-9b82c8483fc5/dist/ruffle.js?id=14365870406:207:29
__webpack_require__.e/<@moz-extension://056d6ecb-8d62-4b0d-8a0c-9b82c8483fc5/dist/ruffle.js?id=14365870406:71:40
__webpack_require__.e@moz-extension://056d6ecb-8d62-4b0d-8a0c-9b82c8483fc5/dist/ruffle.js?id=14365870406:70:67
fetchRuffle@moz-extension://056d6ecb-8d62-4b0d-8a0c-9b82c8483fc5/dist/ruffle.js?id=14365870406:511:31

```

# Player Info
Allows script access: true
(Cached) null

# Page Info
Page URL: https://uploads.ungrounded.net/ruffle_wrapper/ruffleembed.html?v=1.0.67&browsermode=default&props=%7B%22ruffle%22%3A%22%2Fruffle_wrapper%2Flib%2Fruffle.js%3F1682266221%22%2C%22public_path%22%3A%22%2Fruffle_wrapper%2Flib%2F%22%2C%22swf%22%3A%22https%3A%2F%2Fuploads.ungrounded.net%2F436000%2F436085_doeo_ng__3_.swf%3F1208811666%22%2C%22vars%22%3A%7B%22NewgroundsAPI_PublisherID%22%3A1%2C%22NewgroundsAPI_SandboxID%22%3A%2264466a8350f43%22%2C%22NewgroundsAPI_SessionID%22%3A%22%22%2C%22NewgroundsAPI_UserName%22%3A%22%26lt%3Bdeleted%26gt%3B%22%2C%22NewgroundsAPI_UserID%22%3A0%2C%22ng_username%22%3A%22%26lt%3Bdeleted%26gt%3B%22%7D%2C%22width%22%3A550%2C%22height%22%3A450%2C%22icon%22%3A%22https%3A%2F%2Fpicon.ngfiles.com%2F436000%2Fflash_436085_card.png%3Ff1607985359%22%2C%22warnOnUnsupportedContent%22%3Afalse%7D

# Browser Info
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Platform: Win32
Has touch support: false

# Ruffle Info
Version: 0.1.0
Name: nightly 2023-04-15
Channel: nightly
Built: 2023-04-15T00:19:19.513Z
Commit: ddb45f2cc2b9c5d9d4dbc5702cfbe907ffc49f2c
Is extension: false

# Metadata
</details>

This seems to be related to the unusual way that Newgrounds loads Ruffle:
```js
var script = document.createElement( "script" );
script.onload = function() {
	prereq.script = 1;
	console.log("ruffle.js loaded");
	preReqUpdated();
}
script.src = params.ruffle;
document.getElementsByTagName( "head" )[0].appendChild( script );
```
Depending on the timing of when the extension loads, sometimes the extension copy of Ruffle is what ends up loading on the page. But it doesn't know that it's the extension copy because the `isExtension` variable is only set in `polyfills.ts`, which doesn't run when the JS API is used. Still though, I don't know if this is what's causing the error. I don't understand why it's so timing-dependent.
