### ISSUE TITLE
Error on https://www.friv.cm/duck-life-5-treasure-hunt/

### ISSUE THREAD

**Issue by Gosteelers112** [ruffle-rs/ruffle#8447]
The game loads, but doesn't fully work, the game doesn't run as it did with flash.

**Comment by n0samu** [comment]
The issue I'm noticing is that collecting the coins doesn't work:
`Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x9360328 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x904f854 }))) : RustError("Cannot call null or undefined method ::getBounds of class coin")`
This should be fixed once #8397 is merged.

Are you seeing any other issues with the game?

**Comment by n0samu** [comment]
As predicted, that problem is now fixed. But I'm noticing some other issues with the game:
- It is very difficult to click the buttons to select the speed of your computer when the game first loads.
- Mousing over ducks in the town often doesn't show their speech bubbles, or can even show a speech bubble for the wrong duck.
- In the shop screens, mousing over the arrows does not scroll the screen up/down.
- With the Ruffle browser extension, the other ducks in the cave don't appear at all. But with the desktop app, they do.

**Comment by Lord-McSweeney** [comment]
The NPC ducks in the cave now appear; mousing over ducks shows the correct speech bubble, no matter where you are; and mousing over the up and down arrow keys now works.
