### ISSUE TITLE
Pipe Riders not supported AVM2

### ISSUE THREAD

**Issue by deividbinev12** [ruffle-rs/ruffle#8534]
### Describe the bug

https://user-images.githubusercontent.com/80902993/201509664-fd7cb477-9173-4991-a92d-f37414c10a3b.mp4

Ruffle Extension 2022-11-04

https://www.y8.com/games/pipe_riders

### Expected behavior

https://user-images.githubusercontent.com/80902993/201509783-49f7e651-d142-4e64-88ff-a2edd4a17d50.mp4

Flash Version

https://flashstorage.games/pipe-riders.html

### Affected platform

Browser's extension

### Operating system

Windows 11

### Browser

Edge

### Additional information

it's 3D flash game but, AVM2 is not supported 3D, WAFlash is error but, pipe riders like friv

**Comment by Lord-McSweeney** [comment]
I get an out-of-memory error in the console for me (Chrome 107): `WAFLASH> WAFLASH_NOTIFY_ABORT. Memory usage exceeded threshold!

Ar @ waflash.min.js?2022091801:1
`

**Comment by n0samu** [comment]
> I get an out-of-memory error in the console (unrelated to Ruffe) for me (Chrome 107): `WAFLASH> WAFLASH_NOTIFY_ABORT. Memory usage exceeded threshold!`
> 
> `Ar @ waflash.min.js?2022091801:1`

That's because you're playing the game with WAFlash, not Ruffle. flashstorage.games has a bar below the game that lets you choose what emulator to use.
![image](https://user-images.githubusercontent.com/71368227/206959187-88b28b98-2948-4171-bc2c-00284f061294.png)

**Comment by Lord-McSweeney** [comment]
The original issue is no longer present, but you cannot play levels, probably due to the following error: `Modifying an XML object is not yet implemented`.

**Comment by Lord-McSweeney** [comment]
New error:
```
Error dispatching event EventObject(EventObject { type: "closed", class: flash.events::Event, ptr: 0x7c6250 }) to handler FunctionObject(FunctionObject { ptr: 0x2706b50 }) : TypeError: Error #1009: Cannot access a property or method of a null object reference. (accessing field: unlink)
	at sandy.core.data::Polygon/set appearance()
	at sandy.core.data::Polygon/destroy()
	at sandy.core.scenegraph::Shape3D/__destroyPolygons()
	at sandy.core.scenegraph::Shape3D/destroy()
	at PipeLevel/CreateCylinderClay()
	at PipeLevel/CreateScene()
	at PipeLevel()
	at PipeGame/StartGame()
	at flash.events::EventDispatcher/flash::events::EventDispatcher::dispatchEvent()
	at PipeGame/DoorsClose()
```

Stub warnings:
```
WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.text.StyleSheet.setStyle()
WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.text.TextField.styleSheet setter
WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.text.TextField.condenseWhite setter
WARN core/src/stub.rs:126 Encountered stub: AVM2 flash.utils.Dictionary constructor with weak keys
```

**Comment by Lord-McSweeney** [comment]
Still happenning (see above comment).

**Comment by Aaron1011** [comment]
This is caused by a bug with how we handle dynamic object properties. In avmplus, deleting a dynamic property *never* triggers a rehash: https://github.com/adobe/avmplus/blob/858d034a3bd3a54d9b70909386435cf4aec81d21/core/avmplusHashtable.cpp#L147. This makes it possible to delete already-seen properties during iteration over an object, without disturbing the iteration order.

Unfortunately, this SWF seems to rely on that behavior - it deletes keys from `Material.m_oPolygonMap` while iterating over the keys of `Material.m_oPolygonMap`, and expects to be able to iterate over all the keys.

Separately - there seems to be some code in avmplus that tries to handle *adding* keys to map during iteration. However, it doesn't seem to produce a sensible result, based on my testing in Flash player. Hopefully, there aren't any SWFs that depend on the exact behavior when adding new keys.
