### ISSUE TITLE
give a custom url on runtime

### ISSUE THREAD

**Issue by A-UNUSED-ACCOUNT** [ruffle-rs/ruffle#859]
This should be a feature so there would be no more sitelocked games

**Comment by Dinnerbone** [comment]
This came up as a discussion on Discord a few months back. I think that whilst there may be legitimate use cases for this for old and unsupported content, ultimately this will only serve to enable theft and rehosting of other websites content, allowing people to monetise what isn't theirs. I don't think this is a feature I would support, sorry :(

Others may have another view, and ultimately it's @Herschel's decision - but I would suggest that preservation of old content would best be done through something like Flashpoint, possibly even using our desktop application in the future, but it's too easily abused on the web.

**Comment by manokara** [comment]
> I think that whilst there may be legitimate use cases for this for old and unsupported content, ultimately this will only serve to enable theft and rehosting of other websites content

Indeed, but like you mentioned at the end, maybe we could make the desktop player recognize URL checks and simply ignore them, while keeping normal behavior on the web, where it actually makes sense. I don't know how hard that could be, given that some developers could've obfuscated them in some way.

**Comment by Dinnerbone** [comment]
I think the desktop client will end up with a bunch of options like that, for supporting old content. It's just on web, where theft of flash games ran rampant, that we need to be careful.

**Comment by ROBERT-MCDOWELL** [comment]
I wonder if create a blockchain system for this case won't help....

**Comment by Lord-McSweeney** [comment]
This has been implemented on desktop with the `--spoof-url` option.

**Comment by Dinnerbone** [comment]
It's a feature on desktop now but for Web, it's simply not moral imo.

Yes you can "easily" (depending on your knowledge, skillset, and the swf in question) edit a swf to remove or change the sitelock, but then **you** are the one who has, essentially, committed copyright theft or whatever bad thing that can be classed as. The immoral act was yours, not Ruffle's.

For content that no longer works and cannot possibly work due to missing or renamed domains, we can add a specific fix for those games into Ruffle with our compatibility rules feature. If you know of such a game, please open an issue for it and we can make that content work again - as long as we believe there's no moral issue with doing so.

I know it's splitting hairs a little but it's a liability and morality thing, at the heart of it. We don't support people stealing content that was made to deliberately stop people from stealing content. We don't support copyright theft and adding such a feature on websites allows exactly that, even if sometimes it's for good reasons too.
