### ISSUE TITLE
Cat in Japan - error log

### ISSUE THREAD

**Issue by sodscg** [ruffle-rs/ruffle#8849]
### Describe the bug

`ERROR ruffle_core::avm2::events] Error dispatching event EventObject(EventObject { type: "enterFrame", class: flash.events::Event, ptr: 0x23c28340c20 }) to handler FunctionObject(FunctionObject(GcCell(Gc { ptr: 0x23c0fc2be98 }))) : RustError("Cannot set undefined property ::_cpmstar_lastshown on Some(Main)")`

### Expected behavior

probably no error

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[catinjapan.zip](https://github.com/ruffle-rs/ruffle/files/10261677/catinjapan.zip)

**Comment by n0samu** [comment]
The game works fine for me. An error message does not necessarily mean there is anything wrong. Is the game playable for you too?

**Comment by n0samu** [comment]
I beat the game in Ruffle. I'm happy to have been introduced to such a great game 😄 
![image](https://user-images.githubusercontent.com/71368227/208627536-0e5ad1d1-91e3-4f45-b617-7e3bef910041.png)

Anyway, closing this issue since the game works fine. Let me know if you're having an issue and I can reopen it.
