### ISSUE TITLE
Bullet Heaven 3 - Regression

### ISSUE THREAD

**Issue by sodscg** [ruffle-rs/ruffle#8850]
### Describe the bug

This was a game for one of the Newgrounds Flash Jams, and it seems to only be a black screen + music now
no log either

### Expected behavior

the game should be visible

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[Bullet Heaven 3 Prototype.zip](https://github.com/ruffle-rs/ruffle/files/10261754/Bullet.Heaven.3.Prototype.zip)

**Comment by Lord-McSweeney** [comment]
The WASM sends a GET request to `[path]/undefined`.

**Comment by Herschel** [comment]
Seems like this broke as a result of the loading/chunking pages. (It works on web, at least on the demo page -- might be because the demo page loads a local file all at once via JS and then feeds it to Ruffle)

The game contains no preloader code, so the SWF is streaming as fast as it can. On frame 2, the game does `gotoAndStop("titlescreen");`, which relies on that frame having been loaded, and the frame label seen. In Flash Player, this frame has already been loaded (`_framesloaded` is 20) and the seek succeeds. In Ruffle, `_framesloaded` is 2 so the seek fails, and the game stops on the current blank frame.

Along the same lines as #2435, this happens to work based on the specific loading behavior of the Flash Player, and we need to try to match it as much as possible.

**Comment by sodscg** [comment]
Its worth noting that this did used to work on Desktop, as the game was available on itch io with Ruffle, and the builds at the time had no problem either
here's the one that it came with

[ruffle.zip](https://github.com/ruffle-rs/ruffle/files/10262568/ruffle.zip)

**Comment by sodscg** [comment]
alternatively, 
https://kupo-games.itch.io/bullet-heaven-3-prototype

**Comment by Zinc-Exclamation** [comment]
this still on 2023-02-11

**Comment by sodscg** [comment]
As of 2023 - 01 -13, this is now no longer regressing :)
