### ISSUE TITLE
Castle Clout 3 - Buttons issue

### ISSUE THREAD

**Issue by sodscg** [ruffle-rs/ruffle#8852]
### Describe the bug

Ruffle is missing the buttons

![castleclout3](https://user-images.githubusercontent.com/102984201/208495931-dc1dcd55-c23b-411e-8d2b-c72b1a696626.png)

### Expected behavior

the buttons should exist

### Affected platform

Desktop app

### Operating system

Windows 10

### Additional information

[castleclout3.zip](https://github.com/ruffle-rs/ruffle/files/10261839/castleclout3.zip)

**Comment by Lord-McSweeney** [comment]
Nothing is shown in the console.

**Comment by n0samu** [comment]
Actually this is shown many times in the terminal:
`[WARN  ruffle_core::avm2::globals::flash::display::graphics] Graphics.beginBitmapFill: not yet implemented`
Looking at the game's `GameButton` class, you can see that its `draw` function uses `graphics.beginBitmapFill`. Because this is not implemented in Ruffle, the buttons are not drawn.

**Comment by sodscg** [comment]
Still invisible on latest

**Comment by sodscg** [comment]
![cc3b](https://user-images.githubusercontent.com/102984201/227744080-405477de-132b-43ed-9a0d-115974f7bfd8.png)
not invisible anymore, but not exactly correct

**Comment by sodscg** [comment]
![c3gr](https://user-images.githubusercontent.com/102984201/227744100-3a8b6757-c712-4b57-b4d5-ce3dfcbc5c38.png)
though, you can play the game now

**Comment by n0samu** [comment]
Fixed by #10630
