### ISSUE TITLE
IceCrystal swf file just scrolls downwards out of screen

### ISSUE THREAD

**Issue by rredford** [ruffle-rs/ruffle#9182]
### Describe the bug

It starts up fine but moves downwards out of screen area.
[IceCrystal.zip](https://github.com/ruffle-rs/ruffle/files/10429793/IceCrystal.zip)

### Expected behavior

It stays in area, showing "atoms" and crystal forming.

### Affected platform

Desktop app

### Operating system

linux mint 21.1

### Additional information

I only have swf. It's quite old project, dating from 2007, and I developed swf files by simply reverse engineering swf files and making my own swf files. Fun! 

So I do not have any abode proper source files. prl something? I forgot what their filename extension was.

**Comment by CUB3D** [comment]
The issue here is due to `nodeMode` which tries to redefine `this`:
```
function nodeMove(whichnode) {
  this = Nodecenter["n" + whichnode];
  this.vy += grav;
  ...
  this._x += this.vx;
  ...
```
In Flash this works but in Ruffle it doesn't and ends up moving the wrong object.

(Funnily enough, re-compiling the AS in jpexs with no real changes will make it work again, as it switches this function to use registers rather than properties)

**Comment by rredford** [comment]
So it's illegal move. How do I change it so it works properly? It was quite old and predates my college years lol
