### ISSUE TITLE
Panic attempting to reserve 18 exabytes of memory

### ISSUE THREAD

**Issue by Dinnerbone** [ruffle-rs/ruffle#92]
The file "401000/401799_pre_Scene_1202c.swf" in newgrounds.com.zip will crash when you attempt to load it, with "memory allocation of 18446744073709551614 bytes failed".

Running in debug shows that we're probably integer underflowing:
> thread 'main' panicked at 'attempt to subtract with overflow', ruffle\swf\src\read.rs:1035:32

**Comment by kmeisthax** [comment]
I have to wonder: what does this SWF normally do? Negative allocation usually is a sign of someone deliberately trying to tickle a memory safety vulnerability. Have to wonder if this one's malicious or something...

**Comment by Herschel** [comment]
Generally there are some SWFs with slightly malformed tags because of software differences (either issues in the official Flash IDE itself, or third-party SWF creation software).

In this SWF, a button action record (SWF19 p. 197) has an invalid CondActionSize of 2. Usually this length has to be at least 4. ffdec returns an error on this too.

I fixed the underflow, now it just returns a normal error for this tag and will no longer try to allocate a bajillion bytes. This will still error out in the scanner, but Ruffle will skip incorrect tags gracefully.

I should investigate what the official Flash Player does with this tag.
