### ISSUE TITLE
Firefox Ruffle Missing from the Firefox Addons Store

### ISSUE THREAD

**Issue by Beamy68** [ruffle-rs/ruffle#9655]
the link from the website is not working either

**Comment by n0samu** [comment]
Closing in favor of #9054. Also reported in #9618.

**Comment by rachel809** [comment]
its not even listed anymore  i get this everytime.. Oops! We can’t find that page

If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
    Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available [extensions](https://addons.mozilla.org/en-US/firefox/extensions/) or [themes](https://addons.mozilla.org/en-US/firefox/themes/), or by asking for help on our [community forums](https://discourse.mozilla.org/c/add-ons). idk what do somebody please contact them or fix this please it works on edge and google chrome but not firefox??

**Comment by n0samu** [comment]
Please see my previous explanation https://github.com/ruffle-rs/ruffle/issues/8799#issuecomment-1374391215
