### ISSUE TITLE
Renovate doesn't update Node.js dependencies

### ISSUE THREAD

**Issue by tsunamistate** [ruffle-rs/ruffle#9876]
Even though `renovate.json5` has a setting to update Node.js dependencies every month

```
{
            "matchLanguages": ["js"],
            "groupName": "Node.js dependencies",
            "extends": ["schedule:monthly"],
},
```

ever since repository migrated from `dependabot` to `renovate` in January 2023, there were no PRs to update them in either February or March, outside https://github.com/ruffle-rs/ruffle/pull/9374

`npm install` still lists 2 high level vulnerabilities: `http-cache-semantics  <4.1.1`, `ua-parser-js  0.8.1 - 1.0.32`, which are easily fixed by `npm update` or `npm audit fix`

Also, there are multiple updates available in top-level `package.json`
![image](https://user-images.githubusercontent.com/4958520/223094974-f3bf1fc0-dcc6-4ac7-9444-c40c848669f2.png)

**Comment by Dinnerbone** [comment]
The default fileMatch only looks for a package.json in the root, we need to adjust that to look in web dir

**Comment by Dinnerbone** [comment]
Actually no it looks like it does work. I've triggered the javascript update manually for now to see for sure.

**Comment by tsunamistate** [comment]
So, it looks like the schedule doesn't work?

Looking at Renovate docs, it looks like the wording is wrong (?)
https://docs.renovatebot.com/presets-schedule/#schedulemonthly

**Comment by Dinnerbone** [comment]
Looking into this some more, I think it's working fine - I triggered the one today manually but they were scheduled to happen.

The versions we depend on are `^foo` which already takes care of minor/patch level updates, so Renovate will only care about updating them to the next major version, which are not released very often.

I think, in fact, the biggest issue we have is that are aren't updating the lock file very often, which causes the minor/patch level updates to lag behind. I can open a PR to make Renovate renew the lock every month too.

But, for the issue here, I think it's working as intended.

**Comment by tsunamistate** [comment]
Well, good thing that it works! I just checked bot history and didn't find any PR's for Node deps, so thought something was broken.
IMO, #9877 should still be merged, vulnerability warning still persists, even after merging #9878
