### ISSUE TITLE
[Skeleton Park] Issue with a specific animation

### ISSUE THREAD

**Issue by Toad06** [ruffle-rs/ruffle#993]
In Skeleton Park, when two dogs meet each other, they begin to fight.
![sk1](https://user-images.githubusercontent.com/14274782/89828165-f8714800-db58-11ea-924a-26f6cfa77e94.png)

If you get into the brawl or if you get hit by another dog in the meantime, you will lose a life and a "Continue" button will appear:
- if you don't click this button quickly, the brawl will stop and the two dogs will become visible again. In Flash, they are hidden.
- if you click the button while the brawl still happens, the animation will still be displayed after the level restarts. This does not happen in Flash.
![sk2](https://user-images.githubusercontent.com/14274782/89828645-9bc25d00-db59-11ea-918e-50ce6dd989d6.png)

https://www.y8.com/games/skeleton_park

**Comment by Herschel** [comment]
Normally the dogs reappear after fighting because the code stores a reference to the dogs in question and restores them after the fight. However, the movieclip containing the enemy collision gets removed when the lost life screen appears, so the references to the dogs are invalid, and normally they don't reappear in Flash.

Ruffle doesn't emulate the behavior of removed clips properly; in AS2, removed movie clips go into a weird "ghost state" and can no longer be used, returning undefined for everything. Ruffle allows references to removed clips to continue to exist and be used as normal, even though they are no longer on the display list. This causes the dogs to reappear as if the game was still active.

**Comment by Zinc-Exclamation** [comment]
I confirm this happens on Ruffle ruffle-nightly-2022_07_10 still
